### ISSUE TITLE
Clarify documentation for Pending Pacts

### ISSUE THREAD

**Issue by pendsley** [pact-foundation/pact-jvm#1134]
In the pact-jvm docs for Pending Pacts

> You also need to provide the tags used to publish the providers main-line results (i.e. tags like prod or master).

https://github.com/DiUS/pact-jvm/tree/master/provider/junit5#pending-pact-support-version-410-and-later (And everywhere else Pending Pacts are mentioned)

This seems misleading the way it's worded, since you should set it to whatever the tag for the current branch is.

**Comment by uglyog** [comment]
would this make more sense?
> If your Pact broker supports pending pacts, you can enable support for that by enabling that on your Pact broker 
annotation or with JVM system properties. You also need to provide the tags used to publish the providers main-line results 
(you should set it to the current branch name). The broker will then label any pacts found that don't have a successful verification result as pending. That way, if they fail verification, the verifier will ignore those failures and not fail the build.

**Comment by pendsley** [comment]
The part that confused me was having "...main-line results" in there, followed up with "...tags like prod or master". I think if that was rephrased, maybe we wouldn't need the followup/clarification?

> If your Pact broker supports pending pacts, you can enable support for that by enabling that on your Pact broker annotation or with JVM system properties. **You also need to provide the tags that will be published with your provider's verification results.** The broker will then label any pacts found that don't have a successful verification result as pending. That way, if they fail verification, the verifier will ignore those failures and not fail the build.

That, followed by the code example might be enough?

**Comment by kflorence** [comment]
@uglyog i think this one can be closed as it was addressed by https://github.com/pact-foundation/pact-jvm/commit/d383ef75d32a0fe127d183cc30e994b389c856ea
