### ISSUE TITLE
[Usage question] Using Pact JVM with JUnit 5 in a CDI application

### ISSUE THREAD

**Issue by straurob** [pact-foundation/pact-jvm#1144]
I'm working on a prototype how to use Pact for contract testing in our application. While the basic setup, either with JUnit 5 or the Maven plugin, is working fine, I do have some trouble when it comes to seting up provider states.

Following the [documentation](https://github.com/DiUS/pact-jvm/tree/master/provider/junit) I'm aware of the @State annotation. So, a state setup method could look like this:

```
@State("user already exists")
public void createUser() {
  // ...
}
```

The problem I'm facing is this. Our application uses CDI, it is kind of heavyweight and so is its data model. Even for only creating a user, at minimum I would have to somehow inject the DAO for database access. For more complex provider states I would have to insert data across several tables in a consistent way. All of this would get kind of complex.

Are there any recommendations how to handle this? Some of my first ideas...

* Injecting the services, or at least the DAO, into the Pact provider state methods. This seems to create a new layer of complexity with something like Weld JUnit or Arquillan?
* Using Mockito to mock services. As there are functional tests for the services themselves, I'd go with that approach but I've only found examples for Spring Boot applications, _none for CDI_.
* Implementing a REST endpoint in the application dedicated to insert data. This would solve the dependency issues but the complex data model is still there, so I wouldn't gain much.

From what I know so far, I'd favor #2 though it contradicts the idea to "use as much production code as possible".

**Comment by uglyog** [comment]
I would go with a mock-based solution if you can. The provider state callbacks are there so you can put your provider in a valid state so it can generate a valid response. The actual data it uses is not as important.
