### ISSUE TITLE
How can we connect provider using proxy ? Is it possible in pact to connect provider endpoint using proxy credentials?

### ISSUE THREAD

**Issue by KANISHKART** [pact-foundation/pact-jvm#1146]

**Comment by uglyog** [comment]
Proxy details can be set with the following JVM system properties:

* http.proxyHost
* http.proxyPort
* https.proxyHost
* https.proxyPort
* http.nonProxyHosts

**Comment by sumit-ps** [comment]
Hi @uglyog , could you please provide some example how can we add proxy details to the provider endpoint. tried to add the using jvm but it did not worked

**Comment by todor-kolev** [comment]
> Hi @uglyog , could you please provide some example how can we add proxy details to the provider endpoint. tried to add the using JVM system properties but it did not worked
> System.setProperty("http.proxyHost","someproxy")
> System.setProperty("http. proxyPort","proxyport")

Doing the above worked for me so you might need to use `https.proxyHost` and `https.proxyPort` instead.
