### ISSUE TITLE
@PactBroker not reading Spring properties with JUnit 5

### ISSUE THREAD

**Issue by gustavotpd** [pact-foundation/pact-jvm#1178]
I'm using this dependency
```
    <!-- https://mvnrepository.com/artifact/au.com.dius/pact-jvm-provider-junit5 -->
    <dependency>
        <groupId>au.com.dius</groupId>
        <artifactId>pact-jvm-provider-junit5</artifactId>
        <version>4.0.10</version>
    </dependency>
```

My code:
```
@PactBroker(scheme = "https", host = "${pactbroker.host}", authentication = @PactBrokerAuth(token = "${pactbroker.auth.token}"))
@Provider("PriceService")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ExtendWith(SpringExtension.class)
@ActiveProfiles("test")

public class PriceServicePactTests {

@LocalServerPort
private final int port = 8082;
ObjectMapper objectMapper = new ObjectMapper();
@MockBean
private PriceDAO priceDao;

@BeforeEach
public void setupTest(final PactVerificationContext context) {
	System.setProperty("pact.provider.tag", "dev");
	System.setProperty("pact.provider.version", "1.0.0");
            context.setTarget(new HttpTestTarget("localhost", port, "/"));
}

@BeforeClass
public void enablePublishingPact() {
   	System.setProperty("pact.verifier.publishResults", "true");
}

@TestTemplate
@ExtendWith(PactVerificationInvocationContextProvider.class)
void pactVerificationTestTemplate(final PactVerificationContext context) {
	context.verifyInteraction();
}
```

Running the test this error occours: **java.lang.RuntimeException: Could not resolve property "pactbroker.host" in the system properties or environment variables and no default value is supplied**

any help would be appreciated.

Thanks in advance.

**Comment by gustavotpd** [comment]
Any help?

**Comment by mefellows** [comment]
(FYI I just reformatted your issues - please try to use code gates to help with readability)

**Comment by gustavotpd** [comment]
Hi @mefellows, Do you know if exists a fix to this issue? Thanks in advance.

**Comment by mefellows** [comment]
I don't know if it's a problem. If you can share a reproducable example that might help.

For reference, this project uses environment variables (resolved via the Spring interface) and that works just fine: https://github.com/pactflow/example-provider-springboot/

**Comment by gustavotpd** [comment]
This github you shared link seems to be broken. 404.

**Comment by mefellows** [comment]
Apologies, please try again now (it was set to private visibility)

**Comment by gustavotpd** [comment]
Good afternoon. I'm using maven dependency, added both listed in your build.gradle on my pom.xml:

`        <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-provider-junit5</artifactId>
            <version>4.0.10</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-provider-spring</artifactId>
            <version>4.0.10</version>
            <scope>test</scope>
        </dependency>`

`@ExtendWith(SpringExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@Provider("PriceService")
@PactBroker(scheme = "https", host = "${PACT_BROKER_HOST}",
		authentication = @PactBrokerAuth(token = "${PACT_BROKER_TOKEN}"))
@ActiveProfiles("test")`

and this is my application-test.yml

`# Pact.io configuration
pactbroker:
  host: ${PACT_BROKER_HOST:ab-inbev.pact.dius.com.au}
  auth:
    token: ${PACT_BROKER_TOKEN:ep_slrX3zdQF3SHD6D6wgA}`

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.322 s <<< FAILURE! - in com.abinbev.b2b.price.api.integrations.PriceServicePactTests
[ERROR] pactVerificationTestTemplate{PactVerificationContext}  Time elapsed: 0.321 s  <<< ERROR!
java.lang.RuntimeException: **Could not resolve property "PACT_BROKER_HOST" in the system properties or environment variables and no default value is supplied**

**Comment by mefellows** [comment]
_NOTE: I'm not sure if you meant to post your credentials. I've redacted the token as it seemed to be active. I would suggest rotating it as soon as you can_

**Comment by gustavotpd** [comment]
Thanks to advise.

**Comment by YOU54F** [comment]
The answer above is indeed the solution for this particular problem :)
