### ISSUE TITLE
adding authentication headers option to PactUrl

### ISSUE THREAD

**Issue by 03ayush** [pact-foundation/pact-jvm#1224]
actually i was trying to fetch pacts from a url via @PactUrl notation but the url that i am requesting needs an authorization header to authenticate but i was unable to find a way in Pacturl so as to include in the headers part..

**Comment by mefellows** [comment]
You can definitely authenticate. Does this not work for you https://docs.pact.io/implementation_guides/jvm/provider/junit#using-authentication-with-the-with-the-pact-broker?

**Comment by mefellows** [comment]
The authentication is for the Pact Broker, the URL is which source to use. I think you may also use a system property https://docs.pact.io/implementation_guides/jvm/provider/junit#more-java-system-properties

**Comment by uglyog** [comment]
4.1.9 released with the auth options
