### ISSUE TITLE
Gradle: Pact Public Task fails when using Semantic Release Plugin

### ISSUE THREAD

**Issue by sneufeind** [pact-foundation/pact-jvm#1228]
Hey guys,

i regnozied that there is a problem when your pact -gradle-plugin and the [de.gliderpilot.semantic-release](https://github.com/tschulte/gradle-semantic-release-plugin)-plugin are applied together.

**The Problem**
It leads to the following error:

> No signature of method: **au.com.dius.pact.core.pactbroker.PactBrokerClient.uploadPactFile()** is applicable for argument types: (File, **org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$DelayedVersion**...) values: [C:\Users
\projects\user-client\build\pacts\user-consumer-user-provider.json, ...]
  Possible solutions: uploadPactFile(java.io.File, java.lang.String), uploadPactFile(java.io.File, java.lang.String, java.util.List)

**Analysis**
It points out that the  method `uploadPactFile` of your `PactBrokerClient.kt` expects a version property from type String, but it could be any object (as [the gradle Project spec](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#getVersion--) says).

Look at here: https://github.com/DiUS/pact-jvm/blob/503856e9fbfc2120723475c86ccd286fb9bc9fa0/provider/gradle/src/main/groovy/au/com/dius/pact/provider/gradle/PactPublishTask.groovy#L60

**A Solution**
I would suggest to invoke the `toString()` before you put it into the upload method, like this:

Before:
`result = brokerClient.uploadPactFile(pactFile, version, pactPublish.tags)`

Fixed:
`result = brokerClient.uploadPactFile(pactFile, version.toString(), pactPublish.tags)`

Would it possible to fix that the next days?

Thank you in advance

**Comment by uglyog** [comment]
4.1.9 released with the fix

**Comment by sneufeind** [comment]
This issue should be closed.
