### ISSUE TITLE
Provider state params not serialized correctly in pact file

### ISSUE THREAD

**Issue by diana-zaharia** [pact-foundation/pact-jvm#1234]
Spotted issue in pact-jvm  v4.1.9, but I assume all versions since 4.1.0 (which dropped Gson library for json parsing) are affected.

When sending any custom object as provider state param, it gets written to pact file as `null`
E.g. specifying a provider state as:

```
given("my custom object exists", "id", UUID.randomUUID())
```
will get written to pact file as:
```
"providerStates": [
  {
    "name": "my custom object exists",
    "params": {
      "id": null
    }
  }
]
```

Any primitives or boxed primitives seem to be serialized fine.

**Comment by uglyog** [comment]
Version 4.1.10 has been released with this fix

**Comment by diana-zaharia** [comment]
Hey @uglyog tried version 4.1.10 but it seems serialization is still not working for immutable objects.
Do you think there's anything that can be done about that? :confused:
```
java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter cannot access a member of class java.util.UUID (in module java.base) with modifiers "private final"
kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter cannot access a member of class java.util.UUID (in module java.base) with modifiers "private final"
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:224)
	at au.com.dius.pact.core.support.Utils.objectToJsonMap(Utils.kt:85)
	at au.com.dius.pact.core.support.Utils.jsonSafeValue(Utils.kt:101)
	at au.com.dius.pact.core.model.ProviderState.toMap(ProviderState.kt:19)
```

**Comment by uglyog** [comment]
@diana-zaharia It needs to be a POJO. Just call `.toString()` on the UUID.
