### ISSUE TITLE
Dependencies of pact-jvm-server not resolved in gradle 6.6

### ISSUE THREAD

**Issue by leiferksn** [pact-foundation/pact-jvm#1239]
Hi,

I'm using pact-jvm-server and start it from gradle as javaexec, but I'm not getting dependencies/libs of pact-jvm-server resolved and added to my class path automatically, so I need to add them manually. Talked to @uglyog and he meant that I should raise an issue for that.

We are working with a multiple module project, so the build.gradle that takes care of the pact-jvm-server looks like

runtimeClasspath "au.com.dius.pact:pact-jvm-server:4.1.7"

```
dependencies {
    runtimeClasspath "au.com.dius.pact:pact-jvm-server:4.1.7"
    runtimeClasspath "au.com.dius:pact-jvm-core-model:4.0.10"
    runtimeClasspath "org.scala-lang:scala-library:2.12.0"
    runtimeClasspath "com.typesafe.scala-logging:scala-logging_2.12:3.7.2"
    runtimeClasspath "com.github.scopt:scopt_2.12:3.5.0"
    runtimeClasspath "ws.unfiltered:unfiltered-netty-server_2.12:0.9.1"
    runtimeClasspath "au.com.dius:pact-jvm-consumer:4.0.10"
}

jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest {
        attributes(
                "Class-Path": configurations.runtimeClasspath.collect { it.toURI().toString() }.join(' '),
                "Main-Class": "au.com.dius.pact.server.Server"
        )
    }
}

```

I've taken a look at the pact-jvm-server.pom and it doesn't contain any dependencies, just the one jar for the server. So maybe that's part of the problem.

Thank you for taking a look.

**Comment by uglyog** [comment]
4.1.11 has the dependencies in the published POM

**Comment by leiferksn** [comment]
thank you! it works.
