### ISSUE TITLE
Request Headers are not getting registered in Pact ContracT file 

### ISSUE THREAD

**Issue by Dattasaisukumar** [pact-foundation/pact-jvm#1246]
Hi Team 
                     I am trying to generate one pact file with headers in Request but while generating the Pact Contract file it is not showing the details of the REQUEST HEADERS in Pact file ,Please find the attached Code Snippets and Pact File snippets 

![image](https://user-images.githubusercontent.com/44521198/99043704-9b9c8800-25b4-11eb-8326-949907bc0c35.png)

![image](https://user-images.githubusercontent.com/44521198/99043737-aeaf5800-25b4-11eb-89ce-c05dee980955.png)

**Comment by ashishkujoy** [comment]
@Dattasaisukumar I think that because you have not added any header in `headersreq` you have added in `headers` only.

**Comment by Dattasaisukumar** [comment]
> @Dattasaisukumar I think that because you have not added any header in `headersreq` you have added in `headers` only.

Hi Ashish
                      you are right , but after adding the headers to Request it is failing with assertion error as shown below , but I am not validating any of Headers in my code can you please help me on this 

![image](https://user-images.githubusercontent.com/44521198/99046132-54b09180-25b8-11eb-8ce5-5116773c016b.png)

![image](https://user-images.githubusercontent.com/44521198/99046213-727df680-25b8-11eb-8c2b-3e9cca22c2b8.png)

**Comment by mefellows** [comment]
Are you sending the header `test` in your request? That error indicates your http client is not sending that header and therefore is disallowing the pact to be serialised because your code isn't doing what you said it should.

I'm not surprised, because in your first example you were looking at a different header, so I'm guessing you just added to see if it appears in your pact file without understanding the consequence.

**Comment by Dattasaisukumar** [comment]
> Are you sending the header `test` in your request? That error indicates your http client is not sending that header and therefore is disallowing the pact to be serialised because your code isn't doing what you said it should.
> 
> I'm not surprised, because in your first example you were looking at a different header, so I'm guessing you just added to see if it appears in your pact file without understanding the consequence.

Hi  Matt 
                Acutally our endpoint need a Language Header and when I am trying to pass it is showing the same error . I just want to know whether it is showing same error if we add any Random key also . I have did the same Request from Postman it is working  . Can you please guide me If I am doing anything wrong with Passing of Request Headers.
![image](https://user-images.githubusercontent.com/44521198/99065114-ea561c00-25cc-11eb-98f6-eea1148c47f2.png)
![image](https://user-images.githubusercontent.com/44521198/99065208-0bb70800-25cd-11eb-8805-0955bd067268.png)
![image](https://user-images.githubusercontent.com/44521198/99065278-27221300-25cd-11eb-9caf-badc1639e1f4.png)

**Comment by mefellows** [comment]
In your postman test you actually send the `language` header. In your pact test you don't send any headers at all. 

Pact is telling you it's expecting the header that you told it to expect. Update your `runTest` method to actually call the endpoint in the way you've told it you would in `pactTest`

**Comment by Dattasaisukumar** [comment]
> In your postman test you actually send the `language` header. In your pact test you don't send any headers at all.
> 
> Pact is telling you it's expecting the header that you told it to expect. Update your `runTest` method to actually call the endpoint in the way you've told it you would in `pactTest`

Thanks a lot  Maat for guiding me on my issue can you please help me on how to do the RunTest Update with headers in it for this if possible . I know I am asking more but Please help me on this

**Comment by uglyog** [comment]
To verify the provider, you need to have the provider running on the required port (8083). The connection refused error is because it is not running.
