### ISSUE TITLE
Consumer tests on provider side for underlying calls

### ISSUE THREAD

**Issue by artemptushkin** [pact-foundation/pact-jvm#1248]
I wonder about capabilities and potential feature request on writing consumer tests during executing provider verification, i.e. consumer tests on the provider side.

As it is written in [the pact-jvm documentation](https://docs.pact.io/implementation_guides/jvm/provider#provider-state) provider might have consumers itself and usually requires mocking underlying services.

It seems quite rational to use the same framework - pact for mocking it.
But this example in the documentation doesn't go along with the general approach with annotations or Gradle setup. Basically, we have to explicitly set up everything.

I consider only the latest libraries after `4.0.10`

### Junit5
As for now, for instance, for `junit5spring` library, we are capable include **one** consumer mock with Pact. It is possible because of having `@TestTemplate` method, we can put `@PactTestFor` and extend it with `PactConsumerTestExt.class`
```java
@Provider("plan-api")
@PactBroker(
		host = "my.pact.dius.com.au", scheme = "https",
		authentication = @PactBrokerAuth(token = "a-token")
)
@ExtendWith(value = {SpringExtension.class, PactConsumerTestExt.class})
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
class PlanPactServiceApplicationTests {

	@TestTemplate
	@PactTestFor(port = "8092", providerName = "auth-api")
	@ExtendWith(PactVerificationSpringProvider.class)
	void pactVerificationTestTemplate(PactVerificationContext context) {
		context.setTarget(new HttpTestTarget("localhost", 8080));
		context.verifyInteraction();
	}

	@Pact(provider = "auth-api", consumer = "plan-api")
	public RequestResponsePact createPact(PactDslWithProvider pactDsl) {
		return pactDsl
				.given("authorize-plan-calls")
				.uponReceiving("GET REQUEST")
				.path("/auth")
				.method("GET")
				.willRespondWith()
				.status(200)
				.toPact();
	}

	@State("get plans")
	public void test() { }
}
```

But it is viable only for a **single** mock, as no way to put additional annotation.
It would be really helpful to have aggregation annotation:
```java
@PactTestsFor(
    @PactTestsFor(port = "8092", providerName = "auth-api"),
    @PactTestsFor(port = "8093", providerName = "product-api")
)
```

### Junit4

As for Junit4 we have any options at all, as on the provider side we have only `@State` method.
It would be convenient to have an annotation that we can put on the class, or maybe provide an additional setup method for this.

Please let me know if I'm wrong and your vision on it.

**Comment by uglyog** [comment]
The big problem with this is it introduces coupling between all the builds for all the services. I did this exact thing (but not doing consumers tests during the provider verification but using the pact files from the consumer tests to setup mock servers). All the consumer tests ran first, then the provider verification ran using the pact files from the consumer tests.

Here is a diagram of the solution. The gray boxes are the pact tests.

![image](https://user-images.githubusercontent.com/863666/100490979-519ad100-3174-11eb-96d8-f82f25900ebd.png)

One day a new person joined the team. And to get started, he thought we would make the test data used in the consumer app more relevant (use proper formed names and addresses etc.). This cause a cascading series of failing CI builds which took him a week to get all working again. Then two weeks later another team came to ask him why he has broken their build (that service has not been changed for a while, and when it was changed it's build started failing). 

This guy has a very poor opinion of Pact.

**Comment by artemptushkin** [comment]
@uglyog thanks. In several days after I published the question that thought come-up to me - to separately start the mock server with pacts and prevent that chain of failures.

One of the options to use `spring-cloud-contract-stub-runner` to fetch pacts from the broker, there is a convenient one line annotation. Or, of course, to start with consumer tests in `this` service and then use these pacts for provider run.

What did you use to start the mock server at the second step? I wonder that it should be with the Broker, i.e. `@PactFolder` for consumer pacts and `@PactBroker` for provider part

**Comment by uglyog** [comment]
@artemptushkin I just have gradle tasks in my build that did it before the verification ran.

**Comment by artemptushkin** [comment]
I see, thanks for the first answer. It is clear and I see your point why you don't suppose to couple these things 👍
