### ISSUE TITLE
consumerVersionSelectors does not select a pact file having the specified tag

### ISSUE THREAD

**Issue by anddreiu** [pact-foundation/pact-jvm#1249]
- pact jvm 4.1.11
- Pact Broker 2.68.1 
- using JUnit to run the Provider tests

I am trying to use specific tags to retrieve the correct pact file when running the Provider tests for a consumer. So I've applied the below consumerVersionSelectors:

~~~
@PactBroker(consumerVersionSelectors = { @VersionSelector(tag = "prod", consumer = "consumerName") }
~~~
Unfortunately, the pact file retrieved does not have 'prod' tag, it has only 'master' tag: 
~~~
consumerName version: 0.41.0 (master)
~~~
In the logs I can see that the correct tag and consumer are used, but the version retrieved is not the expected one.
~~~
2020-11-11 06:39:28.637 DEBUG [PactBrokerLoader.kt] Loading pacts from pact broker for provider providerName and consumer version selectors [ConsumerVersionSelector(tag=prod, latest=true, consumer=consumerName, fallbackTag=null)]
Verifying a pact between consumerName and providerName
  Notices:
    1) The pact at https://pactbroker/pacts/provider/providerName/consumer/consumerName/pact-version/64fr34ca943bbg242432we3f9hwe43c34r25wef2 is being verified because it matches the following configured selection criterion: latest pact for a version of consumerName tagged 'prod'
~~~

If I use 'master' tag, then the correct version is selected (the latest one that I have in Pact Broker). But for any other tag, it does not take the correct Pact version, it always retrieve that 0.41.0 version which has master tag and I don't understand why it happens this.

Thank you

**Comment by uglyog** [comment]
If you check the debug logs (above the snippet you provided), you should see the request made to the Pact broker. If it has the correct values then this is an issue with the Pact broker. @bethesque might have some insight into this.

**Comment by bethesque** [comment]
Can I see the debug logs please @anddreiu?

Also, can you check something for me in the API Browser (HAL browser). Paste the pact URL that you got in the test output into the location bar (under the title "Explorer") and click "go".  In the "Links" section, find the `pb:consumer-version` relation, and then click the `GET` button. Scroll down to the "Embedded Resources" section, and let me know what tags are listed.

**Comment by anddreiu** [comment]
Below you can find all the logs that I am able to see. Is there a way to enable more logging which could help you?

~~~
2020-11-30 15:55:41.638 DEBUG main [au.com.dius.pact.provider.junit.PactRunner.initialize PactRunner.kt:73] Found annotation @au.com.dius.pact.provider.junitsupport.Provider(value=providerName)
2020-11-30 15:55:41.640 DEBUG main [au.com.dius.pact.provider.junit.PactRunner.initialize PactRunner.kt:78] Found annotation @au.com.dius.pact.provider.junitsupport.Consumer(value=consumerName)
2020-11-30 15:55:41.970 DEBUG main [au.com.dius.pact.provider.ProviderUtils.instantiatePactLoader ProviderUtils.kt:145] Pact source does not have a constructor with one argument of type Class
2020-11-30 15:55:41.980 DEBUG main [au.com.dius.pact.provider.junitsupport.loader.PactBrokerLoader.loadPactsForProvider PactBrokerLoader.kt:193] Loading pacts from pact broker for provider providerName and consumer version selectors [ConsumerVersionSelector(tag=prod, latest=true, consumer=consumerName, fallbackTag=)]
2020-11-30 15:55:41.983 DEBUG main [au.com.dius.pact.provider.junitsupport.loader.PactBrokerLoader.newPactBrokerClient PactBrokerLoader.kt:286] Authentication: Basic
2020-11-30 15:55:41.991 DEBUG main [au.com.dius.pact.core.pactbroker.HalClient.fetch HalClient.kt:241] Fetching: /
2020-11-30 15:55:43.428 DEBUG main [au.com.dius.pact.core.pactbroker.HalClient.fetch HalClient.kt:241] Fetching: https://pactbroker/pacts/provider/providerName/consumer/consumerName/pact-version/64fr34ca943bbg242432we3f9hwe43c34r25wef2
~~~

Also, I've checked in the API Browser and there is a single tag:
~~~
tags[0]: master
~~~

So that pact version does not have prod tag, but it's selected to be used.

**Comment by bethesque** [comment]
There is a log line in the broker that will tell you what request it received. 

https://github.com/pact-foundation/pact_broker/blob/2c948fb5e3a17c03df86078925f9971e95a674d4/lib/pact_broker/api/resources/provider_pacts_for_verification.rb#L88

Can you please find that and paste it here.

The next step is to get you to make a copy of your database, run this [redaction script](https://github.com/pact-foundation/pact_broker/blob/master/script/prod/redact-data.sql) on it, and then upload it here for me so I can put it into an instance locally where I can debug it.

**Comment by uglyog** [comment]
I'm not seeing the HTTP request in the logs. Are you using Spring/Springboot, or just normal JUnit tests?

**Comment by uglyog** [comment]
If I run one of my tests with debug, the see the following logs:
```
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /pacts/provider/multicookie_provider/for-verification HTTP/1.1[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/json; charset=UTF-8[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept: application/hal+json, application/json[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 59[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: test.pact.dius.com.au[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.13 (Java/1.8.0_275)[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
09:15:08.288 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "{"consumerVersionSelectors":[{"latest":true,"tag":"test"}]}"
```

**Comment by bethesque** [comment]
Is the pact that's being returned also the latest overall pact?

**Comment by anddreiu** [comment]
I've just tried something. I've added some new Pact files for a test consumer, using direct curl requests. I added 3 versions and tagged two of them using the below commands.

~~~
curl -v --user blabla -XPUT \-H "Content-Type: application/json" \
-d@testandrei-providerName.json \
https://pactbroker/pacts/provider/providerName/consumer/testandrei/version/0.0.1

curl -v --user blabla -X PUT -H "Content-Type: application/json" https://pactbroker/pacticipants/testandrei/versions/0.0.1/tags/testandrei
~~~

So now I have:


~~~
|       Consumer       | Consumer Version | Tag      |
|----------------------|------------------|----------|
| testandrei           | 0.0.3            |          |
| testandrei           | 0.0.2            |master    |
| testandrei           | 0.0.1            |testandrei|

Then, when I run the test, even if the specified tag is testandrei or master or nothing, the Pact retrieved is the one having version 0.0.3.

Thanks for looking into this issue and trying to help me.

**Comment by uglyog** [comment]
If the pacts all have the same content, then the broker treats them as the same thing. So it might be showing 0.0.3 because that is the latest publication. Try with changing the actual pact file contents.

**Comment by bethesque** [comment]
Ah! Ron has identified the issue. The URL returned by the 'pacts for verification' response returns a "permalink" url to the pact content (you'll notice it has `/pact-version/abc` not `/version/1234` in the URL). The consumer version shown in the relation is, however, the latest consumer version that has that same content. 

I have recently made some changes that will allow me to select the correct consumer version however. Let me get back to you.

**Comment by bethesque** [comment]
If you update to 2.72.0 of the Pact Broker, and follow the same instructions I gave you before, you should see the tags you expect.

**Comment by anddreiu** [comment]
Yep, it looks like you are right. If the content of the Pact files is different, then the correct tagged Pact is retrieved. I am waiting now for my team to upgrade the Pact Broker version and then I will re-try the scenario.

Thanks a lot Beth and Ron for your help! Much appreciated!

**Comment by anddreiu** [comment]
Hi @bethesque. My team has upgraded the Pact Broker to version 2.72.0 and I can see the same behavior. If the Pact content is the same, the latest one is retrieved, even if it does not have the specified tag.

I've looked in the API Browser and the selected Pact file does not have the specified tag.

**Comment by bethesque** [comment]
Can you please provide the URLs that are being used? That is, the URL that is being returned to verify, and then the consumer version that is shown in the pact resource when you look at it in the HAL browser.

Just to clarify, the right content is being verified, and it is working as originally intended. The pact verification belongs only to the pact content, and it does not matter which consumer version(s) it was selected for. That being said, it would be nice from a usability perspective to have the consumer version/tags match what would be expected when you reverse the URLs.

**Comment by bethesque** [comment]
Ok, I've worked out what it is. The metadata isn't being set on the end of the URL to record which consumer version the pact content is from. The reason is that the same pact content may be selected by multiple consumer version selectors. eg. A standard set of selectors would be `{"latest": true, "tag": "main"}, {"latest": true, "tag": "prod"}`. If the latest version from the main branch is in production, then the same underlying pact content will have been selected by both selectors. To speed up the verification process, the selected collection of pact contents are deduplicated, because as I said earlier, the verification results are linked to the pact content, not to the pact publication (which is the database object that gets created when you publish a pact, and stores the reference to the content and the consumer version).

It would be more accurate for the pact content URL that gets returned to contain links to ALL the consumer versions with which it was associated, but that could be a very long list, so for simplicity's sake, and to make the clients not care whether they got a link to the "pact publication" or the "pact content" it just has the reference to the latest consumer version.
