### ISSUE TITLE
Maven surefire report does not contain display name of test cases

### ISSUE THREAD

**Issue by tinexw** [pact-foundation/pact-jvm#1255]
The Maven surefire report does not contain the human readable test case names (dynamically generated by Junit5's TestTemplate method) Instead, it just contains the default notation with the `[0]`, `[1]`... suffix. 
This makes it hard in a CI/CD server to see at first glance which interaction failed.

IntelliJ Runner:
<img width="583" alt="intellij-test-runner" src="https://user-images.githubusercontent.com/7386945/100221414-f15c2300-2f18-11eb-89c7-0e41a3e8398a.png">

Maven Surefire Report:
<img width="801" alt="maven-report" src="https://user-images.githubusercontent.com/7386945/100222454-6419ce00-2f1a-11eb-9141-7c767b37dac5.png">

The same issue exists for gradle. However, this might be caused by gradle itself because the same issue exists when using the gradle runner in IntelliJ, s https://github.com/gradle/gradle/issues/5975

IntelliJ Gradle Runner:
<img width="577" alt="intellij-gradle-runner" src="https://user-images.githubusercontent.com/7386945/100221404-eef9c900-2f18-11eb-93a5-3304cb982da3.png">

Gradle Report:
<img width="861" alt="gradle-report" src="https://user-images.githubusercontent.com/7386945/100222311-32086c00-2f1a-11eb-82b4-f9a7ac14ca42.png">

**Comment by tinexw** [comment]
Hmm... maybe it's a surefire issue... https://issues.apache.org/jira/browse/SUREFIRE-1546

**Comment by uglyog** [comment]
Is this for a consumer test?

**Comment by uglyog** [comment]
I'm getting the correct display names when verifying the provider with 4.1.11.

```
$ mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T04:33:14+10:00)
Maven home: /home/ronald/.sdkman/candidates/maven/current
Java version: 11.0.8, vendor: N/A, runtime: /home/ronald/.sdkman/candidates/java/11.0.8-open
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-29-generic", arch: "amd64", family: "unix"
```

In the console:
```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.933 s <<< FAILURE! - in com.github.uglyog.AppPactTest
[ERROR] Pact between Foo Web Client (1.2.3/AB) and Activity Service - Upon a request for activities(com.github.uglyog.AppPactTest)  Time elapsed: 0.266 s  <<< ERROR!
au.com.dius.pact.provider.junitsupport.MissingStateChangeMethod: MissingStateChangeMethod: Did not find a test class method annotated with @State("many activities exist")

[ERROR] Pact between Foo Web Client 2 (1.2.3/AB) and Activity Service - Upon a request for activities(com.github.uglyog.AppPactTest)  Time elapsed: 0.002 s  <<< ERROR!
au.com.dius.pact.provider.junitsupport.MissingStateChangeMethod: MissingStateChangeMethod: Did not find a test class method annotated with @State("many activities exist")

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AppPactTest.Pact between Foo Web Client (1.2.3/AB) and Activity Service - Upon a request for activities » MissingStateChangeMethod
[ERROR]   AppPactTest.Pact between Foo Web Client 2 (1.2.3/AB) and Activity Service - Upon a request for activities » MissingStateChangeMethod
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

In the surefire report:
```
  <testcase name="Pact between Foo Web Client 2 (1.2.3/AB) and Activity Service - Upon a request for activities" classname="com.github.uglyog.AppPactTest" time="0.002">
    <error message="MissingStateChangeMethod: Did not find a test class method annotated with @State(&quot;many activities exist&quot;)" type="au.com.dius.pact.provider.junitsupport.MissingStateChangeMethod">au.com.dius.pact.provider.junitsupport.MissingStateChangeMethod: MissingStateChangeMethod: Did not find a test class method annotated with @State("many activities exist")
</error>
  </testcase>
```

**Comment by uglyog** [comment]
That's using 
```
       <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
```

See https://github.com/uglyog/pact-maven-springboot-test

**Comment by tinexw** [comment]
The issue appears with Junit5 - I updated my original description accordingly to make it clearer.
I also added a small example here: https://github.com/tinexw/cdc-demo/tree/maven (in the maven branch)

**Comment by tinexw** [comment]
It is related to surefire. After using [this configuration](https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#Surefire_Extensions_and_Reports_Configuration_for_.40DisplayName) as mentioned in [the surefire issue about display name support](https://issues.apache.org/jira/browse/SUREFIRE-1546?focusedCommentId=16976182&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16976182) it works!

<img width="882" alt="Screen Shot 2020-11-28 at 10 25 55" src="https://user-images.githubusercontent.com/7386945/100498666-1b555580-3164-11eb-9c6a-7893520c57d2.png">
