### ISSUE TITLE
Do not fail verification test when provider state doesn't exist.

### ISSUE THREAD

**Issue by danilchican** [pact-foundation/pact-jvm#1260]
Is there any way to do not fire error when state on a provider side is not defined?

There are cases when Consumer defines state, e.g. "products exist" but Provider shouldn't do something special inside provider state method. But if method with `@State` is not defined it fails.

How to do not fail without having `@State`?

**Comment by joklek** [comment]
A workaround I see is to use the same `@State` method for a few states.

This does not avoid having to have the states in the producer, but you don't have to create a separate method ` @State("default", "products exist")`. OR just use the default state

**Comment by uglyog** [comment]
I've added an `@IgnoreMissingStateChange` annotation which you can add to your test class

**Comment by danilchican** [comment]
@uglyog great! Which version has this improvement?

**Comment by anto-ac** [comment]
> @uglyog great! Which version has this improvement?

I don’t think it has been released yet.

**Comment by uglyog** [comment]
Just been released :-D (4.1.12)

**Comment by danilchican** [comment]
@uglyog , great! Thanks for quick improvement.
