### ISSUE TITLE
Method MessagePactBuilder#withContent does not add the generators to the message from the body (DslPart)

### ISSUE THREAD

**Issue by theovanessen** [pact-foundation/pact-jvm#1278]
I made a consumer contract test for amqp messaging and used the dateExprssion and the dateTimeExpression in the body of the message.
It noticed that there were no generator configurations in the generated contract. As a result of which the provider cannot use the generators.

When I look at the function `MessagePactBuilder#withContent(body: DslPart)` I don't see that the generators from the body (DslPart) are copied into the message, like this is done in the `RequestResponseInteraction#requestToMap` and the `RequestResponseInteraction#responseToMap` methods for the HTTP consumer request and response data.
The method `MessagePactBuilder#withMetadata(metadata: Map<String, Any>)` does add the generators for the metadata section.

**Comment by uglyog** [comment]
4.1.13 released

**Comment by theovanessen** [comment]
The generators are present.
Thanks for the quick fix.
