### ISSUE TITLE
Scope of junit5Spring library

### ISSUE THREAD

**Issue by artemptushkin** [pact-foundation/pact-jvm#1280]
Currently, the library `au.com.dius.pact.provider:junit5spring` publishes with **runtime** scopes for all the transitive dependencies: https://repo1.maven.org/maven2/au/com/dius/pact/provider/junit5spring/4.1.12/junit5spring-4.1.12.pom

Gradle doesn't fetch it as it transitive and it forces library-consumers to explicitly declare `au.com.dius.pact.provider:provider:junit5`.

Maven does. That's why maybe this is not changed yet.

This is the only library with these scopes, for instance [provider:junit5](https://repo1.maven.org/maven2/au/com/dius/pact/provider/junit5/4.1.12/junit5-4.1.12.pom) is okay and transitives have **compile** scope.

Is there a reason for it?
Please align it, I hope to `compile` side. Or let's update documentation

**Comment by uglyog** [comment]
4.1.13 released

**Comment by artemptushkin** [comment]
Thanks! Scopes are okay now
