### ISSUE TITLE
inconsistent system property name for pact broker

### ISSUE THREAD

**Issue by jogaco** [pact-foundation/pact-jvm#1283]
Env variables for pact cli docker image https://hub.docker.com/r/pactfoundation/pact-cli are like these:

- PACT_BROKER_BASE_URL
- PACT_BROKER_USERNAME
- PACT_BROKER_PASSWORD

Whereas the env variables for PactBroker annotation are like these:

- PACTBROKER_HOST
- PACTBROKER_PORT
- ...

Can we have a consistent set of env vars accross all moving parts?

**Comment by uglyog** [comment]
The PactBroker annotation uses JVM system properties like `pactbroker.host`. Where did you get the PACTBROKER_HOST environment variable format from?

**Comment by jogaco** [comment]
You are right. My bad.
