### ISSUE TITLE
Is `"min": 0` needed in matchers generated by Consumer PactDSL? (GroovyDSL doesn't use it)

### ISSUE THREAD

**Issue by tlinkowski** [pact-foundation/pact-jvm#1289]
## Current status

Right now:
- PactDSL generates an extra `"min": 0` entry on calls to `each*Like` methods ([source](https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonBody.java#L796))
- while GroovyDSL does no such thing ([source](https://github.com/pact-foundation/pact-jvm/blob/master/consumer/groovy/src/main/kotlin/au/com/dius/pact/consumer/groovy/Matchers.kt#L157))

Example:
- Pact DSL: `new PactDslJsonBody().eachLike("values", stringType("example"))` generates
  ```json
   "$.values": {
     "matchers": [{"match": "type", "min": 0}],
     "combine": "AND"
   }
   "$.values[*]": {
     "matchers": [{"match": "type"}],
     "combine": "AND"
   }
   ```
- Groovy DSL: `{ values eachLike(string('example')) }` generates
  ```json
   "$.values": {
     "matchers": [{"match": "type"}],
     "combine": "AND"
   }
   "$.values[*]": {
     "matchers": [{"match": "type"}],
     "combine": "AND"
   }
   ```

## Consequences

Apart from the obvious (and unintuitive) discrepancy between PactDSL and GroovyDSL, the main drawback is that Pact Broker does **not** render the content of such `eachLike`s when it renders them.

That is, instead of:
```json
"values": [
  "example"
]
```
Pact broker renders:
```json
"values": [
]
```

which makes the preview in Pact Broker very much useless 😞 

## Question

Can the following occurrences of `matchMin(0)` below be replaced with `TypeMatcher.INSTANCE`?
1. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonBody.java#L740
2. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonBody.java#L769
3. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonBody.java#L796
4. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonBody.java#L1082
5. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonBody.java#L1156
6. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonArray.java#L129
7. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonArray.java#L148
8. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonArray.java#L736
9. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonArray.java#L754
10. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonArray.java#L955
11. https://github.com/pact-foundation/pact-jvm/blob/57a8541e08cbecb2c324010b8a8423fd9d2aeb1b/consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonArray.java#L1034

Would you accept a PR with such a change?

**Comment by uglyog** [comment]
PRs are always welcome, but in this case it was a small change so I just did it.

**Comment by uglyog** [comment]
4.1.17 has been released
