### ISSUE TITLE
Pact-jvm fails to build on master

### ISSUE THREAD

**Issue by ewebprojects** [pact-foundation/pact-jvm#1291]
Attempt to build the project from the sources fail on master (checked out earlier today)

with java 8:
./gradlew clean build leads to
'Execution failed for task ':provider:lein:compileClojure' > Metaspace

with java 11
./gradlew clean build leads to
Execution failed for task ':provider:dokkaJavadoc'
> com/sun/tools/doclets/formats/html/HtmlDoclet

Can you advise please what is the required configuration needed to build the project ? what version of java+gradle to use, what are the memory settings..etc.  thanks.

**Comment by uglyog** [comment]
Master branch needs to be built with JDK 8. I don't have an issue building it, but I have a computer with a lot of RAM. Hoe much RAM does your machine have?

You can change the Metaspace settings (see Class Metadata https://docs.oracle.com/javase/10/gctuning/other-considerations.htm#JSGCT-GUID-BFB89453-60C0-42AC-81CA-87D59B0ACE2E)

**Comment by eleco** [comment]
thanks for the quick reply, it seems the dokka task is no longer erroring with java 8.

Although now there is an error on the next task triggered with ./gradlew build:

> Task :provider:signMavenPublicationPublication FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':provider:signMavenPublicationPublication'.
> Cannot perform signing task ':provider:signMavenPublicationPublication' because it has no configured signatory

I see the same error when running ./gradlew publishToMavenLocal  (as indicated in the contributing guide https://github.com/pact-foundation/pact-jvm/blob/master/CONTRIBUTING.md)

Any idea ? I just want to install the jars in my local maven repo.

**Comment by uglyog** [comment]
CONTRIBUTING.md hasn't been updated in a long time, and is out of date.

To publish to your Maven local repo, you need to have created a GPG key and then set in `~/.gradle/gradle.properties`:

```
signing.keyId                 # this is your GPG key ID
signing.password              # GPG key password
signing.secretKeyRingFile     # Path to the GPG secret key file
```

**Comment by kflorence** [comment]
@ewebprojects I think we should leave this open until the documentation is updated. Also it would be nice if signing weren't required to publish to local maven repository.

**Comment by kflorence** [comment]
FYI this is a good resource to link to for GPG https://gist.github.com/phit/bd3c6d156a2fa5f3b1bc15fa94b3256c

**Comment by kflorence** [comment]
https://docs.gradle.org/current/userguide/signing_plugin.html#sec:conditional_signing

**Comment by kflorence** [comment]
I had to set `org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8` in my `~/.gradle/gradle.properties` to fix metaspace problems with JDK 11
