### ISSUE TITLE
handling of body responses with content-type application/x-thrift

### ISSUE THREAD

**Issue by ewebprojects** [pact-foundation/pact-jvm#1298]
hello - is it possible to have body responses with content-type 'application/x-thrift' handled in the same way as body responses with content-type 'application/x-thrift+json' ? 

For legacy/corporate reasons we are unable to modify the content type produced by our application, so we are stuck with 'application/x-thrift' which to the best of my understanding means body responses will be compared using string equality, and matchers wont be taken into account.

The alternative would be to fork the pact-jvm code and make that change in the forked pact-jvm code base, but maybe there's another easier way.

thanks

**Comment by uglyog** [comment]
You could fork the pact-jvm code and make that change, and then submit a PR for the fix :-D

**Comment by keeping-it-up** [comment]
> You could fork the pact-jvm code and make that change, and then submit a PR for the fix :-D

Hi uglyog, PR created for this issue: https://github.com/pact-foundation/pact-jvm/pull/1304
Can you please have a look?
Thanks.

**Comment by uglyog** [comment]
4.1.17 has been released
