### ISSUE TITLE
Possibility to populate pactbroker.host property together with scheme

### ISSUE THREAD

**Issue by danilchican** [pact-foundation/pact-jvm#1300]
Hi there!
In our project we would like to do not send any additional property for scheme of pact broker (http/https). Instead of that it would be nice to have possibility to populate **pactboroker.host** property together with host. 
Currently if I pass scheme into host it fails due to host is invalid. 

Can anyone do the improvement of **@PactBroker** annotation to have this enhancement?

Actual result: _pactbroker.host=https://my-pact-broker.url_ fails because of having **https** scheme in host name. for _pactbroker.host=my-pact-broker.url_ doesn't fail. 
Expected result: do not fail when I pass  _pactbroker.host=https://my-pact-broker.url_ and override default pactbroker.scheme with the pasted one into host name.

Thanks in advance!

**Comment by uglyog** [comment]
This should have been done years ago. I've deprecated the host, port and scheme attributes in favour of just providing a URL, which is what everyone would only need

**Comment by danilchican** [comment]
@uglyog , yes. thanks!

**Comment by uglyog** [comment]
4.1.18 released

**Comment by danilchican** [comment]
Issue can be closed, I think
