### ISSUE TITLE
pact broker using base path 

### ISSUE THREAD

**Issue by gjemp** [pact-foundation/pact-jvm#1306]
Hi,
we have a case , where the pact broker has base path defined . All responses contain links with the base path.
Now consumer and provider  are using pactbroker directly to get and publish pacts . Due that the url that points to pact broker has also the basepath in it like "https://my.home/base/path/"
Now what happens is that provider POST will fail cause it has link like that:
https://my.home/base/path/base/path/...
I suspect that it will get the second basepath from the pact broker and merge them to one link.  
On the client side we should havbe a flag or a parameter with what the client can trust only the pact broker links  when it is reusing them...

**Comment by gjemp** [comment]
ok the case was that I defined only the base path not the base url and in that case it was adding the base path to the url.

**Comment by uglyog** [comment]
Did this solve the issue for you?

**Comment by gjemp** [comment]
yes it did
