### ISSUE TITLE
For XML tests, no functionality to test text node using matchers

### ISSUE THREAD

**Issue by lovikasaxena** [pact-foundation/pact-jvm#1311]
Example having text within InnerNode: 
### <RootNode>
	<InnerNode>Some text</InnerNode>
</RootNode>

PactXmlBuilder and XmlNode does not provide functionality to add TextNodes. I tried creating my own but it only works for exact match of text and not using matchers.

Using lib: au.com.dius:pact-jvm-consumer-junit5:4.0.10

**Comment by lovikasaxena** [comment]
Could implement test for XML using lib: "au.com.dius.pact.consumer:junit5:4.2.0"

**Comment by Avkashhirpara** [comment]
Hello, @lovikasaxena  

I am trying the same thing, Is it possible for you to share the whole example. 

Thanks in advance.
