### ISSUE TITLE
Possibility to specify Routing Key for messages

### ISSUE THREAD

**Issue by EvgheniiShipilov** [pact-foundation/pact-jvm#1312]
Is there a possibility to specify a routing key(ex. for RabbitMQ)? 

Having the destination itself is not sufficient as we would need both exchange and routing key separately. According to the comment [here](https://github.com/pact-foundation/pact-specification/issues/30#issuecomment-782473884) it's a language thing. However I couldn't find any documentation for it.

**Comment by uglyog** [comment]
When comparing messages, you can match both the message payload and a key-value map of metadata. You need to put the routing key in that. 

Example test in Java: https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit/src/test/java/au/com/dius/pact/consumer/junit/v3/ExampleMessageWithMetadataConsumerTest.java

On the provider side, your provider function that returns the message needs to also return the metadata using either `MessageAndMetadata` or one of `org.apache.commons.lang3.tuple.Pair` or a Kotlin `Pair`.
