### ISSUE TITLE
Pact junit5 library not verifying the request object

### ISSUE THREAD

**Issue by rahuldeshmukh81** [pact-foundation/pact-jvm#1320]
I have implemented consumer and produce where consumer consume post request.

However,
In consumer side request object verified as mentioned in the contract but if I  change something lets say if I rename any field in provider request and if I run provider test then it wont fail.

It should fail as it is not as mentioned in the contract?

Please answer below question:

1 Do we need to mock database response or how we can deal with?
2 How we can verify request object in provider end in case of post request?
3 if we mock the db call in provider side and if any thing change in real service then test wont fail as we mock the data in provider

**Comment by uglyog** [comment]
Could you kindly clarify a few things for our understanding:

You have a consumer that is making a POST request. You mention renaming fields. Is this in the body of the POST request (i.e. what the consumer is sending), or in the response from the provider?

How are you renaming the fields?

Answers to your questions:

1. You can either mock the database or use provider states. See https://docs.pact.io/getting_started/provider_states/ and https://docs.pact.io/provider/using_provider_states_effectively/ and https://docs.pact.io/implementation_guides/jvm/provider/junit#provider-state-callback-methods

2. A POST request is no different from any other type of request. It has a body in the request and in the response. When the provider is verified, a POST request is made to it with the request body from the pact file, and then the response from the provider is checked against the response from the pact file.

3. True, that is the downside of mocking out behaviour in computer systems.

**Comment by rahuldeshmukh81** [comment]
Consumer is sending request body to provider which is mentioned in the pact file. 
Eg ,
Consumer is  sending name and age and in provider if we rename name field to firstName then provider is not failing.
I understand post request made by body which mentioned in the pact file but if it is not matched with the request body of provider it should fail but its not failing. If I remain as firstName then value will be ser as null.
If I change in response from provider end then it would fail which is correct but ir should work the same for request as well.
Did I missed something or it is the default behavior that it won't validated request body?

**Comment by uglyog** [comment]
> Consumer is sending name and age and in provider if we rename name field to firstName then provider is not failing

If the provider is not failing and still sending the expected response, that is not an issue with the Pact framework. It's an issue with your provider. If it does not receive the values it is expecting, it should return an error response.

**Comment by rahuldeshmukh81** [comment]
Provider is sending expected response because I am mocking the response in state callback.
Inside api we may huge database calls in real time and as per my understanding it won't work with real database call thats why I mock the response.
But concern here is why request object is not validating .

**Comment by uglyog** [comment]
> But concern here is why request object is not validating 
The request is validated during the consumer test, not the provider verification test.  Please read https://docs.pact.io/getting_started/how_pact_works/

> 2 How we can share the pact file with providers without docker image. What are the other option do we have?
Generally a Pact Broker is used to share Pact files.
