### ISSUE TITLE
Provider not matching request body

### ISSUE THREAD

**Issue by rahuldeshmukh81** [pact-foundation/pact-jvm#1321]
Provider side matching is not working if I add any thing or rename or remove any field in request body of provider which is not same as contract then its not failing.

Eg inside contract file request body contain name field and the same field if I remove or rename in request body of provider (not in response) only in request then pact is not validating that.

I want to confirm at provider side will the matching work on request body? 

I can see matching rule for request body in pact file but its seems like not functioning.
Ref https://github.com/pact-foundation/pact-jvm/issues/1320

@bethesque @uglyog Please help

**Comment by uglyog** [comment]
Pact does not validate the request on the provider side, it invokes the provider using the request in the Pact file, and validates the **response**.
