### ISSUE TITLE
@IgnoreNoPactsToVerify passes verification tests when a connection to the pact-broker can't be established

### ISSUE THREAD

**Issue by jarmy** [pact-foundation/pact-jvm#1322]
If running a Pact verification `SpringBootTest` with `@IgnoreNoPactsToVerify` and there's no SSL/TLS certificates installed allowing a connection to the pact-broker, the test will pass with `No pacts found to verify`.  After enabling debugging on the test side, I was able to find this event (full log 
[pact_SSLHandshakeException.log](https://github.com/pact-foundation/pact-jvm/files/6117992/pact_SSLHandshakeException.log)):
```
09:53:46.187 [DEBUG] [TestEventLogger]     2021-03-10T09:53:46.154-0800 [Test worker] WARN  a.c.d.pact.core.pactbroker.HalClient - Could not fetch the root HAL document
09:53:46.187 [DEBUG] [TestEventLogger]     javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

```

I'd like to think that if no connection can be made to the broker, the test would fail.

Here's the pact libraries we're using:
```
    testImplementation "au.com.dius.pact.provider:junit5:4.1.7"
    testImplementation "au.com.dius.pact.provider:junit5spring:4.1.7"
```

**Comment by uglyog** [comment]
@jarmy could you try with the latest versions (4.1.17)? The error handling was changed.

**Comment by jarmy** [comment]
@uglyog After upgrading, the test fails with `au.com.dius.pact.core.pactbroker.InvalidNavigationRequest: Failed to fetch the root HAL document`. This is resolved.
