### ISSUE TITLE
Does Pact have some feature to make redirects?

### ISSUE THREAD

**Issue by wedla** [pact-foundation/pact-jvm#1323]
Hello all! I'm sorry if this were already answered, but I didn't find anything to help me.

I'm trying to do the following tests with two "different" endpoints:

- one that ends without a trailing slash, for example: /invoice (POST)
- another that ends with a trailing slash, like: /invoice/ (POST)

I'm receiving 307 from the server. Is there a way that pact can handle this http code, get the exact location that comes in the response header, and try to make the request again?

I noted that with get requests, I don't face this problem, but with post ones, the test fails because it was expecting another http code (such as 202, 400) but received 307 (temporary redirect) and doesn't try making the request again.

My code:

![image](https://user-images.githubusercontent.com/15742763/110709854-a8845d80-81db-11eb-8281-6ada45c65513.png)

where:
caminhoTransmissaoMultiplaComBarra = /invoices/
verboRequisicao = POST
cabecalhoTransmissaoSemEscopo = a bearer token + headers with content-type being "application/json".

**Comment by uglyog** [comment]
Redirect handling was disabled due to #952

I think a system property would help to enable that.

**Comment by uglyog** [comment]
4.1.18 released. You can set the system property  `pact.verifier.enableRedirectHandling=true` to enable it.

**Comment by wedla** [comment]
Hi @uglyog, sorry for the late response, but there is a future date for publishing this version on maven repository? my project is a maven one and i verified that this version is not there yet.

**Comment by uglyog** [comment]
It is definitely there: https://repo1.maven.org/maven2/au/com/dius/pact/consumer/junit/4.1.18/ in fact 4.1.19 is now the latest version

**Comment by wedla** [comment]
Hi, @uglyog, this isse can be closed. I verified it and it works smoothly! Thank you very much!
