### ISSUE TITLE
PactDslJsonBody().stringType() not working as expected

### ISSUE THREAD

**Issue by sushant-17** [pact-foundation/pact-jvm#1325]
Hello,

I am trying to make a contract where all the json attributes are string type, so I am using .stringType throughout. I expect the provider to match on all the properties for any kind of string but it's failing.

`DslPart orgDetailsPart = new PactDslJsonBody().stringType("country").stringType("city").stringType("cityDescription")
                .eachLike("internalIdentifiers").stringType("identifierType").stringType("identifierValue").closeArray()
                .eachLike("organisationNames").stringType("type").stringType("value").closeArray();`

`DslPart responseBody_200 = new PactDslJsonBody().object("hierarchy", new PactDslJsonBody().stringType("type").object("hierarchyTree")
                .object("organisationDetails", orgDetailsPart)
                .eachLike("children").object("organisationDetails", orgDetailsPart).closeArray()
                .closeObject());`

`return builder
                .given("GET OK Response")
                .uponReceiving(MessageFormat.format("A request to {0}", URL))
                .path(URL)
                .headers(headers)
                .method(HttpMethod.GET.toString())
                .willRespondWith()
                .status(HttpStatus.OK.value())
                .body(responseBody_200)
                .toPact();`

On provider, it gives assertion failure because all the properties are trying to match to "string" instead of any string value.

I am using the following dependencies:
<artifactId>pact-jvm-consumer-junit5_2.12</artifactId>
            <version>3.6.13</version>

<artifactId>pact-jvm-provider-junit5_2.12</artifactId>
            <version>3.6.13</version>

<artifactId>pact-jvm-provider-maven</artifactId>
                <version>4.0.0</version>

Any ideas what is going wrong here?

**Comment by sushant-17** [comment]
I get assertion failures like such:

$.hierarchy.hierarchyTree.children.0.organisationDetails.city -> Expected 'string' but received '1385'
$.hierarchy.hierarchyTree.children.0.organisationDetails.cityDescription -> Expected 'string' but received 'Fremont'

**Comment by uglyog** [comment]
You must not mix major versions of the Pact-JVM libraries (3.6.13 and 4.0.0). Also, if you try with the latest versions it might help.

**Comment by sushant-17** [comment]
I think 3.6.13 is almost latest version, and then I also tried with maven plugin version 4.0.10
I still face the same error

**Comment by uglyog** [comment]
4.2.3 is the latest version:
`au.com.dius.pact.consumer:junit5:4.2.3`
`au.com.dius.pact.provider:junit5:4.2.3`

**Comment by sushant-17** [comment]
Alright, I get it now. So it works when I started using the 4.x.x versions.
Thanks a lot! :)
