### ISSUE TITLE
Ignore the scale of decimal values being compared by the JsonBodyMatcher

### ISSUE THREAD

**Issue by sdobrovolschi** [pact-foundation/pact-jvm#1335]
For some reason, the trailing zeros from decimal values are removed from pacts upon publishing to the pact broker. This results in pact verification failures if the provider exposes decimals with a specific scale. e.g. a money amount with a scale of 3.
Therefore, given an expected value of 2.3 and an actual value of 2.300 will result in the failure below:
`body: $.price.amount Expected 2.3 (Decimal) but received 2.300 (Decimal)`

Could the [JsonValue#equals](https://github.com/pact-foundation/pact-jvm/blob/master/core/support/src/main/kotlin/au/com/dius/pact/core/support/json/JsonValue.kt#L176) method be changed to use the `compareTo` (that compares the numeric value) instead of `equals` for decimal values?

**Comment by artemptushkin** [comment]
what's the pact-jvm version do you use? it was fine for me since `4.2.*`

**Comment by sdobrovolschi** [comment]
> what's the pact-jvm version do you use? it was fine for me since `4.2.*`

4.2.3

**Comment by uglyog** [comment]
4.2.4 has been released

**Comment by sdobrovolschi** [comment]
> 4.2.4 has been released

Thank you very much.

When is it expected to be published to maven?

https://mvnrepository.com/artifact/au.com.dius.pact.provider/junit5spring

**Comment by uglyog** [comment]
Looks like there was an issue with the release. I've re-released it.

**Comment by sdobrovolschi** [comment]
Thanks for the fix
