### ISSUE TITLE
PactBroker and IgnoreNoPactsToVerify

### ISSUE THREAD

**Issue by ralfovelgoenne** [pact-foundation/pact-jvm#1337]
I set up a test requesting PACTs from PactBroker. Everything works fine if the PACT Broker is up and running. By using the PACT Broker the tests are depending on a running PACT Broker and a valid connection to it. I want to prevent that if the PACT Broker is temporarily down or the developer does not have a valid connection to it the build breaks locally. 
Therefore I used @IgnoreNoPactsToVerify in the test. 
But if the connection fails the tests do fail by:
_2021-04-09
                08:08:56 SEVERE au.com.dius.pact.core.pactbroker.HalClient Failed to fetch the root HAL document
java.net.UnknownHostException: pact-broker.net_

Is there are way to ignore this in case the connection fails to PACT Broker?

The header of my test class:
_@RunWith(PactRunner.class)
@Provider("TestApp")
@IgnoreNoPactsToVerify(ignoreIoErrors = "true")
@PactBroker(host="pact-broker.net", port = "80", authentication = @PactBrokerAuth(username = "test", password = "test"))
public class ExamplePactTest extends JerseyTest {
.._

**Comment by uglyog** [comment]
What version of Pact-JVM are you using?

**Comment by ralfovelgoenne** [comment]
I am using 4.1.15.

**Comment by uglyog** [comment]
4.1.20 has been released

**Comment by ralfovelgoenne** [comment]
Thanks for that, it works for me. Greetings to Melbourne.
