### ISSUE TITLE
Junit5 multiple pact fragments for consumer tests

### ISSUE THREAD

**Issue by artemptushkin** [pact-foundation/pact-jvm#1342]
Hi!

As for Junit4 you have `@PactVerifications` annotation to run **multiple** stubs during the particular test, but won't the analog for this in Junit5 or workaround? We have only `@PactTestFor` that doesn't support multiple `pactMethod`

You Junit4 example that would be appreciated to reproduce in Junit5 - https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit/src/test/java/au/com/dius/pact/consumer/junit/pactproviderrule/PactProviderWithMultipleFragmentsTest.java

I tried to put one `@PactTestFor` on the class level and one on the test, it doesn't work either, as I think it should not be. Even if yes, it doesn't support more than 2 fragments :)

**Comment by uglyog** [comment]
https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit5/src/test/groovy/au/com/dius/pact/consumer/junit5/MultiTest.groovy is an example of how to do it with JUnit 5.

**Comment by uglyog** [comment]
Or are you referring to having a test with multiple providers?

**Comment by artemptushkin** [comment]
@uglyog yes, specifically multiple _stubs by pact_ with one or more providers per consumer. I think multiple providers is also a case and more general even

**Comment by uglyog** [comment]
4.2.5 has been released
