### ISSUE TITLE
Release 4.2.4 is missing on Maven Central

### ISSUE THREAD

**Issue by tlinkowski** [pact-foundation/pact-jvm#1343]
- 4.2.3 exists there: https://search.maven.org/artifact/au.com.dius.pact/consumer/4.2.3/jar
- 4.2.4 doesn't: https://search.maven.org/artifact/au.com.dius.pact/consumer/4.2.4/jar

**Comment by uglyog** [comment]
I don't know what happened there, but I re-released it. It is available now.
