### ISSUE TITLE
Difference in matching rules for headers/query (Pact DSL vs. Groovy DSL)

### ISSUE THREAD

**Issue by tlinkowski** [pact-foundation/pact-jvm#1346]
Hi, as an example, imagine a **boolean** query parameter (or header - it's the same issue) named `debugMode`.

## Definition
Pact DSL:
```java
.matchQuery("debugMode", "true|false", "true")
```

Groovy DSL:
```groovy
                .withAttributes([
                        ...
                        query  : [
                                debugMode: bool(true)
                        ]
                ])
```

## Generated Pact "request"

Both DSLs:
```json
        "query": {
          "debugMode": [
            "true"
          ]
        },
```

## Generated Pact "matching rules"
Pact DSL:
```json
            "debugMode": {
              "matchers": [
                {
                  "match": "regex",
                  "regex": "true|false"
                }
              ],
              "combine": "AND"
            }
```

Groovy DSL:
```json
          "query": {
            "debugMode": {
              "matchers": [
                {
                  "match": "type"
                }
              ],
              "combine": "AND"
            }
```

## Question

Is the behavior in Groovy DSL correct?

Will the "type" matcher actually allow only "true" or "false"? I'm wondering since the example in Pact "request" is actually a String, not a Boolean (and there seems to be no trace in the Pact that `debugMode` is of Boolean type).

**Comment by uglyog** [comment]
I think you are correct, the `bool` function just adds a type matcher, which will match any strings. Let me confirm.

**Comment by uglyog** [comment]
I've added a boolean matcher that will match the string values of `true` and `false`. Will only work with V4 spec, but you can also use the regex matcher.

**Comment by uglyog** [comment]
4.2.5 has been released
