### ISSUE TITLE
Junit5 + spring + mocks does not work when I mock in the state

### ISSUE THREAD

**Issue by leonleo997** [pact-foundation/pact-jvm#1349]
Hey there!
I'm running into a problem:

I'm trying to mock a service to return a list of animals, however, when I mocked the method into the `@State` it does not work but if I mocked the method in a  `@BeforeEach` it works. Any idea?

This is the code:
```java
@ExtendWith(SpringExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Provider("AnimalShelterBack")
@PactFolder("pacts")
@Slf4j
public class listAnimal {
    @LocalServerPort
    private int port;

    @Mock
    private AnimalService animalService;

    @InjectMocks
    private AnimalController animalController;

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }

    @BeforeEach
    void before(PactVerificationContext context) {
        MockitoAnnotations.initMocks(this);
        MockMvcTestTarget target = new MockMvcTestTarget();
        target.setControllers(animalController);
        context.setTarget(target);
    }

//    @BeforeEach// UNCOMMENT THE ANNOTATION TO MAKE IT WORKS
    private void createAnimal() {
        Animal animal = new Animal();
        animal.setName("Yesid");
        animal.setGender("Male");
        animal.setBreed("Bengali");
        animal.setVaccinated(true);
        animal.setVaccines(new String[]{"Leucemia"});
        ArrayList animals = new ArrayList();
        animals.add(animal);

        Mockito.when(animalService.getAll()).thenReturn(animals);
    }

    @State("there are animals")
    public void getAnimals() {
        createAnimal(); //IT SHOULD WORK HERE BUT IT DOES NOT WORK
    }
}

```

**Comment by leonleo997** [comment]
FYI: this is the repo, the branch is: https://github.com/leonleo997/animal-shelter-java-back/pull/6/files

**Comment by gediminasmorkys** [comment]
@leonleo997 

Have you tried moving your Mockito.when() statement to be inside the `@State` method? That seems to work well for me.

e.g.

    private List<Animal> createAnimals() {
        Animal animal = new Animal();
        animal.setName("Yesid");
        animal.setGender("Male");
        animal.setBreed("Bengali");
        animal.setVaccinated(true);
        animal.setVaccines(new String[]{"Leucemia"});
        ArrayList animals = new ArrayList();
        animals.add(animal);
        return animals;
    }


@State("there are animals")
    public void getAnimals() {
        Mockito.when(animalService.getAll()).thenReturn(createAnimals());
        createAnimal();
    }

**Comment by leonleo997** [comment]
ohhh I didn't try, I will
