### ISSUE TITLE
fail maven build if publish verification results fails

### ISSUE THREAD

**Issue by janssk1** [pact-foundation/pact-jvm#1364]
If the broker rejects verification results (might happen if the version used to publish is not semver compliant), the maven plugin only prints out a message. 

It should (conditionally?) fail the build, making it clear that something failed. Now the build is green, but no results are published. 

Version: 4.1.20

**Comment by uglyog** [comment]
Are you using JUnit tests to verify your provders?

**Comment by janssk1** [comment]
Right. Junit5. I'm using the approach documented in https://docs.pact.io/implementation_guides/jvm/provider/junit5/

**Comment by uglyog** [comment]
4.2.6 has been released
