### ISSUE TITLE
pact to check output array has a particular element - tried arrayContaining but it doesn't work

### ISSUE THREAD

**Issue by keeping-it-up** [pact-foundation/pact-jvm#1367]
Our requirement is to have a contract which make sure that response returns an array which must have at least the elements we are using.

We are using arrayContaining method with pact 4.2.5 version.

For example, api response is following:

```
{
    "output": [
        "a",
        1,
        {
            "id": 10,
            "name": "john"
        }
    ]
}
```

from this response, we are interested in first element 'a'. so response array must have 'a' element, we don't care if array has extra element (which it will have hence we are using arrayContaining() instead of array() method).

Now at consumer end, I expected following to work, but it doesn't:

```
.body(newJsonBody(o -> {
                    o.arrayContaining("output", a -> {
                       a.stringValue("a");
                    });
                }).build())
```

Error: 

```
java.util.NoSuchElementException
	at au.com.dius.pact.consumer.dsl.PactDslJsonArrayContaining.closeArray(PactDslJsonArrayContaining.kt:30)
	at au.com.dius.pact.consumer.dsl.LambdaDslObject.arrayContaining(LambdaDslObject.java:1133)
	at com.pact.PactTest.lambda$method$2(PactTest.java:47)
	at au.com.dius.pact.consumer.dsl.LambdaDsl.newJsonBody(LambdaDsl.java:116)
```

It seems arrayContaining() needs at least one type element, so following code works:

```
.body(newJsonBody(o -> {
                    o.arrayContaining("output", a -> {
                       a.stringType("a");
                    });
                }).build())
```

But then producer test works if output array has any string element - I need make sure that it has string element 'a'.

Following also works at consumer end:

```
.body(newJsonBody(o -> {
                    o.arrayContaining("output", a -> {
                       a.numberType(10);
                       a.stringValue("a");
                    });
                }).build())
```

Producer tests again pass because number 1 in output matches with numberType and it doesn't check if output really contain string 'a'.

Is there no way to check output array has a particular element?

Thanks.

**Comment by uglyog** [comment]
4.2.6 has been released

**Comment by keeping-it-up** [comment]
Thanks. Its working now partially.

So this works now:

```
.body(newJsonBody(o -> {
                    o.arrayContaining("output", a -> {
                       a.stringValue("a");
                    });
                }).build())

```
This checks that response array must have 'a' element.

However arrayContaining() seems to be matching fine if any one element matches.

If I want to make sure that response must have more than 1 elements which I am interested in, for example response array must have 'a' and 1 elements. Then I would write contract like following:

```
.body(newJsonBody(o -> {
                    o.arrayContaining("output", a -> {
                       a.numberValue(1);
                       a.stringValue("a");
                    });
                }).build())
```


However its not checking both elements, this matches fine if response array has either 1 or 'a'.
I would like it to match if response has both 1 and a.

Is there a way to achieve that?

Thanks.

**Comment by uglyog** [comment]
Hmm, that sounds like an issue. I'm sure it is meant to match both

**Comment by uglyog** [comment]
I can't replicate that. I've setup a test that expects the two values ("a" and 1), and then if I pass in `["b", {"id": 10,"name": "john"}, 1, true]` I get `mismatch=Variant at index 0 (a) was not found in the actual list`

**Comment by uglyog** [comment]
Ah! Looks like the `arrayContaining` DSL method is not constructing the matching rule correctly

**Comment by keeping-it-up** [comment]
Thanks Ronald, please let me know when new release is available.

**Comment by uglyog** [comment]
4.2.7 has been released

**Comment by keeping-it-up** [comment]
works fine, thank you.
