### ISSUE TITLE
Request body encoded for graphql content type

### ISSUE THREAD

**Issue by fuudge** [pact-foundation/pact-jvm#1371]
Recently upgraded from Pact 3.6.2 to 4.1.21, everything looks ok except one test where graphql endpoint is used and the generated pact file uses encoded value for request body instead of actual graphql query. I'm guessing this isn't supported and is down to application/graphql being used instead of json, but is there any way to treat it like a text similar to json?

I'm using DSL to generate the RequestResponsePact and running with JUnit

**Comment by fuudge** [comment]
I found the system property `pact.content_type.override.<TYPE>.<SUBTYPE>=text|binary|json` I can use to override the non binary "classification" of the graphql content type.

**Comment by fuudge** [comment]
I found the system property `pact.content_type.override.<TYPE>.<SUBTYPE>=text|binary|json` I can use to override the non binary "classification" of the graphql content type.

**Comment by uglyog** [comment]
Could you provide the content type that is used by GraphQL?

**Comment by fuudge** [comment]
Sorry if that wasn't very clear but it's `application/graphql`

**Comment by uglyog** [comment]
I'll add that to the list of json content types
