### ISSUE TITLE
Authentication using bearer toker

### ISSUE THREAD

**Issue by naushadamin** [pact-foundation/pact-jvm#1378]
Pack documentation states the following way to pass bearer token using Junit:

```
@PactBroker(host = "${pactbroker.url:localhost}", port = "1234", tags = {"latest", "prod", "dev"},
  authentication = @PactBrokerAuth(token = "test"))
```

However, the javadoc doesn't mention the token attribute nor is it available in the source. How do I pass bearer token as a provider to verify Pact?

**Comment by mefellows** [comment]
https://docs.pactflow.io/#java--junit-5

Note the open source pact broker doesn't support bearer tokens, only Pactflow (unless if course you've added your own security on top).

**Comment by uglyog** [comment]
What version are you using? Token support was added in 4.0.2.

**Comment by naushadamin** [comment]
Thanks! I was able to access contract using bearer token with 4.0.10. PactBroker verification failed and it was expected. I was hoping to see a track/record/audit of failed verification in Pactflow. However, the UI shows it as Never. Is that expected?

**Comment by mefellows** [comment]
You need to enable publishing of verification results. Please consult the docs for how to do this for your specific situation.

e.g. https://docs.pact.io/implementation_guides/jvm/provider/gradle/#3-execute-gradle-pactverify
