### ISSUE TITLE
Regenerate ANTLR code using version 4.8 or later

### ISSUE THREAD

**Issue by knutwannheden** [pact-foundation/pact-jvm#1380]
I am running pact tests in the context of a Quarkus service and about 1 year ago Quarkus upgraded from ANTLR 4.7.2 to ANTLR 4.8 (meanwhile ANTLR 4.9.2 is available). Now when running my tests I see a warning like this logged:

```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8
```

Since ANTLR 4.7.2 is already more than two years old I think it would be nice to upgrade to a newer version.

**Comment by uglyog** [comment]
I've checked the release notes, and there are no changes for Java so I've upgraded to 4.9.2

**Comment by knutwannheden** [comment]
I think the ANTLR generator would also have to be rerun, as the ANTLR version is generated as a constant somewhere.

**Comment by knutwannheden** [comment]
I couldn't find it in the repo anywhere. So I take it the generator is automatically executed as part of the build, which is perfect.

**Comment by uglyog** [comment]
> I couldn't find it in the repo anywhere. So I take it the generator is automatically executed as part of the build, which is perfect.

Yes, it uses the Gradle plugin to generate the source

**Comment by uglyog** [comment]
4.2.7 has been released

**Comment by knutwannheden** [comment]
I have verified that this now works. Thanks!
