### ISSUE TITLE
validating contract with pact-jvm-spring

### ISSUE THREAD

**Issue by naushadamin** [pact-foundation/pact-jvm#1381]
In looking at the example provided in your workshop, I see the provider side of the validation is checking response shape(contract in my opinion) but also attribute values. I don't see a way to validate just the shape of the response. Is that possible with pact-jvm-spring?

**Comment by mefellows** [comment]
Can you please expand on your question? If you're want to test the response shape but not fail on specific values, you should use the matchers e.g. https://docs.pact.io/implementation_guides/jvm/consumer/junit#dsl-matching-methods

**Comment by naushadamin** [comment]
The example is from the consumer side. I am looking for instructions/examples to do the similar on provider side.

**Comment by mefellows** [comment]
The consumer is responsible for adding the matchers, not the provider.

**Comment by naushadamin** [comment]
Thanks!
