### ISSUE TITLE
Allow specifying `@PactDirectory` on outer class of `@Nested` test

### ISSUE THREAD

**Issue by knutwannheden** [pact-foundation/pact-jvm#1382]
I think it would be nice if `@PactDirectory` could be specified on the outer class of a `@Nested` test like this:

```java
@ExtendWith(PactConsumerTestExt.class)
@PactTestFor(providerName = "provider")
@PactDirectory("../my-pacts")
public class FooPactConsumerTest {

    @Nested
    class GreetingTest {
        @Pact(consumer = "consumer")
        public RequestResponsePact createFragment(PactDslWithProvider builder) {
            return null;
        }

        @Test
        @PactTestFor(providerName = "provider")
        void testRequests() {
        }
    }
}
```

This is for instance useful when declaring multiple `@Nested` tests inside the same outer class as otherwise the `@PactDirectory` annotation needs to be repeated for each nested test. This would also be in line with how the JUnit 5 [`@Timeout` annotation works](https://junit.org/junit5/docs/current/user-guide/#writing-tests-declarative-timeouts):
> To apply the same timeout to all test methods within a test class and all of its `@Nested` classes, you can declare the `@Timeout` annotation at the class level. It will then be applied to all test, test factory, and test template methods within that class and its `@Nested` classes unless overridden by a `@Timeout` annotation on a specific method or `@Nested` class. Please note that `@Timeout` annotations declared at the class level are not applied to lifecycle methods.

**Comment by uglyog** [comment]
4.2.7 has been released

**Comment by knutwannheden** [comment]
I have verified that this now works. Thanks!
