### ISSUE TITLE
Including -Dpact.provider.tag causes "link was missing" error if slash (/) in provider name

### ISSUE THREAD

**Issue by csydvs** [pact-foundation/pact-jvm#1388]
So I'm using the junit5spring maven dependency (4.2.6), and pactfoundation/pact-broker version 2.79.1.2, and whenever I run my command that looks something like this:
```mvn verify -Dpact.provider.version=${BUILD_VERSION}_${GIT_COMMIT_SHA} -Dpact.verifier.publishResults=true -Dpact.provider.tag=${GIT_BRANCH_NAME}```

I get an error that says 
```
FAILURE!
java.lang.AssertionError: Failed to update the test results: Could not tag provider [my/provider-name], link was missing
```
This command works for me as long as I don't include the -Dpact.provider.tag piece, but of course it doesn't tag my version without that.

I looked through the [original issue for tagging provider versions](https://github.com/pact-foundation/pact-jvm/issues/823), as well as some of the [source code](https://github.com/pact-foundation/pact-jvm/blob/b5da12bf65eee44f47f47b5657929615ed213230/core/pactbroker/src/main/kotlin/au/com/dius/pact/core/pactbroker/PactBrokerClient.kt), and I'm wondering if `pb:provider` just doesn't exist on my version of the broker for some reason? I don't see it on my HAL browser page, but I've never used the HAL browser before so maybe I'm missing something and it's just a misconfiguration of some kind on my part. 

Workaround for now is to just tag using the CLI, of course, but it would be more convenient to use the library for the given language if possible. 

Thanks!

**Comment by uglyog** [comment]
That version should have that link. It might be the slash in the provider name that is the problem.

You can confirm it by going to the HAL browser and selecting `Latest pact versions`
![image](https://user-images.githubusercontent.com/863666/123534623-c57c7680-d761-11eb-875b-43316ed5b807.png)

Then find your provider in the list and select the latest pact link (actually can use any one)
![image](https://user-images.githubusercontent.com/863666/123534680-2146ff80-d762-11eb-9155-02bfd8af605d.png)

Then select the `Provider` link
![image](https://user-images.githubusercontent.com/863666/123534707-56ebe880-d762-11eb-9a5f-400599544a45.png)

You should see the link there:
![image](https://user-images.githubusercontent.com/863666/123534741-9b778400-d762-11eb-85cd-ef071e948e6a.png)

**Comment by csydvs** [comment]
Interesting. Thanks for the play-by-play, I followed your instructions, and, sure enough, it was there. My guess is that this indeed the slash in the provider name issue, as you said, although it should be pretty narrow since I haven't had any other issues in the rest of the functionality (or in tagging my provider using the cli). I'll rename the ticket to make it more specific for that case.

**Comment by uglyog** [comment]
4.2.8 is released

**Comment by csydvs** [comment]
Version 4.2.8 did the trick for me. Thanks!
