### ISSUE TITLE
Skip pact tests at ./gradlew build goal

### ISSUE THREAD

**Issue by miaguicam7** [pact-foundation/pact-jvm#1390]
Hi all,

I would need to ignore the execution of the Pact tests when I run the "./gradlew build" goal. Is there a flag that  can skip them without having to touch code?

Thank you very much!

**Comment by uglyog** [comment]
If you are writing the Pact tests as unit tests, then you need to use the standard way to skip tests for the test framework used (i.e JUnit 4 or 5)
