### ISSUE TITLE
Build passes when provider is removed

### ISSUE THREAD

**Issue by mcarn** [pact-foundation/pact-jvm#1391]
We are facing an issue in our pipelines when removing a Provider java class, as it stands we should be validating that the consumers are not affected when the provider is deleted or changed. But the pipeline is passing. At the moment, we are creating a branch where we remove Provider classes, expecting the pipeline to fail when tested with all current consumers.
To run the pipeline we are using a multiple step approach, starting with a mvn call with the following mvn arguments
```
mvn -B -Dpactbroker.consumerversionselectors.tags=master -Dpactbroker.providerTags=master -Dpactbroker.host=${PACT_BROKER_HOST} -Dpactbroker.auth.token=${PACT_BROKER_TOKEN} -Dpact.verifier.publishResults=true -Dpact.provider.version=$PACT_PROJECT_VERSION -Dpact.provider.tag=$BITBUCKET_BRANCH verify
```
In the logs we are able to see that we are checking against the consumers, but the following appears  
>Not all of the 6 were verified. The following were missing:
> 
>xxxxCommand
> 
>yyyyCommand
> 
But it still passes.
And a second step where we call can-i-deploy in a docker command
```
mvn pact:publish -Dpact.broker.token=$PACT_BROKER_TOKEN -Dpact.broker.url=https://$PACT_BROKER_HOST -Dpact.projectVersion=$PACT_PROJECT_VERSION -Dpact.consumer.tags=$BITBUCKET_BRANCH
docker run --rm -v ${PWD}:${PWD} -e PACT_BROKER_BASE_URL=https://$PACT_BROKER_HOST -e $PACT_BROKER_TOKEN pactfoundation/pact-cli:latest broker can-i-deploy --broker-base-url $PACT_BROKER_HOST --broker-token $PACT_BROKER_TOKEN --pacticipant ${BITBUCKET_REPO_SLUG} --version $PACT_PROJECT_VERSION --to master --retry-while-unknown 60 --retry-interval 10
```
I assume that the first step of the pipeline, the maven call, should fail as the contract will be broken.
* Are we wrongly configuring pact? We have filtering enabled.

**Comment by mefellows** [comment]
Thanks Miguel, can you please share debug logs (with any sensitive information redacted)?

**Comment by mcarn** [comment]
Here is the file. Thanks
[ics2_23062021.txt](https://github.com/pact-foundation/pact-jvm/files/6709950/ics2_23062021.txt)

**Comment by mefellows** [comment]
I can't quite follow the entire log file, but it looks like you have pending pacts enabled:

> [INFO]     2) This pact is in pending state for this version of ku-item-command-service because a successful verification result for a version of ku-item-command-service with tag 'master' has not yet been published. If this verification fails, it will not cause the overall build to fail. Read more at https://docs.pact.io/go/pending

So any failures for those contracts shouldn't block the build. It looks like 2/3 contracts aren't pending though.

I might need @uglyog to look into this one to ensure the output and behaviour is correct.

**Comment by mcarn** [comment]
They shouldn't be pending as they have been verified at least once.

**Comment by mefellows** [comment]
> They shouldn't be pending as they have been verified at least once.

Are you sure it's been validated for the _provider tag_ `master`?  

For clarity, I'm referring to [this sentence](https://docs.pact.io/pact_broker/advanced_topics/pending_pacts/) from the docs:

> The provider tags are used to determine the pending status because it is common to implement new features of a provider on a feature branch. If the provider tags were not taken in to consideration, a newly passing verification on feat-x of the provider would suddenly cause the verification of that content by branch main of the provider to fail.

We should be able to clarify this on our side, I think (as per your support ticket). 

> We have filtering enabled.

I also missed this bit the first time around, could you please elaborate on what that means exactly?

**Comment by mcarn** [comment]
> Are you sure it's been validated for the provider tag master?

The logs are displaying the following, so we assume it's been validated:

```
 [INFO]     2) This pact has previously been successfully verified by a version of ku-item-command-service with tag 'master'. If this verification fails, it will fail the build. Read more at https://docs.pact.io/go/pending
```

>I also missed this bit the first time around, could you please elaborate on what that means exactly?

We use the feature from [Pact junit runner - Filtering the interactions that are verified](https://docs.pact.io/implementation_guides/jvm/provider/junit/#filtering-the-interactions-that-are-verified). We use these filters  so that we can have one class per interaction verification, making them cleaner.

**Comment by mefellows** [comment]
OK so this makes a bit more sense.

Note the [warning](https://docs.pact.io/implementation_guides/jvm/provider/junit/#filtering-the-interactions-that-are-verified):

![Screen Shot 2021-07-01 at 10 17 27 pm](https://user-images.githubusercontent.com/53900/124123033-208fcf80-daba-11eb-96b8-198bcd089c69.png)

Unless I'm mistaken about a JVM specific feature, filtering is intended for isolating one or more tests for dev reasons. It's not designed for integrating back to the broker, because it wouldn't receive a transactional, binary true/false response, to be able to determine compatibility etc.

This also explains why your contracts are pending, because verification results haven't been published to prove you're compatible. The contract is still pending, regardless of whether or not it can satisfy the needs of the consumer.

So your `can-i-deploy` still works, presumably, because as far as its concerned, your provider hasn't changed and the version that works still satisfies the contract.

**Comment by mcarn** [comment]
> Unless I'm mistaken about a JVM specific feature, filtering is intended for isolating one or more tests for dev reasons. It's not designed for integrating back to the broker, because it wouldn't receive a transactional, binary true/false response, to be able to determine compatibility etc.

We have removed the filtering annotations and now the pipeline fails. That worked! Filtering was our issue.

>This also explains why your contracts are pending, because verification results haven't been published to prove you're compatible. The contract is still pending, regardless of whether or not it can satisfy the needs of the consumer.

Pending pacts already worked as expected. Most of the pacts are verified but only some new pacts are new and still pending.

We will work towards fixing these things. 
Thanks for your time @mefellows

**Comment by mefellows** [comment]
Good to hear (and thank goodness) - thanks for clarifying @mcarn .
