### ISSUE TITLE
provider scala implementation dependency leaks

### ISSUE THREAD

**Issue by caoilte** [pact-foundation/pact-jvm#1395]
The provider has an "implementation" dependency on Scala. I don't know how or why, but this is leaking to both kotlin and scala users of the library (leading to things like this https://pact-foundation.slack.com/archives/C9UN99H24/p1623952632261000).

Possibly you need to include the Java Library Plugin in order to make implementation dependencies work correctly? (I've never used Gradle so I could be way off.)

https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

**Comment by uglyog** [comment]
4.2.8 is released
