### ISSUE TITLE
Check metadata - spring message PACT

### ISSUE THREAD

**Issue by juan-fernandez-enverus** [pact-foundation/pact-jvm#1397]
Hello,

Working on a project with some specifics for the expected info in the message metadata. I can see the DSL allows to specify that. But I can see no way to verify that info.

Consumer only injects the body on the byte array:

```
public void setMessage(byte[] message) {
    this.currentMessage = message;
}
```

Provider only can verify the body on the returning string:

```
@PactVerifyProvider("my scenario")
public String test() {
    return body;
}
```

What about metadata? It is strange to be able to specify it in the DSL but not be able to verify it in the tests.

**Comment by uglyog** [comment]
Your test method should return both the message contents and the metadata. See https://github.com/pact-foundation/pact-jvm/tree/master/provider/junit#example-of-message-test-that-verifies-metadata

**Comment by juan-fernandez-enverus** [comment]
Awesome! Thank you very much for the answer
