### ISSUE TITLE
pact:can-i-deploy retryInterval/retriesWhenUnknown not working as expected

### ISSUE THREAD

**Issue by bawoodruff** [pact-foundation/pact-jvm#1405]
Per the Slack channel conversation:

When I have an unknown version of the pact pushed to the pact broker, I expect that the retry process would occur with the maven plugin until a result is posted or the retry period has expired.  Instead, the plugin returns a failure case immediately. Our system is using the OSS pactbroker 2.79.0.

The pact CLI works as expected in this scenario but maven is better suited for our CI configuration.  Logging from -X for pact:can-i-deploy is below.

01:15:25 [DEBUG] -----------------------------------------------------------------------
01:15:25 [DEBUG] Goal:          au.com.dius.pact.provider:maven:4.2.7:can-i-deploy (default-cli)
01:15:25 [DEBUG] Style:         Regular
01:15:25 [DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
01:15:25 <configuration>
01:15:25   <latest default-value="">true</latest>
01:15:25   <pactBrokerAuthenticationScheme default-value="basic">basic</pactBrokerAuthenticationScheme>
01:15:25   <pactBrokerPassword>${pactbroker.auth.password}</pactBrokerPassword>
01:15:25   <pactBrokerServerId>${pact.broker.serverId}</pactBrokerServerId>
01:15:25   <pactBrokerToken>${pact.broker.token}</pactBrokerToken>
01:15:25   <pactBrokerUrl>https://redacted</pactBrokerUrl>
01:15:25   <pactBrokerUsername>${pactbroker.auth.username}</pactBrokerUsername>
01:15:25   <pacticipant>PetstoreService</pacticipant>
01:15:25   <pacticipantVersion>${pacticipantVersion}</pacticipantVersion>
01:15:25   <retriesWhenUnknown default-value="0">10</retriesWhenUnknown>
01:15:25   <retryInterval default-value="10">300</retryInterval>
01:15:25   <settings default-value="${settings}"/>
01:15:25   <to default-value="">${pact.tag}</to>
01:15:25 </configuration>
01:15:25 [DEBUG] =======================================================================
01:15:25 [INFO] 
01:15:25 [INFO] --- maven:4.2.7:can-i-deploy (default-cli) @ bryanwconsumer01 ---
...
01:15:26 [DEBUG] Configuring mojo au.com.dius.pact.provider:maven:4.2.7:can-i-deploy from plugin realm ClassRealm[plugin>au.com.dius.pact.provider:maven:4.2.7, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@4b85612c]
01:15:26 [DEBUG] Configuring mojo 'au.com.dius.pact.provider:maven:4.2.7:can-i-deploy' with basic configurator -->
01:15:26 [DEBUG]   (f) latest = true
01:15:26 [DEBUG]   (f) pactBrokerAuthenticationScheme = basic
01:15:26 [DEBUG]   (f) pactBrokerUrl = https://redacted
01:15:26 [DEBUG]   (f) pacticipant = PetstoreService
01:15:26 [DEBUG]   (f) retriesWhenUnknown = 10
01:15:26 [DEBUG]   (f) retryInterval = 300
01:15:26 [DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@4a50d04a
01:15:26 [DEBUG] -- end configuration --
01:15:26 Computer says no ¯\_(?)_/¯ 
01:15:26 
01:15:26 There is no verified pact between the latest version of PetstoreConsumer (5b926da) and the latest version of PetstoreService (fec1397)

**Comment by bawoodruff** [comment]
Haven't tried this locally yet, but I don't see the configuration passed along, should the brokerClientConfig in PactCanIDeployMojo.kt be updated as per below?

```
    if (brokerClient == null) {
      brokerClient = PactBrokerClient(pactBrokerUrl!!, brokerClientOptions(), brokerClientConfig(retriesWhenUnknown, retryInterval))
    }

```

**Comment by bawoodruff** [comment]
Added some tracing and deployed locally:

`[DEBUG] Matrix Query: /matrix?q[][pacticipant]=PetstoreService&latestby=cvp&q[][latest]=true&latest=true
[DEBUG] result = Ok({"matrix":[{"consumer":{"_links":{"self":{"href":"https://redacted/pacticipants/PetstoreConsumer"}},"name":"PetstoreConsumer","version":{"_links":{"self":{"href":"https://redacted/pacticipants/PetstoreConsumer/versions/5b926da"}},"branch":null,"number":"5b926da","tags":[]}},"pact":{"_links":{"self":{"href":"https://redacted/pacts/provider/PetstoreService/consumer/PetstoreConsumer/version/5b926da"}},"createdAt":"2021-07-20T01:14:02+00:00"},"provider":{"_links":{"self":{"href":"https://redacted/pacticipants/PetstoreService"}},"name":"PetstoreService","version":null},"verificationResult":null}],"summary":{"deployable":null,"failed":0,"reason":"There is no verified pact between the latest version of PetstoreConsumer (5b926da) and the latest version of PetstoreService (fec1397)","success":0,"unknown":1}})
`

**Comment by bawoodruff** [comment]
Tracked this down, submitting a PR

**Comment by bawoodruff** [comment]
https://github.com/pact-foundation/pact-jvm/pull/1406

**Comment by uglyog** [comment]
4.2.8 is released

**Comment by bawoodruff** [comment]
Verified.  Thanks!

**Comment by bawoodruff** [comment]
CI is not progressing when the pact is verified.

**Comment by bawoodruff** [comment]
The plugin was handling this correctly, the verification was not completed for all versions.  When the verification was posted correctly, the plugin worked as expected.
