### ISSUE TITLE
Enabling contract testing with Pact

### ISSUE THREAD

**Issue by naushadamin** [pact-foundation/pact-jvm#1408]
Hello, I am trying to understand the steps to complete in our development process to enable contract testing with Pact.

My understanding is that the following steps will need to be complete to enable Contract testing. Typically Consumer will be the driver to initiate the process:

1. add/update contract
2. add/update unit test
3. write contract
4. publish contract
5. verify contract
6. ok to deploy

Does pactVerify generate(upon successful verification) data that for verification metrix for pact broker? If the answer is yes, then why do we need to add a subsequent step in my pipeline after ok to deploy to register verification. If the answer is no then how will ok to deploy task be ever successful since I haven't deployed yet. I was looking at your documentation for canIDeploy task here: https://docs.pact.io/pact_broker/can_i_deploy/. Please advise

**Comment by uglyog** [comment]
Yes, pactVerify will publish the verification results to the pact broker. There is no subsequent after ok to deploy to register verification.

You can find more information at https://docs.pact.io/pact_nirvana

**Comment by naushadamin** [comment]
I am trying to configure pactVerify task in build.gradle as following:

`pact {
    broker {
            pactBrokerUrl = 'somebrokerurl'
            // OR to use a bearer token
            pactBrokerToken = 'sometoken'
    }

    serviceProviders {
        siteapi {
            protocol = 'http'
            host ='localhost'
            port = 8181
            path = '/somepath'

            hasPactWith('siteapi-consumer') {
                pactSource = url('path to contract')
            }

        }
    }
}`

When I execute the task I am getting the following error:

**You must specify the pactfile to execute (use pactFile = ...)**

I verified the url specified in pactSource is a valid one using curl or postman. Why am I getting the error above?

**Comment by uglyog** [comment]
@naushadamin please upgrade to the latest version.

Also, if you're using a pact broker see https://github.com/pact-foundation/pact-jvm/tree/master/provider/gradle#for-pact-jvm-410-and-later

**Comment by naushadamin** [comment]
For a given consumer I have n number of providers. I am trying to setup a CI/CD pipeline to add publish/validate/deploy steps. Do you have any reference/example I can review?

**Comment by uglyog** [comment]
The Pact Broker has logic to determine if a pact has changed. The best way to to always publish to the broker, and it will work out the correct things to do based on whether the pact has changed or not.

**Comment by YOU54F** [comment]
Yes see the CI/CD workshop

https://docs.pactflow.io/docs/workshops/ci-cd/

> I am trying find if there is any out of box support to conditionally publish contracts only when a change is detected

The Pact Broker will take care of this, you publish contracts from every build, it will determine if the contents have changed and publish the required verification
