### ISSUE TITLE
Allow {variable} vs ${variable} specifier in parameterized paths

### ISSUE THREAD

**Issue by bawoodruff** [pact-foundation/pact-jvm#1410]
I'd like to be able to share URI specifications between Pact and RestTemplate -- but parameterized paths in Pact JVM are using ${variable} whereas Spring's RestTemplate use {variable} in the path specification.

I am currently performing a workaround as such:

```
 .pathFromProviderState(
    StoreManagement.UriComponents.GET_STORE_BY_RELATIVE_STORE_URL.replace("{", "${"),
    StoreManagement.UriComponents.GET_STORE_BY_RELATIVE_STORE_URL.replace("{relativeStoreUrl}", ValidStoreUrl))
```

Can we have an option to change the specifier in Pact JVM?

**Comment by uglyog** [comment]
I've added two system properties to change the markers of the expressions:
- `pact.expressions.start`
- `pact.expressions.end`

**Comment by uglyog** [comment]
4.1.25 released
