### ISSUE TITLE
Defining the "standalone" declaration using the PactXmlBuilder

### ISSUE THREAD

**Issue by LucasRll** [pact-foundation/pact-jvm#1414]
Hello,

while using the PactXmlBuilder I'm not able to define the XML declaration "standalone". The generated XML-Message always defines "standalone=no" which doesn't match my expected XML-Structure.

**Example**
I want to define this XML-Structure:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TestRoot>
    <Test>TestValue</Test>
</Test>
```

Using this Code:
```kotlin
return PactXmlBuilder(
                "TestRoot",
                null,
                emptyMap(),
                "1.0",
                Charsets.UTF_8.displayName()
            ).build { Test: XmlNode ->
                Test.appendElement("Test", Collections.emptyMap(), string("TestValue"))
            }
```

Which results in:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TestRoot>
    <Test>TestValue</Test>
</Test>
```

Is there a way to define the "standalone" declaration?

Best regards

**Comment by uglyog** [comment]
I've updated the builder, so you can now set it with either:

```kotlin
    PactXmlBuilder(
            "TestRoot",
            null,
            emptyMap(),
            "1.0",
            Charsets.UTF_8.displayName(),
            true
    )
```

or

```kotlin
    PactXmlBuilder("TestRoot")
        .withStandalone(true)
        .build {
```

Just note that the JVM XML implementation does not always add the attribute.

standalone == true -> `<?xml version="1.0" encoding="UTF-8"?>`
standalone == false -> `<?xml version="1.0" encoding="UTF-8" standalone="no"?>`

**Comment by uglyog** [comment]
4.1.25 released

**Comment by LucasRll** [comment]
I tried out your updates in version 4.2.10 because I needed some other fixes as well. Thanks for the fix, but as you already mentioned, in my case the standalone attribute defined "yes" wasn't added to the XML. 

So the Unit Tests won't work without further adjustments.

**Comment by parvathinakka** [comment]
<SOAP-ENV:Envelope xmlns:SOAP-ENV=http://schemas.xmlsoap.org/soap/envelope/>
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:GetStudentDetailsResponse xmlns:ns2=http://pactfloweng.jpmchase.net/beans>
            <ns2:StudentDetails>
                <ns2:id>1</ns2:id>
                <ns2:name>Adam</ns2:name>
                <ns2:passportNumber>E1234567</ns2:passportNumber>
            </ns2:StudentDetails>
        </ns2:GetStudentDetailsResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
How to achive this using PactXmlBuilder, any suggestions

**Comment by rholshausen** [comment]
@parvathinakka what have you tried?
