### ISSUE TITLE
Improve the options implementation for `ProviderInfo`

### ISSUE THREAD

**Issue by kflorence** [pact-foundation/pact-jvm#1415]
https://github.com/pact-foundation/pact-jvm/blob/ac6a0eae0b18183f6f453eafddb89b90741ace42/provider/src/main/kotlin/au/com/dius/pact/provider/ProviderInfo.kt#L82

We noticed that if you pass in an invalid option (either the key or the type), it will be silently ignored. It would be nice to either have type safety here, or some other validation that what you provide is correct before the value are forwarded on to the broker as JSON.

**Comment by uglyog** [comment]
4.1.25 released
