### ISSUE TITLE
WIP pact validation failure fails build

### ISSUE THREAD

**Issue by dimkin-eu** [pact-foundation/pact-jvm#1417]
### Steps to reproduce
- consumer adds new message contract to pact in a branch ( tagged with `B-150` )
- provider (not knowing about it) runs test against `test` env tag + wip enabled

### expected
- `test` env verification succeeds
- suite verification passes, disregarding that  wip part fails

### observed
- `test` env verification succeeds
- suite verification fails as wip part fails

### Env versions
* [pact4s](https://github.com/jbwheatley/pact4s) 0.0.16
  * "au.com.dius.pact" % "provider" % 4.2.9
* pact broker 2.81.0

```
Verifying a pact between BClient (a81e995f) and BAPI [PENDING]

  Notices:
    1) The pact at https://.../pacts/provider/BAPI/consumer/BClient/pact-version/.../metadata/... is being verified because it is a 'work in progress' pact (ie. it is the pact for the latest version of BClient tagged with 'B-510' and is still in pending state). Read more at https://docs.pact.io/go/wip
    2) This pact is in pending state for this version of BAPI because a successful verification result for a version of BAPI with tag 'master' has not yet been published. If this verification fails, it will not cause the overall build to fail. Read more at https://docs.pact.io/go/pending

  [from Pact Broker https://.../pacts/provider/BAPI/consumer/BClient/pact-version/.../metadata/...]
  b.PTState
      Verification Failed - No annotated methods were found for interaction 'b.PTState'. You need to provide a method annotated with @PactVerifyProvider("b.PTState") on the classpath that returns the message contents.

....

[info] - Verify pacts for provider `BAPI` *** FAILED ***
[info]   Verification failed:

....
[info] Run completed in 45 seconds, 688 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	BMessagesProviderPactVerifierSpec
[error] (main / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by kflorence** [comment]
That is from https://github.com/pact-foundation/pact-jvm/blob/956d9f17e3af29a185bf3f2a32e425b8b46a3538/provider/src/main/kotlin/au/com/dius/pact/provider/ProviderVerifier.kt#L332

It seems like this code path for annotated method verification ignores `pending`, if the interaction is `pending` it should not throw an exception, it should skip verification instead.

@uglyog thoughts?

**Comment by kflorence** [comment]
@dimkin-eu this might actually be a bug in `pact4s`. Perhaps we can't assume that every verification failure is a test failure: https://github.com/jbwheatley/pact4s/blob/main/shared/src/main/scala/pact4s/PactVerifyResources.scala#L37

**Comment by uglyog** [comment]
Do you need me to do anything here?

**Comment by kflorence** [comment]
@uglyog nope, I think this ticket can be closed and fixed upstream in `pact4s`
