### ISSUE TITLE
Pact-java framework encodes the url having space with a +

### ISSUE THREAD

**Issue by i050510** [pact-foundation/pact-jvm#1427]
When pact-java framework reads the interactions and sends the request to our tests, we notice that the url's are encoded.
The request section in the interaction of the pact file looks like
"request": {
        "method": "get",
        "path": "/v4/Service.svc/Test",
        "query": "$select=Id%2CCreatedAt%2CIsActionable%2CIsRead%2CNavigationTargetObject&$filter=%28IsGroupHeader%20eq%20false%29&$orderby=CreatedAt%20desc",
......
We notice that the request in TargetRequestFilter method is as below
/v4/Service.svc/Test$select=Id%2CCreatedAt%2CIsActionable%2CIsRead%2CNavigationTargetObject&$filter=%28IsGroupHeader+eq+false%29&$orderby=CreatedAt+desc

@TargetRequestFilter
	public void requestFilter(HttpRequest request) throws Exception {
		....
	}

How do we disable such url encoding.

**Comment by TimothyJones** [comment]
Both `+` and `%20` should be understood correctly as space by compliant HTTP servers. See a related discussion here: https://github.com/DiUS/pact-consumer-swift/issues/125

(although I agree that it's ideal if the values encoded in the pact are what your client actually sends)

**Comment by uglyog** [comment]
Pact-JVM uses the Apache HTTP client to make HTTP requests, and that is encoding the query parameters in that form. The query string has to be decoded when loaded from the Pact file because the HTTP client will cause it to be double encoded on the way out if not.

As @TimothyJones mentioned, encoding spaces with a `+` is valid.

**Comment by i050510** [comment]
We fixed this issue by suitably handling it at the server end.

Thanks and Regards,
Ramya
