### ISSUE TITLE
Set "String" as a response body instead of PactDslJsonBody

### ISSUE THREAD

**Issue by DmitriyDmitruk** [pact-foundation/pact-jvm#1441]
Do the Pact JVM has something like PactDslStringBody ?
My response return body as a String but not as JSON object.
How to set "String" as a response body instead of PactDslJsonBody ?

![Screenshot_118](https://user-images.githubusercontent.com/17577713/133439753-8ae6ef14-1490-4814-9a24-e23dc69d2b8b.jpg)

**Comment by uglyog** [comment]
```java
builder
      .path("/path")
      .method("GET")
      .willRespondWith()
      .status(200)
      .body("String Value", "text/plain")
      .toPact()
```
