### ISSUE TITLE
add ignore option for pact-jvm can-i-deploy

### ISSUE THREAD

**Issue by bawoodruff** [pact-foundation/pact-jvm#1444]
The pact-broker CLI offers this ignore option -- I would like to filter providers through a similar mechanism with the pact-jvm maven plugin:

```
      [--ignore=IGNORE]                    
              # The pacticipant name to ignore. Use once for each pacticipant
                being ignored. A specific version can be ignored by also
                specifying a --version after the pacticipant name option.
```

**Comment by uglyog** [comment]
I've added the ignore options, but I'm unsure how Maven will map system properties to a repeated Mojo parameter. I assume it will be something like  `-Dignore.name=one -Dignore.version=123 -Dignore.name=two`. You'll need to play around with them to work that out.

**Comment by uglyog** [comment]
No, that doesn't work

**Comment by uglyog** [comment]
Maven only supports comma separated values for system properties mapped to collections. I managed to get ` pact:can-i-deploy -Dpacticipant='Animal Profile Service' -Dlatest=true -Dignore=bob:100,fred` to set ` ignore = [IgnoreSelector(name=bob, version=100), IgnoreSelector(name=fred, version=null)]`

I'll update the docs with the format required for that parameter.

**Comment by uglyog** [comment]
4.1.28/4.2.13 is released
