### ISSUE TITLE
Please use semantic versioning!

### ISSUE THREAD

**Issue by jens-meiss** [pact-foundation/pact-jvm#1450]
hi, since a few release you do one breaking api change after the next in PATCH version. is it possible for you to make breaking changes in MINOR version only? 

please re-read the https://semver.org/ documentation and stick to the system. it is quiet annoying to have breaking changes in PATCH versions.

**Comment by TimothyJones** [comment]
I don't maintain pact-jvm, but I think the linked semver documentation says that breaking changes are for major version bumps, not minor:

> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards compatible manner, and
> 3. PATCH version when you make backwards compatible bug fixes.

(I don't know if Maven has an explicit convention for semver - a quick google lead me to [this](https://maven.apache.org/pom.html#Version_Order_Specification) which suggests that they expect to be largely but not wholly semver-compatible- at least where it comes to version selectors).

However, I do agree that some convention regarding breaking changes and version numbers is very useful for consumers, and I do think that semver is becoming more and more of a standard.

**Comment by uglyog** [comment]
@jens-meiss could you kindly piss off to what ever dismal hole you crawled out of. I'm not going to re-read some stupid specification.

Seriously, you are complaining about software you use for free built on other people's spare time, and you couldn't even bother to indicate how you were impacted or what the breaking change was.

The semver spec will not help with unintentional breakages. I would normally apologise, but in this instance I thing you deserve any inconvenience you got.

**Comment by jens-meiss** [comment]
@uglyog thanks, i already got what i wantet, your attentation about your development process. as you already noticed it is a free to use framework, so other people use it to improve theire development processes, but since you make one breacking change in each new patch release the acceptance of this framework, especially in big projects with more than 100 developers, gets lower and lower and people start looking around for other solutions ... 

semver is nothing new, it is standard in maven sind more than 15 years, i'm wonder that it seems that you never understood maven versions ... but that makes it more clear why you make breaking changes, like moving public api methods and classes around the package structure as you like, not as it should be for a framework

**Comment by mefellows** [comment]
@jens-meiss could you please share the APIs that have broken? That will help us identify any process issues (and also others who may have experienced the same pain).
