### ISSUE TITLE
Use "all in one" endpoint to publish pacts

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-jvm#1452]
There is a new "all in one" api that can be used to publish contracts in a single call. The docs are [here](https://github.com/pact-foundation/pact_broker/blob/master/lib/pact_broker/doc/views/index/publish-contracts.markdown) 

The benefits of using this endpoint are:

* One HTTP call - no partial failures
* The notices to print to the user will tell them what they need to do next in the set up/development process (eg. add provider tests, create a webhook) etc and will help us with our product led growth approach.

The endpoint is designed to be used by a CLI, and returns a collection of notices to be printed to stdout for the user. The pact broker client uses the following colours for each notice, and it would be good to keep that the same across implementations. level https://github.com/pact-foundation/pact_broker-client/blob/2a51e37/lib/pact_broker/client/colorize_notices.rb#L21

```
case type
when "warning", "prompt" then "yellow"
when "error", "danger" then :red
when "success" then :green
else nil
end
```

**Comment by uglyog** [comment]
Released 4.3.4/4.2.19/4.1.33
