### ISSUE TITLE
Add support for publishing pacts with branches

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-jvm#1453]
* Add user facing option to pact publishing interfaces to support a "branch" property
* Call the Broker API to set the branch for the version in one of the following ways:
  * Quick and dirty hack - add yet another separate HTTP call to the pact publishing code to create the branch version.
  * The "slightly more work but better in the longer term" solution - use the new "all in one" pact publishing endpoint.

## Docs for the quick and dirty solution

* Before creating the tags, send a `PUT` using the `pb:pacticipant-branch-version` relation from the index with params `pacticipant`, `branch` and `version`.
* If the branch is set, and the broker does not support branches (ie. the relations are not there), raise an appropriate error (or print warning - which ever works best for JVM) indicating that the broker does not support branches, and they should update to Pact Broker version 2.86.0 or later for branch support.

# Docs for the long term solution

See https://github.com/pact-foundation/pact-jvm/issues/1452

**Comment by johnreilly100** [comment]
Just to be clear as it stands is there no way to set the branch though the JVM 4.3.x library?

**Comment by uglyog** [comment]
It hasn't been implemented yet

**Comment by uglyog** [comment]
Released 4.3.4/4.2.19/4.1.33
