### ISSUE TITLE
`PactMismatchesException: Unexpected Request` when sending POST request

### ISSUE THREAD

**Issue by DmitriyDmitruk** [pact-foundation/pact-jvm#1458]
**When I'm changing method from GET to POST**
![Screenshot_155](https://user-images.githubusercontent.com/17577713/135827380-377e6709-5392-47f6-8eef-ef793e3d8cb0.jpg)

I'm getting `PactMismatchesException: Unexpected Request`
![Screenshot_157](https://user-images.githubusercontent.com/17577713/135827960-60712ce0-4584-45a6-b160-870a13305982.jpg)

Why exception contains method GET if I set POST?

**Comment by dimkin-eu** [comment]
you must change line 48 also

**Comment by DmitriyDmitruk** [comment]
My mistake. Thank you!
