### ISSUE TITLE
Wrong pending status resolving while WIP pacts feature enabled. 

### ISSUE THREAD

**Issue by danilchican** [pact-foundation/pact-jvm#1462]
Used JVM lib version: au.com.dius.pact.provider:junit5:4.2.13
Pact Broker version: 2.79.0

Our team has faced with the issue regarding WIP pacts.

**What we have before introducing WIP (Provider CI pipeline):**
Our pull-request **Provider** CI pipeline has step related to verification for Consumer "prod" contracts against current provider branch/tag (master, develop, feature branch).
Example: you created PR in Provider repo. Our Provider CI pipeline will run contracts verification against contracts resolved by using following command params:
-Dpact.provider.tag=feature1/description 
-Dpact.provider.version=1.1.0-{hash} 
-Dpactbroker.consumerversionselectors.tags=prod 
-Dpactbroker.consumers=Consumer1,Consumer2.

In addition to that we would like to introduce WIP pacts to be able to verify any other contracts we have against Provider PR/branch. We added two properties (pactbroker.enablePending and pactbroker.includeWipPactsSince) to enable WIP pacts. Thereafter we added another property "pactbroker.providerTags" which is responsible for setting up tags list for published verification results (required for WIP). We expect that in addition to "prod" contracts there will be **pending** pacts which will be verified additionally. 

So the parameters become looking like:
-Dpact.provider.tag=feature1/description 
-Dpact.provider.version=1.1.0-{hash} 
-Dpactbroker.consumerversionselectors.tags=prod 
-Dpactbroker.consumers=Consumer1,Consumer2.
**-Dpactbroker.enablePending=true 
-Dpactbroker.includeWipPactsSince=2021-09-14
-Dpactbroker.providerTags=feature1/description**

**Expected:**
The Provider in PR got verified against Consumer contracts marked as "prod" and in case it doesn't fulfill them the validation fails. Any WIP contracts detected in specified time range got verified but does not affect verification results (build).

**Actual:**
The Consumer's "prod" contracts resolved in context of Provider's PR, marked as pending and does not fail build in case of unsuccessful verification result.

From my understanding it contradicts to the [Pact docs statement](https://docs.pact.io/pact_broker/advanced_topics/pending_pacts/#how-it-is-calculated) below:
_A pact's content is pending for all branches of a provider **until** the **first successful verification** has been **published**. From then on, it is no longer pending for the provider branch that published the successful verification, and **will not be pending for any other new provider branches created thereafter**. It will stay in pending for branches that already existed at the time of the successful verification._

Is it expected behavior or it's a bug? 
Thank you in advance!

**Comment by mefellows** [comment]
I don't know how those properties map to the JVM runtime, so I won't comment there. But could you please share the full communication logs with the pact broker? That will help with any investigation to see what is actually sent to the broker, and what the broker thinks is pending or not.

**Comment by danilchican** [comment]
@bethesque , as I see for the newest version of Pact Broker everything works fine:)
Thanks!
