### ISSUE TITLE
WIP pacts cannot be disabled through default "pactbroker.enablePending" property for the newest Pact Broker.

### ISSUE THREAD

**Issue by danilchican** [pact-foundation/pact-jvm#1475]
Pact Broker java version used: `au.com.dius.pact.provider:junit5:4.2.13`
Pact Broker version: `2.88.0`

Our team has faced with the issue regarding disabling WIP pacts for the newest Pact Broker. For the `2.79.0` it worked fine.

In the JVM lib there is a default property `pactbroker.enablePending` to disable or enable WIP pacts while working with Pact Broker.

But passing this property with the value "false" it also includes WIP pacts.
Is it a but or it was fixed in a newest version of JVM lib?

**Comment by mefellows** [comment]
I believe it was fixed in `4.2.14` .

**Comment by danilchican** [comment]
@mefellows , it was fixed. right. thanks!
