### ISSUE TITLE
Is there a way to map an attribute only if its value is not null?

### ISSUE THREAD

**Issue by wedla** [pact-foundation/pact-jvm#1476]
Hello, guys! I've been reading the docs, and I came to this [page](https://docs.pact.io/faq/#why-is-there-no-support-for-specifying-optional-attributes), in which it's described that there's no support for optional attributes, but I don't know for certain if my doubt falls in the same scenario.

Here we go: I'm testing some failures cases. In some cases, it's returned an attribute called "path", in others it is not returned. I searched a way in the docs to code it elegantly, but I didn't find anything that could help me. Now, I'm doing this:

```
if (answer.getDetails().getPath() != null) {
    pactBuilder = pactBuilder
	.object("details")
		.stringValue("code", answer.getCode())
		.stringValue("message", answer.getMessage())
		.stringValue("path", answer.getPath());
} else {
    pactBuilder = pactBuilder
	.object("details")
		.stringValue("code", answer.getCode())
		.stringValue("message", answer.getMessage());
}
```

What I really wanted was something like that:

```
pactBuilder = pactBuilder
	.object("details")
		.stringValue("code", answer.getCode())
		.stringValue("message", answer.getMessage());
if (answer.getDetails().getPath() != null) {
    	pactBuilder
               .getObject()
                 .stringValue("path", answer.getPath());
} 
```

Where .getObject() doesn't really exist, but I'm putting it here just for the example. Is there a way that I can do this that I want?

**Comment by uglyog** [comment]
You should have two different tests, one for when the path is set and the other when it is not.

**Comment by wedla** [comment]
@uglyog Hello, Ronald, thank you for your answer! Actually, I have different tests, as you suggested, but I use the same method for mapping the returned values, since they are similar but for one field (path). So I was looking for a way to code it elegantly, without putting the if and else.

**Comment by uglyog** [comment]
Ah! No, I don't think there is a way to do that without an if statement.

**Comment by wedla** [comment]
Thank you again, Ronald! And have a great weak! I'm closing the issue.
