### ISSUE TITLE
Regression: No `ParameterResolver` registered for `org.apache.http.HttpRequest`

### ISSUE THREAD

**Issue by knutwannheden** [pact-foundation/pact-jvm#1481]
We are currently testing the new 4.3.0 release and discovered a regression in the JUnit 5 integration: There is no longer a `ParameterResolver` registered for the `org.apache.http.HttpRequest` type. Thus a test method can no longer declare a `HttpRequest` parameter as [described in the documentation](https://github.com/pact-foundation/pact-jvm/blob/d543ca426507e153c327e90fc22e00670ad0e247/provider/junit5/README.md?plain=1#L131-L153):
```java
    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void testTemplate(PactVerificationContext context, HttpRequest request) {
      // This will add a header to the request
      request.addHeader("X-Auth-Token", "1234");
      context.verifyInteraction();
    }
```

Looking at [the history](https://github.com/pact-foundation/pact-jvm/commit/af77e44abc046120c0629a5d9bdb96fe5eaf5897#diff-07611175e9acc9590c7cb10053bba9fd740f13c506778a303ea015635d9fa15c) it looks like this would work if the parameter were declared as of type `ClassicHttpRequest`, but this is a subtype of `HttpRequest` and I assume this was refactored by accident.

**Comment by uglyog** [comment]
With 4.3.0 the Apache HTTP client has been upgraded to 5, which has different interfaces and classes. `HttpRequest` is now an interface that does not have any methods to get the request/response bodies. `ClassicHttpRequest` provides the same interface as the previous version.

But as you probably only need to use it to set headers, supporting it makes sense.

**Comment by uglyog** [comment]
Just a note that the new interface is now `org.apache.hc.core5.http.HttpRequest` not `org.apache.http.HttpRequest`

**Comment by knutwannheden** [comment]
I see. Thanks for the feedback. So possibly all that is needed is a documentation update and a migration guide.

**Comment by uglyog** [comment]
Migration doc is there already https://github.com/pact-foundation/pact-jvm/blob/master/upgrade-to-4.3.x.md, I'll update the docs.

**Comment by uglyog** [comment]
4.3.1 released which will allow you to use `HttpRequest`

**Comment by knutwannheden** [comment]
Thanks!
