### ISSUE TITLE
How to solve generated matcher?

### ISSUE THREAD

**Issue by SergeyPirogov** [pact-foundation/pact-jvm#1496]
Hello,

I have a problem matching requests. I have a POST request with body:

```
[
  {
    "id": "1bffa18a-c2ed-4bce-9e50-3788834ea014",
    "params": {
      "resource": {
        "id": "0"
      },
      "host": null
    }
  }
]
```
Id here is autogenerated uuid.

I can not find a way to say PACT to ignore values for this filed during request matching. Now I am getting an error

```
org.springframework.web.client.HttpServerErrorException$InternalServerError: 
500 Internal Server Error: [{ "error": "Unexpected request :
```

How can I solve this?

**Comment by mefellows** [comment]
You would normally use a matcher: https://docs.pact.io/implementation_guides/jvm/consumer#dsl-matching-methods

I'd take a look at the workshops on docs.pact.io to get an idea of some of these basics.

**Comment by SergeyPirogov** [comment]
@mefellows ok, how to use it with java? I can not find any examples

**Comment by mefellows** [comment]
See the workshops here: https://docs.pact.io/implementation_guides/workshops/

Here are some example projects on Pactflow, and there are samples inside of this repository also: https://docs.pactflow.io/docs/examples/

**Comment by SergeyPirogov** [comment]
@mefellows I've passed these workshops, but there is no example of usage for matchers

**Comment by mefellows** [comment]
This is an example user of a matcher: https://github.com/pact-foundation/pact-workshop-jvm-spring/blob/step3/consumer/src/test/java/au/com/dius/pactworkshop/consumer/ProductConsumerPactTest.java#L37

It's on a response body, but can be used on the request also.

**Comment by SergeyPirogov** [comment]
@mefellows Thank you very much!

**Comment by mefellows** [comment]
🎄
