### ISSUE TITLE
PactFolder doesn't use expression Language to be parameterized as PactBroker does

### ISSUE THREAD

**Issue by fragonib** [pact-foundation/pact-jvm#1500]
`PactBrokerLoader` allows externalizing parameters using Expression Language 

```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@PactSource(PactBrokerLoader.class)
@Inherited
public @interface PactBroker {
  /**
   * @return URL of pact broker
   */
  String url() default "${pactbroker.url:}";
```

But `PactFolderLoader` doesn't have this option. 

```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@PactSource(PactFolderLoader.class)
@Inherited
public @interface PactFolder {
    /**
     * @return path to subfolder of project resource folder with pact
     */
    String value();
}

```

Do you find interesting to have a PR with a little modification that changes `PactFolderLoader` behaviour to allow same way of externalization? 

I can write that PR if you find it useful

**Comment by uglyog** [comment]
PRs are always welcome

**Comment by fragonib** [comment]
https://github.com/pact-foundation/pact-jvm/pull/1502
