### ISSUE TITLE
Provider JVM client library @VersionSelector branch option

### ISSUE THREAD

**Issue by johnreilly100** [pact-foundation/pact-jvm#1505]
version 4.3.4

Aa far as I can tell there is no way to select a specific branch with the `@VersionSelector` annotation under the `@PactBroker` one.
Is this the case or is there another way to select a specific consumer branch.

**Comment by uglyog** [comment]
Duplicate of #1465

**Comment by uglyog** [comment]
Just a note that the selectors can be overridden by supplying the raw JSON: #1471
