### ISSUE TITLE
Where is the scalasupport folder gone?

### ISSUE THREAD

**Issue by saeltz** [pact-foundation/pact-jvm#1508]
On November 12th [after this commit](https://github.com/pact-foundation/pact-jvm/blob/2257dfd699b0a778a7dd0f7f4402177caaf6008b/provider) the folder still exists. [After the very next commit](https://github.com/pact-foundation/pact-jvm/blob/6f7522ce62926989f239c43f3eae00b0230b6d6b/provider) it is gone and it wasn't deleted or moved in that commit. What happened?

One of the dependencies in the scala plugin are outdated and I wanted to update it but cannot find it.

**Comment by uglyog** [comment]
Scala support has been removed from Pact-JVM in favor of using https://github.com/jbwheatley/pact4s which has much better support for Scala.
