### ISSUE TITLE
A way to fail build when new pact published? Using can-i-deploy or otherwise

### ISSUE THREAD

**Issue by brettjames250** [pact-foundation/pact-jvm#1515]
I am trying to figure out a way stop a maven build when a new and unverified pact is published from the consumer, even if a previous version has been verified by the provider. Currently when using the can-i-deploy goal, it appears a build will be allowed to complete successfully as long a previous version has been verified, as per this doc - https://docs.pact.io/pact_broker/can_i_deploy/

Appreciate this may be trying to do something that can-i-deploy is not intended for. Is there a way this can be implemented using can-i-deploy, or any other method?

Java version : 8

Pact library
```xml
<dependency>
            <groupId>au.com.dius.pact.consumer</groupId>
            <artifactId>junit5</artifactId>
            <version>4.1.17</version>
            <scope>test</scope>
        </dependency>
```

Pact plugin
```xml
<plugin>
                <groupId>au.com.dius.pact.provider</groupId>
                <artifactId>maven</artifactId>
                <version>4.1.33</version>
                <configuration>
                    <pactBrokerUrl>${pact-broker.url}</pactBrokerUrl>
                    <projectVersion>${revision}</projectVersion>
                    <pacticipant>provider-service</pacticipant>
                    <latest>true</latest>
                    <to>PROD</to>
                </configuration>
                <executions>
                    <execution>
                        <id>publish</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>publish</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>can-i-deploy</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>can-i-deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Consumer pact with one integration
```java
import au.com.dius.pact.consumer.MockServer;
import au.com.dius.pact.consumer.dsl.PactDslJsonBody;
import au.com.dius.pact.consumer.dsl.PactDslWithProvider;
import au.com.dius.pact.consumer.junit5.PactConsumerTestExt;
import au.com.dius.pact.consumer.junit5.PactTestFor;
import au.com.dius.pact.core.model.RequestResponsePact;
import au.com.dius.pact.core.model.annotations.Pact;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.specification.RequestSpecification;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.equalTo;

@ExtendWith(PactConsumerTestExt.class)
public class PactConsumerTest {

    private final String GET_USER_RESPONSE_PATH = "src/test/resources/pact_responses/get_user_response.json";
    private static final Map<String, String> reqHeaders = new HashMap<String, String>() {{
        put("Content-Type", "application/json");
    }};
    private static final Map<String, String> responseHeaders = new HashMap<String, String>() {{
        put("Content-Type", "application/json;charset=UTF-8");
    }};

    @Pact(provider = "provider-service", consumer = "consumer-service")
    public RequestResponsePact getUser(PactDslWithProvider builder) {

        return builder
                .given("valid user received from provider")
                .uponReceiving("valid user from provider")
                .method("GET")
                .headers(reqHeaders)
                .path()
                .willRespondWith()
                .status(200)
                .headers(responseHeaders)
                .body(new PactDslJsonBody()
                        .numberValue("userId", 1)
                        .stringValue("userForename", "User")
                        .stringValue("userSurname", "User")
                )
                .toPact();
    }

    @Test
    @PactTestFor(providerName = "provider-service", pactMethod = "getUser")
    public void getUserPact(MockServer mockServer) {

        JsonPath expectedResponse = new JsonPath(new File(GET_USER_RESPONSE_PATH));

        RestAssured.baseURI = mockServer.getUrl();
        RequestSpecification rq = RestAssured
                .given()
                .headers(responseHeaders)
                .when();

        rq.get(mockServer.getUrl()).then()
                .assertThat()
                .statusCode(200)
                .body("", equalTo(expectedResponse.getMap("")));
    }

}
```
When publishing a new version of the contract to the Pact broker, the status is updated to unverified. Message below when hovering over unverified pact in broker
"**_Pact from branch master has changed since last successful verification by provider service(1.0.0)_**"

At the next maven build, the can-i-deploy goal still returns true

```
[INFO] --- maven:4.1.33:can-i-deploy (default-cli) @ consumer-service ---
[WARNING] The POM for org.slf4j:slf4j-api:jar:1.7.25 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
Computer says yes \o/
```

**Comment by mefellows** [comment]
> Currently when using the can-i-deploy goal, it appears a build will be allowed to complete successfully as long a previous version has been verified

No, this is incorrect. Or at the very least is misleading. 

`can-i-deploy` can be used in multiple scenarios. The standard one (using your inputs from above) is to say `can-i-deploy --application provider-service --version ${revision} --to PROD` which says "Find all consumers of provider-service currently tagged 'PROD', and make sure version ${revision} of provider-service is compatible with them". 

In your case, `can-i-deploy` should pass, because the latest version of the consumer _in production_ is compatible. It sounds like only the latest version tagged _master_ is not compatible (this is an assumption based on above, please correct me if that's not the case). 

This case should be checked by a usual provider verification which would check the `master` tag, and would presumably fail if it's not compatible.

`can-i-deploy` is also supposed to be used by consumers, so:

1. If the provider hasn't verified the latest `master` (as per above)
2. The consumer calls `can-i-deploy` similar to above

They should not be allowed to release, and therefore will need to wait for a valid provider verification before they can continue.

You might also find [this workshop](https://docs.pactflow.io/docs/workshops/ci-cd/) helpful in understanding how to gate releases with `can-i-deploy`.

**Comment by brettjames250** [comment]
Thanks, this has been very helpful.

I think my main misunderstanding was using `can-i-deploy` in the consumer context, but incorrectly adding the `<pacticipant>` field/param in the plugin with the 'other'/provider service value, rather than the service I want to deploy (in this case, the consumer). So this seems to be working as expected now.

Running can-i-deploy from the **consumer**

`can-i-deploy --application consumer-service --version ${revision} --to PROD`

```xml
<plugin>
                <groupId>au.com.dius.pact.provider</groupId>
                <artifactId>maven</artifactId>
                <version>4.1.33</version>
                <configuration>
                    <pactBrokerUrl>${pact-broker.url}</pactBrokerUrl>
                    <projectVersion>${revision}</projectVersion>
                    <pacticipant>user-service-omni</pacticipant>
                    <latest>true</latest>
                    <to>PROD</to>
                </configuration>
                <executions>
                    <execution>
                        <id>publish</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>publish</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>can-i-deploy</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>can-i-deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

rather than previously I was trying the below, again from the consumer

`can-i-deploy --application provider-service --version ${revision} --to PROD`

Hopefully I've now understood this functionality correctly?

**Comment by mefellows** [comment]
Yep! That's right.

Basically, you want the consumer to worry about itself and the provider to worry about itself, and the broker will maintain all of the compatibility.
