### ISSUE TITLE
stringMatcher put generated value to contract, results in creating new versions of the contract after each run

### ISSUE THREAD

**Issue by the1stflag** [pact-foundation/pact-jvm#1517]
Hi

I would like to use the stringMatcher in a way it is not supported for now.
Currently we are using the pact without pactbroker. So we are exchanging files via filesystem and put it into version control on provider side.

We build a pact with a DSLBody the following way:

`DslPart body = new PactDslJsonBody()
                .minArrayLike("e",1)
                .stringType("somekey")
                .stringType("someCountry")
                .minArrayLike("dataConfigurationElements",1)
                .stringMatcher("fieldId","0x0\\d{9}")
                .asBody();`

Problem is that a specific value for 0x0\\d{9} will be generated and put into the pact file, not the regular expression itself.
That way, everytime we start the test and consumer side and automatically deploying on provider side the version control want to update the file.
I am not sure, but is this a problem when we switch to pactbroker that permanently new versions of the contract will be generated?

**Comment by mefellows** [comment]
Yes, if the contract is changing each time then it will publish a new version. This will mean you will always need to run provider verification before a `can-i-deploy` of the consumer will pass.

**Comment by the1stflag** [comment]
I personally hoped that the regular expression would be part of the pact file and publishing the test on consumer side will not result in a diiferent version of the file. Is this something you probably would change in the future?

**Comment by mefellows** [comment]
It's not currently the case. It might do at some point in the future. Why does the value need to change each time?

It's a unit test, so you should be able to control the value, usually.

**Comment by the1stflag** [comment]
Thats true, though I like the idea to check interface implemetation via regex on both sides more.
However in the current implementation stringMatcher() does not make much sense because the consumer permanently creates new versions of the pact without a meaningful change of the contract.
