### ISSUE TITLE
Add support for providerVersionBranches in for-verification lookups for pending and wip pacts

### ISSUE THREAD

**Issue by TGNThump** [pact-foundation/pact-jvm#1555]
Currently pact-jvm only supports providerVersionTag and not providerVersionBranches.

**Comment by praveen-em** [comment]
I was about to raise the same request.

**Comment by praveen-em** [comment]
Very keen to use this. Are you planning to do a new release with this change sometime soon?

**Comment by praveen-em** [comment]
Thanks for the new release this morning. Much appreciated.
