### ISSUE TITLE
Request to provider failed with an exception: "/" is not allowed in an identifier in path expression

### ISSUE THREAD

**Issue by topsycreed** [pact-foundation/pact-jvm#1556]
Hey!

**Steps to reproduce:**
Sent a get request to endpoint:
`Method:GET
Path:/shipping/v1
Headers:
{
    "Accept": "application/json",
    "site": "US",
    "Content-Type": "application/json"
}`
That returning response body with '/' symbols, for example:
`{
    "data": [
        {
            "relationships": {
                "user/shippingAddress": {
                    "data": {
                        "id": "123",
                        "type": "user/shipping-address"
                    }
                }
            }
        }
    ]
}`

**Actual:**
At Pact you will see exception:
`Request to provider failed with an exception: "/" is not allowed in an identifier in path expression "$.data[0].relationships.user/shippingAddress.data.id" at index 28 (au.com.dius.pact.core.model.InvalidPathExpression)`

**Expected:**
Test should be passed successfully, since it's already implemented on service end to return such response and consumers expected that.

**Comment by rholshausen** [comment]
I am not able to replicate this issue with Pact-JVM. See example tests: [Consumer](https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit5/src/test/groovy/au/com/dius/pact/consumer/junit5/PathWithValueWithSlashTest.groovy) and [Provider](https://github.com/pact-foundation/pact-jvm/blob/master/provider/junit5/src/test/groovy/au/com/dius/pact/provider/junit5/BodyWithSlashesTest.groovy)

I did notice that the pact file generated from that consumer test (see [pact](https://github.com/pact-foundation/pact-jvm/blob/master/provider/junit5/src/test/resources/pacts/Consumer-ProviderWithSlashes.json#L54)) has the slash escaped `$.data[*].relationships['user/shippingAddress'].data.id`, while the error you provided has `$.data[0].relationships.user/shippingAddress.data.id` which is not valid.

How have you generated the Pact file that was used in your test?

**Comment by topsycreed** [comment]
Hey @rholshausen thanks for your support! We were able to fix the issue from Consumer side as you mentioned.
