### ISSUE TITLE
Missing files: Multiple withFileUpload() is not supported

### ISSUE THREAD

**Issue by pmcpg** [pact-foundation/pact-jvm#1574]
Hi, as the title says if I want to build a pact on the consumer side and use multipart/form-data and withFileUpload() e.g.:

```
@Pact (...)
return builder
        .given("Post something")
        .uponReceiving("Set state for post")
        .path("path/to/resource")
        .withFileUpload("partName0", "fileName0", "form-data", someObject0)
        .withFileUpload("partName1", "fileName1", "form-data", someObject1)
        .method("POST")
        .willRespondWith()
        .status(201)
        .toPact();
(...)
```

In the resulting Pact file I just receive the form-data of just **partName1**. I guess I need to add header and body now manually. Isnt it possible to add multiple files with that method?

**Comment by Dedeepya-Kolli** [comment]
can u pls share us an example on how to use that. Want to include application/json along with image/png.

**Comment by rholshausen** [comment]
Tracking this in #1642
