### ISSUE TITLE
Question: Is pact is available with TestNG framework ?

### ISSUE THREAD

**Issue by sonu-smarsh** [pact-foundation/pact-jvm#1577]
Is pact is available with TestNG framework ? if not, Shall we expect jar for pact TestNG in near future?

**Comment by mefellows** [comment]
We don't currently support TestNg and there are no official plans to do so.

**Comment by mefellows** [comment]
For clarity, we don't have a TestNG interface like we do JUnit. You can still write pact tests in TestNG using the consumer DSL.
