### ISSUE TITLE
Question: Will the latest pact-jvm release 4.3.11 be available in maven repository?

### ISSUE THREAD

**Issue by dianaDBB** [pact-foundation/pact-jvm#1578]
The latest release [4.3.11](https://github.com/pact-foundation/pact-jvm/releases/tag/4_3_11) is not added to the [maven repository](https://mvnrepository.com/artifact/au.com.dius.pact.provider/junit5) yet.

Do you know when this will be available?

I know that the new release was only done a few hours ago, but it has a change that I really need to implement and been waiting for a time now :)

**Comment by rholshausen** [comment]
Oh, sorry, my bad. I need to click the release button in Sonatype. I'll do that now, and it sometimes then takes a few hours to propogate.

**Comment by rholshausen** [comment]
Looks like there is an issue with the release (Maven Central rules rejected it). I need to fix that and then will re-release it.

**Comment by rholshausen** [comment]
Released
