### ISSUE TITLE
Annotation @PactBrokerConsumerVersionSelectors not working?

### ISSUE THREAD

**Issue by dbro04** [pact-foundation/pact-jvm#1591]
Since 
```
@PactBroker(url="....
            consumerVersionSelectors ={
                @VersionSelector(tag = "develop")
            })

```
is deprecated.
 I tried using 
```
@PactBrokerConsumerVersionSelectors
    static SelectorBuilder consumerVersionSelectors() {
        // Select Pacts for consumers deployed to 'Dev' with main branch
        var builder= new SelectorBuilder()
                .deployedTo("Dev")
                .mainBranch();
        return builder;
```
but this doesn't deselect any consumors and on debugging the static method consumerVersionSelectors() isn't called.

**Comment by rholshausen** [comment]
Are you using the latest version of Pact-JVM?

**Comment by dbro04** [comment]
Yes. I'm using 4.3.13 and even tried 4.4.0-beta3.

**Comment by rholshausen** [comment]
Are you using JUnit 4 or 5?

**Comment by dbro04** [comment]
Junit5 using
`    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
`
for the test template

**Comment by rholshausen** [comment]
Hmm, try making the `consumerVersionSelectors` method public.

**Comment by dbro04** [comment]
Yes this was missing !
Thx!
