### ISSUE TITLE
PKIX certificate issue

### ISSUE THREAD

**Issue by Anusha7733** [pact-foundation/pact-jvm#1593]
Failed to fetch the root HAL document
09:22:54  javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
09:22:54  	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
09:22:54  	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
09:22:54  	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:301)
09:22:54  	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295)
09:22:54  	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1471)
09:22:54  	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
09:22:54  	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:936)
09:22:54  	at sun.security.ssl.Handshaker.process_record(Handshaker.java:871)
09:22:54  	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
09:22:54  	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
09:22:54  	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
09:22:54  	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
09:22:54  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
09:22:54  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
09:22:54  	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
09:22:54  	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
09:22:54  	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
09:22:54  	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
09:22:54  	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
09:22:54  	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
09:22:54  	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
09:22:54  	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
09:22:54  	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
09:22:54  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
09:22:54  	at au.com.dius.pact.core.pactbroker.HalClient$getJson$1.invoke(HalClient.kt:283)
09:22:54  	at au.com.dius.pact.core.pactbroker.HalClient$getJson$1.invoke(HalClient.kt:140)
09:22:54  	at au.com.dius.pact.core.support.KotlinLanguageSupportKt.handleWith(KotlinLanguageSupport.kt:36)
09:22:54  	at au.com.dius.pact.core.pactbroker.HalClient.getJson(HalClient.kt:278)
09:22:54  	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:242)
09:22:54  	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:237)
09:22:54  	at au.com.dius.pact.core.pactbroker.HalClient.navigate(HalClient.kt:219)
09:22:54  	at au.com.dius.pact.core.pactbroker.PactBrokerClient$Companion.uploadTags(PactBrokerClient.kt:456)
09:22:54  	at au.com.dius.pact.core.pactbroker.PactBrokerClient.uploadPactFile(PactBrokerClient.kt:249)
09:22:54  	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:636)
09:22:54  	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:237)
09:22:54  	at au.com.dius.pact.provider.gradle.PactPublishTask$_publishPacts_closure1.doCall(PactPublishTask.groovy:60)
09:22:54  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:22:54  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:22:54  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:22:54  	at java.lang.reflect.Method.invoke(Method.java:483)
09:22:54  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
09:22:54  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
09:22:54  	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
09:22:54  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
09:22:54  	at groovy.lang.Closure.call(Closure.java:411)
09:22:54  	at groovy.lang.Closure.call(Closure.java:427)
09:22:54  	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileMatch(ResourceGroovyMethods.java:1578)
09:22:54  	at org.codehaus.groovy.runtime.dgm$990.doMethodInvoke(Unknown Source)

**Comment by mefellows** [comment]
What have you tried? Please reopen once once have searched exisiting issues and have tried all of the usual items, and also provided some more detail on your setup.

**Comment by rholshausen** [comment]
Duplicate of #1236 #741
