### ISSUE TITLE
Exception using new consumer version selector method in kotlin

### ISSUE THREAD

**Issue by stefano-lucka** [pact-foundation/pact-jvm#1594]
Hi, 

I started to migrate the `@Deprecated` `consumerVersionSelectors = [ ]` in the `@PactBroker` annotation by the new way, using `@PactBrokerConsumerVersionSelectors` method like this. See bottom line: 

![image](https://user-images.githubusercontent.com/20859755/183710243-d0f99217-cf55-4eb4-9a16-85bb0af7f0ec.png)

However when running my PactTest that ran using commented-out code above, I get this exception:

![image](https://user-images.githubusercontent.com/20859755/183710445-0cc49cf1-871a-4654-bffa-718d5225dea5.png)

I debugged a bit your library and figured, that this line tries to invoke the identified `selectorsMethod` with a `testInstance` param that is `Optional.empty()` though. I find it strange that `invokeSelectorsMethod` thinks my selector method has 1 param even though it doesn't. This circumstance is explicitly handled in `testClassHasSelectorsMethod`: 

![image](https://user-images.githubusercontent.com/20859755/183710816-cf6e72ce-f2c4-4001-a330-dcfbbc7f8342.png)

* Kotlin version: 1.7.10
* Pact version: 4.3.13
* junit5: yes, `PactVerificationInvocationContextProvider`

What else I tried: 

* Moving my selector method out of abstract class and into to concrete test class 
* Making it "kotlin static" leads to not running into my breakpoint in `testClassHasSelectorsMethod` even, because its not contained in `testClass?.kotlin?.members`: 
```
companion object {
        @PactBrokerConsumerVersionSelectors
        @JvmStatic
        fun consumerVersionSelectors(): SelectorBuilder = SelectorBuilder().branch("my-branch")
    }
```

**Comment by rholshausen** [comment]
The documentation is wrong, the method needs to be public to be invoked.

**Comment by rholshausen** [comment]
Ah! You created a PR to fix the docs. What a champion!

**Comment by rholshausen** [comment]
> I find it strange that invokeSelectorsMethod thinks my selector method has 1 param even though it doesn't
Instance methods have one extra parameter, which is the `this` pointer. 

How is your actual test extending the abstract one?

**Comment by stefano-lucka** [comment]
It looks quite unspectacular to me: 
![image](https://user-images.githubusercontent.com/20859755/183832598-5713e554-e032-48d7-8c73-89cef0a3c713.png)

**Comment by rholshausen** [comment]
I need to investigate the JUnit 5 docs, because it looks like it is not providing a test class instance for your test, and I need the instance to be able to call that method on it.

**Comment by stefano-lucka** [comment]
I did a bit more experimentation about this and added `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` to my test class. I get a `testInstance` then which is of type of my test class itself (ProductPactProviderTest), but the Exception remains the same: 

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
```
![image](https://user-images.githubusercontent.com/20859755/183855156-64b6e32e-c09a-450b-9732-c715c5404ed5.png)

**Comment by stefano-lucka** [comment]
It does work if I unwrap the instance out of the Optional, however I don't know the jUnit5 extension specifics enough in order to understand why the testInstance is missing. In fact, it is already missing on very beginning in `PactVerificationInvocationContextProvider`. Here the param `context.testInstances` is null already.

**Comment by rholshausen** [comment]
For Spring tests, it is better to use `@ExtendWith(PactVerificationSpringProvider::class)`

**Comment by rholshausen** [comment]
Looks like this is the old chicken and egg problem. A test instance is created for each interaction to verify, and we need the selectors to fetch the Pacts so we can create the test instances. So when the selector method is called, there will never be a test instance.

This is why it needs to be static. The other option is to create an new instance to call with, which will work as long as the selector method does not try to use any test class instance variables. They will not be set.

**Comment by rholshausen** [comment]
I've updated the function, it will support both normal functions, abstract base classes as well as companion objects now.  See https://github.com/pact-foundation/pact-jvm/blob/master/provider/junit5/src/test/kotlin/au/com/dius/pact/provider/junit5/ConsumerVersionSelectorKotlinTest.kt

**Comment by stefano-lucka** [comment]
Awesome, thanks.

**Comment by viktorgt** [comment]
I stumbled over the same issue today, since we also migrating from tags to branches/environments. When can we expect a new release?

**Comment by stefano-lucka** [comment]
@viktorgt PACT has released the fix tonight.

**Comment by stefano-lucka** [comment]
Fix confirmed, this code works now: 

```
@PactBrokerConsumerVersionSelectors
fun consumerVersionSelectors(): SelectorBuilder = SelectorBuilder()
     .branch("main")
     .environment("prod")
     .environment("qa")
     .environment("int")
```

Thanks a lot for this fast workflow, fix released just 3 days later, that's amazing.

**Comment by mefellows** [comment]
Thanks for raising! It takes many hands :)
