### ISSUE TITLE
Matches are not allowing vertical bar "|" in name fields

### ISSUE THREAD

**Issue by YarLyashenko** [pact-foundation/pact-jvm#1596]
While validating contract which has vertical bar "|" in field name I receive an error:

```
Failures:
1) Verifying a pact between consumer and provider - a request for full quote
    1.1) "|" is not allowed in an identifier in path expression "$.vectors.LoadingPremiumLife1|amount" at index 29
```

**Comment by rholshausen** [comment]
How was this Pact created? Those values should be escaped, i.e, `$.vectors['LoadingPremiumLife1|amount']`

**Comment by YarLyashenko** [comment]
That pact was created with @pact-foundation/pact version 9.18.1

Pact created with the latest version 10.0.2 has field with escaped vertical bar, as @rholshausen have mentioned. Thanks for pointing out. I'll close the issue
