### ISSUE TITLE
Consumer version selector and enablePending

### ISSUE THREAD

**Issue by anidzgor** [pact-foundation/pact-jvm#1599]
I have the following situation:
- Consumer and provider are compatible.
- Consumer push new changes to develop branch which break compatible with provider
- Provider do some changes but not related with changes from consumer, there are some more important implementation(ex. security or others in backend)
- Provider push this changes as FB but can't succeed because of consumer changes, I try to verify with 2 things: latest develop and environment staging in the following way(I have turned on enablePending):
```
@PactBrokerConsumerVersionSelectors
public static SelectorBuilder consumerVersionSelectors() {
return new SelectorBuilder()
                        .environment(STAGING_ENVIRONMENT)
                        .branch(DEVELOP_BRANCH);
}
```
What I do wrong? When I do something like that, it is working @PactBroker(providerTags = {"staging"}) but this field isn't the old fashioned way of doing that?

**Comment by rholshausen** [comment]
You can use the `tag` method to make it the same as what you had before, i.e. 

```
@PactBrokerConsumerVersionSelectors
public static SelectorBuilder consumerVersionSelectors() {
return new SelectorBuilder()
                        .tag("staging");
}
```

To use environments and branches, you need to make sure that those have been set correct on the Pact files. See https://docs.pact.io/pact_broker/recording_deployments_and_releases#migrating-from-tags-to-deploymentsreleases
