### ISSUE TITLE
Cant expect an empty body on the consumer side

### ISSUE THREAD

**Issue by TorbenSp09** [pact-foundation/pact-jvm#1611]
Hey,

iam not able to expect an empty body on the consumer side when creating the contract. First my code was:

![image](https://user-images.githubusercontent.com/84403716/191787919-e6bccd4d-fe89-4481-a652-ec6a3d377fcd.png)

I already read that there is a difference between expecting an empty body and not caring about the body [here](https://github.com/pact-foundation/pact-js/issues/177) as there was an issue for JavaScript. 

So i changed my code to:

![image](https://user-images.githubusercontent.com/84403716/191788144-2af00a93-c2ea-4a22-ba53-db3a67a5c01e.png)

But the generated contract is still the same without the body property, which will lead to not caring about the body:

![image](https://user-images.githubusercontent.com/84403716/191788290-6c88eea1-f453-4e66-b453-7d370dcdb76e.png)

The expected behaviour would be that there is an emtpy body expected in the response. ("body": "")

Is there anything iam missing out or is this a bug? Iam using version 4.3.14 of pact with Java version 16.0.1.

**Comment by rholshausen** [comment]
Fix released with version 4.3.16
