### ISSUE TITLE
Passing Consumer and PRovider name as Environment variable

### ISSUE THREAD

**Issue by galaxy79** [pact-foundation/pact-jvm#1616]
I'm using the pact-jvm to write the contract test and want to pass the consumer and provider names from the environment variable. I dont see that option on the Consumer annotation and want to check if there is a way to do it.

In our CI , we use a yaml file where we include the consumer and provider names. The reasoning behind this approach is to restrict who can use contract test  and ensure pactipant is onboarded first before publishing it directly from the CI.
I do see an issue raised related to this in 2017 and want to know if this is fixed [#528](https://github.com/pact-foundation/pact-jvm/issues/528)

**Comment by rholshausen** [comment]
Fix released with version 4.3.16
