### ISSUE TITLE
can-i-deploy to ignore PACT  unverified contract from a new Producer.

### ISSUE THREAD

**Issue by AlkaDitta** [pact-foundation/pact-jvm#1654]
I am trying to figure out a way stop a build  to fails when a new and unverified pact is published from the consumer but the provider is still working on implementing PACT.
Details of the scenario I am facing.
We have a new PACT setup b/w a consumer and provider . The consumer side of work is done and the contract can be published in Pactflow. However provider is still working on their PACT implementation.
However on the consumer  PACT contracts with other Providers in Pactflow and we user canIDeploy as a step in the consumer build process.
If I publish  the new unverified contract b/w consumer and new provider , the canIDeploy fails , with  There is no verified pact  .
How can I ignore a particular  provider i, so that canIDeploy does not refer to it

**Comment by rholshausen** [comment]
I would just disable the ca-i-deploy step in the consumer pipeline until the provider team is ready
