### ISSUE TITLE
Release `4.5.0` has no plugin descriptor for Maven Provider plugin

### ISSUE THREAD

**Issue by Harmelodic** [pact-foundation/pact-jvm#1672]
When attempting to run Pact tests with the new `4.5.0` release, I get the following error:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.601 s
[INFO] Finished at: 2023-02-24T07:58:44Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to parse plugin descriptor for au.com.dius.pact.provider:maven:4.5.0 (/home/runner/.m2/repository/au/com/dius/pact/provider/maven/4.5.0/maven-4.5.0.jar): No plugin descriptor found at META-INF/maven/plugin.xml -> [Help 1]
```

[Link to example build job](https://github.com/Harmelodic/init-microservice/actions/runs/4260455393/jobs/7413654135).

I'm guessing something wasn't packaged inside of the released JAR that was supposed to be?

**Comment by robert-zimmermann** [comment]
I also observed the same thing

**Comment by gertjanschouten** [comment]
Yep, here too. Our CI fails because of this, so we have to stick with 4.4.7 for now.

**Comment by rholshausen** [comment]
4.5.1 has been released with the fix

**Comment by Harmelodic** [comment]
Build succeeds with `4.5.1`.
https://github.com/Harmelodic/init-microservice/actions/runs/4311749636/jobs/7521471550

Closing issue.
