### ISSUE TITLE
Set mock ports for multiple providers?

### ISSUE THREAD

**Issue by edeandrea** [pact-foundation/pact-jvm#1675]
This question was [also asked on StackOverflow by someone else](https://stackoverflow.com/questions/74942016/setting-mock-ports-for-multiple-providers-in-pact-jvm) but has yet to receive a response. 

In my case I am not using Spring (as that previous entry on StackOverflow is) but I have the same problem: I have a single business method which calls 2 providers. Each provider is statically configured in the application configuration. Injecting a `MockServer` into the test method doesn't help because the framework itself creates the client implementation (see https://quarkus.io/guides/rest-client-reactive#create-the-interface). The URL for the client is configured at the application level, so the ports of both mock servers need to be known statically before the test class is even created.

Separating into 2 separate tests for each provider is impossible. What we need is either

1. A single mock server instance on a single port that can handle multiple providers using context path root to differentiate between providers.
2. A way to statically configure in the `@PactTestFor` annotation the ability to specify a port per provider.

In my particular case for this exact problem, a single mock server would work because both providers have different context paths that get called. But generically, that may not work for all use cases.

**Comment by rholshausen** [comment]
I've added support for multiple @MockServerConfig annotations, so you can now do
```java
@ExtendWith(PactConsumerTestExt.class)
@MockServerConfig(providerName = "provider1", port = "1234")
@MockServerConfig(providerName = "provider2", port = "1235")
class MultiProviderWithStaticPortsTest {
```

The provider names must match the ones used to setup the Pacts. See https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit5/src/test/java/au/com/dius/pact/consumer/junit5/MultiProviderWithStaticPortsTest.java#L26

**Comment by edeandrea** [comment]
That's awesome! Thank you!

**Comment by edeandrea** [comment]
Closed in https://github.com/pact-foundation/pact-jvm/commit/67a66702496daa52ba060e3c68abe68deaff524a
