### ISSUE TITLE
Pact DSL throws NPE when setting an stringType with example set to `null`

### ISSUE THREAD

**Issue by iekdosha** [pact-foundation/pact-jvm#1679]
I am using consumer version 4.4.7.

Running this code:
```
String value = null;
new PactDslJsonBody()
      .stringType("myField", value)
```

will produce NPE:
```
java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "examples[0]" is null
```

It looks like in file `PactDslJsonBody.kt` method `fun stringType(name: String, vararg examples: String): PactDslJsonBody`  there is not null check before accessing the value:
```
is JsonValue.Object -> body.add(name, JsonValue.StringValue(examples[0].toCharArray()))
```

**Comment by rholshausen** [comment]
I've updated the DSL to throw `IllegalArgumentException` instead of `NullPointerException`
