### ISSUE TITLE
Latest version 4.5.3 released but not in maven central

### ISSUE THREAD

**Issue by fleboulch** [pact-foundation/pact-jvm#1680]
Is there an issue publishing the version 4.5.3 to maven central?

**Comment by rholshausen** [comment]
It can take a few hours for the new files to propagate to the indexes, but it looks like they are there now.

![image](https://user-images.githubusercontent.com/38309842/225575697-b8d3473d-c7b6-4d22-a8d7-32c952ca90a2.png)

**Comment by fleboulch** [comment]
Thanks for the info. I'm closing it
