### ISSUE TITLE
Question: Default fallback tag if branch name of pacticipants are equal?

### ISSUE THREAD

**Issue by MahatmaFatalError** [pact-foundation/pact-jvm#1682]
I specified the following version selector: `@PactBroker(url = "${pactBrokerHost}", consumerVersionSelectors = @VersionSelector(tag = "${PACT_TAGS}"))` while `PACT_TAGS` are "dev,stage,prod" for my ProviderTest.

Coincidentally, the branch name (and tag name) of both provider and consumer were identical. 

In the logs of the provider tests I saw that the consumer version with the tag name of the own provider branch was tested. This surprised me because it was not specified in PACT_TAGS and also no fallbackTag was specified.

Is this behavior intended? How can it be disabled?

**Comment by rholshausen** [comment]
I don't think the `consumerVersionSelectors` support comma-separated values, they need to be individual selectors. i.e.,
```
@PactBroker(url = "${pactBrokerHost}", consumerVersionSelectors = {
    @VersionSelector(tag = "dev"),
    @VersionSelector(tag = "stage"),
    @VersionSelector(tag = "prod")
})
```
