### ISSUE TITLE
plugin version higher than 4.3.19 throws exception

### ISSUE THREAD

**Issue by wmunyan** [pact-foundation/pact-jvm#1686]
I am using gradle with the following plugins section:
```
plugins {
   ...
   id "au.com.dius.pact" version "4.3.19"
```
and some test dependencies:
```
testImplementation group: 'au.com.dius.pact', name: 'consumer', version: '4.3.19'
testImplementation group: 'au.com.dius.pact', name: 'provider', version: '4.3.19'

testImplementation 'au.com.dius:pact-jvm-provider-gradle:4.0.10'
testImplementation 'au.com.dius:pact-jvm-consumer-junit:4.0.10'
```

However, if I try to use any version higher than `4.3.19`, executing any gradle tasks fails with the following error:
```
Cannot invoke "org.gradle.api.artifacts.VersionConstraint.getRequiredVersion()" because "cst" is null
```
It looks as though I am using gradle `7.4.2`, if that helps.  Thanks for any help!

**Comment by rholshausen** [comment]
Don't mix major Pact-JVM versions. You're using both `4.3.19` and `4.0.10`.

**Comment by wmunyan** [comment]
The highest available version of `au.com.dius:pact-jvm-consumer-junit` is `4.0.10` per https://mvnrepository.com/artifact/au.com.dius/pact-jvm-consumer-junit

The highest available version of `au.com.dius:pact-jvm-provider-gradle` is `4.0.10` per https://mvnrepository.com/artifact/au.com.dius/pact-jvm-provider-gradle

**Comment by rholshausen** [comment]
Use `au.com.dius.pact.consumer:junit:4.3.19` and `au.com.dius.pact.provider:gradle:4.3.19`

**Comment by ealesjordan** [comment]
I get the same issue when I have no pact dependencies added in. 

Attempting with gradle plugin version `4.6.1` and gradle version `7.4.2`.

--------------------------------------------------------------------------

However, if I roll back the pact gradle plugin and add the latest dependencies like this:

```
plugins {
    ...
    id 'au.com.dius.pact' version '4.3.12'
}
```

And try to include these dependencies:

```
{
    ...
    testImplementation 'au.com.dius.pact.provider:junit5spring:4.6.1'
    testImplementation 'au.com.dius.pact.consumer:junit5:4.6.1'
}
```

I get this exception for both of the dependencies: 

```
 Cannot invoke "org.gradle.api.artifacts.VersionConstraint.getRequiredVersion()" because "cst" is null
```

**Comment by rholshausen** [comment]
These must be the same: 
![image](https://github.com/pact-foundation/pact-jvm/assets/38309842/b693e20e-c774-4529-bb6d-0331d434ee35)
