### ISSUE TITLE
Is RestPactRunner compatible with V4Pact?

### ISSUE THREAD

**Issue by metteo** [pact-foundation/pact-jvm#1692]
Hi

Asking here instead of SO because it seems to be a bug / omission. 

I have a situation where consumer is publishing a V4Pact in pactflow. 
Provider test is fetching it correctly (under debugger) but then [PactRestRunner](https://github.com/pact-foundation/pact-jvm/blob/master/provider/junit/src/main/kotlin/au/com/dius/pact/provider/junit/RestPactRunner.kt#L10) filters it out because it's not an instance of `RequestResponsePact`... 

I'm wondering if that filtering expression should include `|| pact.isRequestReponsePact()` and some conversion logic (`pact.asRequestResponsePact()`) down the line.

I'm using pact-jvm 4.3.x which is marked as unsupported, but PactRestRunner was not touched since 2020..

**Comment by metteo** [comment]
I have overridden filtering method and included above condition / conversion logic. I can confirm it works for executing the tests. Not sure about publishing the verifications, will report tomorrow.

**Comment by rholshausen** [comment]
Support was only added for JUnit 5. None of the JUnit 4 code has been touched.
