### ISSUE TITLE
Clarification needed about the use of @PactBroker annotation

### ISSUE THREAD

**Issue by neillfontes-klar** [pact-foundation/pact-jvm#1695]
Hi, I have a very simple question which couldn't be answered by the documentation. 

Is it possible to upload new contracts to the Pact Broker via the `@PactBroker` annotation in a **Consumer** test? Or the only means to do so are via `mvn pact:publish` on CI/Manual Maven run? 

If not - then is the `@PactBroker` meant **to be only used by Provider tests** to pull the specified contracts for validation?

**Comment by rholshausen** [comment]
Yes, `@PactBroker` annotation is for provider tests
