### ISSUE TITLE
Gradle task errors: cannot determine module name

### ISSUE THREAD

**Issue by michalwilk96** [pact-foundation/pact-jvm#1696]
Hello,
I've implemented contract tests using 'au.com.dius.pact.consumer:junit5:4.6.0'.
To build, publish contracts I'm using gradle plugin id 'au.com.dius.pact' version "4.6.0".
To verify contracts and write implementation on provider side I'm using: 'au.com.dius.pact.provider:spring6:4.6.0'.
I'm also using Java modules.

In both cases (during product build) I'm getting following errors: 
`error: cannot determine module name for /Users/me/.gradle/caches/modules-2/files-2.1/au.com.dius.pact.consumer/junit5/4.6.0/d19/junit5-4.6.0.jar
error: cannot determine module name for /Users/me/.gradle/caches/modules-2/files-2.1/au.com.dius.pact/consumer/4.6.0/1fe/consumer-4.6.0.jar
error: cannot determine module name for /Users/me/.gradle/caches/modules-2/files-2.1/au.com.dius.pact.core/matchers/4.6.0/10/matchers-4.6.0.jar
error: cannot determine module name for /Users/me/.gradle/caches/modules-2/files-2.1/au.com.dius.pact.core/model/4.6.0/a317/model-4.6.0.jar
error: cannot determine module name for /Users/me/.gradle/caches/modules-2/files-2.1/au.com.dius.pact.core/pactbroker/4.6.0/98f7/pactbroker-4.6.0.jar
error: cannot determine module name for /Users/me/.gradle/caches/modules-2/files-2.1/au.com.dius.pact.core/support/4.6.0/98c/support-4.6.0.jar
`
Thank you for the help.

**Comment by rholshausen** [comment]
What version of Gradle are you using? Also, can you try 4.6.1?

**Comment by michalwilk96** [comment]
Issue resolved in version 4.6.1.
Thanks
