### ISSUE TITLE
Error in installing the au.com.dius.pact:consumer:4.6.1 in Intellij

### ISSUE THREAD

**Issue by Subhojit-Dey1234** [pact-foundation/pact-jvm#1697]
I am having issue in installing  `au.com.dius.pact:consumer:4.6.1` in Intellij.
<img width="970" alt="Screenshot 2023-06-23 at 8 58 31 PM" src="https://github.com/pact-foundation/pact-jvm/assets/66687621/f54c68f4-a034-4d45-9524-46c08b09f701">

**Comment by rholshausen** [comment]
Try now, it seems to be available https://central.sonatype.com/artifact/au.com.dius.pact/consumer/4.6.1/versions

**Comment by Subhojit-Dey1234** [comment]
Same nothing is working. I forgot to mention I am using this command for downloading.
`implementation 'au.com.dius.pact.consumer:junit5:4.6.1'` 
in the dependencies of build.gradle. Is it correct?

**Comment by Subhojit-Dey1234** [comment]
Ok this is solved. I was using a gradle version `7.4` after updating to `8.1` everything is working fine.  I am closing this issue.
