### ISSUE TITLE
gRPC plugin error with configuration

### ISSUE THREAD

**Issue by Subhojit-Dey1234** [pact-foundation/pact-jvm#1699]
I am getting this error while running the Provider test.

`io.pact.plugins.jvm.core.PactPluginValidationForInteractionException: Plugin protobuf failed to validate the interaction: Plugin configuration item with key '8d2f33efe1e67191da02b7ba19ad5733' is required. Received config ["5cf2b6380e0b780079ff3d630c0f6c71"]
`

**Comment by rholshausen** [comment]
There is a mismatch in your Pact file. Try run a clean before the consumer tests are run.

**Comment by Subhojit-Dey1234** [comment]
Yup got it. Thanks for the help. Its working.
