### ISSUE TITLE
Maven Plugin: Authorisation error when running create-version-tag

### ISSUE THREAD

**Issue by JoaoGFarias** [pact-foundation/pact-jvm#1711]
When using Pact-JVM 4.6.2, I am able to run _can-i-deploy_, receiving the PactFlow's response.

However, afterwards, when I run _create-version-tag_, I receive the following error:

> Failed to fetch the root HAL document: Request to path '/' failed with response 401 -> [Help 1]

The Maven command I am using is:

> mvn pact:create-version-tag -Dpacticipant=MY_PACTICIPANT -DpacticipantVersion=MY_VERSION -Dtag='DeployedTo${environment}'

The Pacticipant and version are double checked to exist in the Broker.

Any ideas why I receive a reply from Maven's _can-i-deploy_, but not from _create-version-tag_?

**Comment by rholshausen** [comment]
401 is normally due to invalid credentials. Check how you have set those for the can-i-deploy call.

**Comment by JoaoGFarias** [comment]
Correct @rholshausen. There was an internal library in my team that created the auth problem.
Closing as a non-issue.
