### ISSUE TITLE
Supply branch when publishing Pact JVM Client pact to pact-foundation.pactflow.io

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-jvm#1714]
See https://pact-foundation.pactflow.io/overview/provider/Pact%20Broker/consumer/JVM%20Pact%20Broker%20Client

Currently, the pact is not being picked up when the verification is being run because there is no branch information.

<img width="639" alt="Screenshot 2023-09-05 at 11 02 57 am" src="https://github.com/pact-foundation/pact-jvm/assets/446228/61a734e5-f672-4179-929c-0757d220414f">

If you fancy setting up a `record-release` in the pipeline when a version of pact jvm is released, I can also verify the "deployed and released" versions.

**Comment by rholshausen** [comment]
Branch has been added, but it will probably always be master.

**Comment by bethesque** [comment]
That's fine, it just needs a branch to be picked up by the selectors.
