### ISSUE TITLE
Unstable key generation with multiple provider states

### ISSUE THREAD

**Issue by rkrishnan2012** [pact-foundation/pact-jvm#1717]
Hello,

I am using the Pact JVM + Pact protobuf plugin to generate a consumer contract, but upon re-running the same consumer test twice, there are two interactions created (same contents, just different key). I narrowed it down to only happening when I have a single provider state with multiple parameters passed in, like so:

```
"providerStates": [
        {
          "name": "a user profile exists",
          "params": {
            "email_address": "test@email.com",
            "family_name": "Test",
          }
        }
],
```

Is this a bug in the pact JVM or in the protobuf plugin? It seems eerily similar to [this bug](https://github.com/pact-foundation/pact-reference/issues/264#issuecomment-1527472595) but seems like that's closed.

**Comment by rholshausen** [comment]
That fix should be in the latest version of the protobuf plugin, check that you have updated it. I'll check Pact-JVM to see if there is an issue there.

**Comment by rkrishnan2012** [comment]
Closing this for now until we can repro this locally. Thanks!
