### ISSUE TITLE
Question: PactDSLJsonArray - match only a number of objects from JsonArray

### ISSUE THREAD

**Issue by vasile21** [pact-foundation/pact-jvm#1719]
I have a question in relation to PactDSLJsonArray. I have a json array response like: 
```
 [
   {"fieldA": 1, "fieldB": "2", "fieldC": 3, "field4":[{"name":  "q", "value": "a"},{"name":  "b", "value": 123}]},
   {"fieldA": 1, "fieldB": "2", "fieldC": 3, "fieldD": "optional1","field4":[{"name":  "q", "value": "a"},{"name":  "b", "value": 123},{"name":  "optional2", "value": true}]},
   {"fieldA": 1, "fieldB": "2", "fieldC": 3, "field4":[{"name":  "q", "value": "a"},{"name":  "b", "value": 123},{"name":  "c", "value": true},{"name":  "optional2", "value": true}]}
   {"fieldA": 1, "fieldB": "2", "fieldC": 3, "fieldD": "optional1", "field4":[{"name":  "q", "value": "a"},{"name":  "b", "value": 123},{"name":  "optional2", "value": true}]}
 ]
```
Is there any possibility to write a validation just for object 2 and object 4 from the array? Match that a given number of objects is matching the given pattern?  I ask this because my consumer is greedier than the minimum response structure from the provider.

I looked around in PactDSLJsonArray class, but I couldn't find any.
I use pact-jvm-consumer-junit5 with version 4.0.10.

**Comment by rholshausen** [comment]
> I use pact-jvm-consumer-junit5 with version 4.0.10
That is a very old version, and no longer supported.

There is an array contains matcher that can check for specific items in an array, but it requires V4 Pacts, which is not supported for that version.

**Comment by vasile21** [comment]
thanks for your answer.
I will update my library to the indicated version.
