### ISSUE TITLE
Failed to resolve parameter [au.com.dius.pact.core.model.messaging.MessagePact messagePact]

### ISSUE THREAD

**Issue by kenliao94** [pact-foundation/pact-jvm#1722]
Hi, I wrote a passing message pact consumer test that has the following lines

```
import au.com.dius.pact.core.model.messaging.MessagePact;

@Test
@PactTestFor(pactMethod = "createPact")
void testCompanyDetailsListener_succeeded(MessagePact messagePact) throws Exception {
   // .... testing logic
}
```

The gradle file looks something like

```
plugins {
    id 'java'
    id 'idea'
    id 'jacoco'
    id 'org.springframework.boot' version '2.7.14'
    id 'io.spring.dependency-management' version '1.1.3'
    id "org.sonarqube" version "4.3.0.3225"
    id 'nu.studer.jooq' version '8.2.1'
    id 'com.github.davidmc24.gradle.plugin.avro-base' version '1.6.0'
    id 'com.github.ben-manes.versions' version '0.47.0'
    id "com.github.node-gradle.node" version "6.0.0"
    id "au.com.dius.pact" version "4.3.10"
}

dependencies {
    testImplementation('au.com.dius.pact.provider:junit5:4.5.3')
}
```

It was passing and generated a pact file. However, once I add the provider dep to the dependencies: 

```
dependencies {
    testImplementation("au.com.dius:pact-jvm-consumer-junit5:4.0.10")
    testImplementation('au.com.dius.pact.provider:junit5:4.5.3')
}
```

That test fails with 

Failed to resolve parameter [au.com.dius.pact.core.model.messaging.MessagePact messagePact] in method [....] java.lang.String au.com.dius.pact.core.support.expressions.ExpressionParser.parseExpression$default(java.lang.String, au.com.dius.pact.core.support.expressions.ValueResolver, int, java.lang.Object)'
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [au.com.dius.pact.core.model.messaging.MessagePact messagePact] in method [....]

I am pretty sure the newly added testImplementation is the culprit, but I don't know how to resolve it or if it is indeed a bug in the library. Would appreciate any help with resolving this error.

**Comment by rholshausen** [comment]
Don't mix major versions of the Pact-JVM libraries. You're using 3 different versions.
```
id "au.com.dius.pact" version "4.3.10"

testImplementation("au.com.dius:pact-jvm-consumer-junit5:4.0.10")
testImplementation('au.com.dius.pact.provider:junit5:4.5.3')
```
