### ISSUE TITLE
Question: How to exclude pact-jvm metadata from pact json

### ISSUE THREAD

**Issue by huehnerlady** [pact-foundation/pact-jvm#1725]
Hi, 

we run into the problem, that the pact is "changed" after every dependency update, hence it has to be verified, because the metadata changes. I do understand, that metadata like the pact specification is important, but why is the `pact-jvm` version important?

We are not yet in the position of having the perfect flow, so my question is, if there is any way to exclude that field from the pact jsons, so we do not have a changing pact after every single dependency update?

Cheers

**Comment by YOU54F** [comment]
you can't exclude it, it's part of the core library. the metadata shouldn't cause the pact to be re verified, you possibly have other random data or your workflow is set to verify on contract published and not contract requiring verification publish
