### ISSUE TITLE
Support `object` and `array` expectation without specifying consumer in LambdaDSL

### ISSUE THREAD

**Issue by biergit** [pact-foundation/pact-jvm#1737]
In my consumer test I want to expect an object but I do not care about any members.
With the LambdaDSL I have to write `body.object("attributeName", object -> {})`
I would prefer to write `body.object("attributeName")` or if you don't want to introduce another method I would like to be able to write
`body.object("attributeName",null)`.

**Comment by rholshausen** [comment]
4.6.8 released with this change
