### ISSUE TITLE
Usage of Xerces appears to cause org.xml.sax.SAXNotRecognizedException when using Gradle 8.4+

### ISSUE THREAD

**Issue by frankjkelly** [pact-foundation/pact-jvm#1743]
Due to the following change in Gradle 8.4
https://docs.gradle.org/current/userguide/upgrading_version_8.html#xml_parsing_now_requires_recent_parsers

It appears that the pact plugin for gradle (which uses xerces) causes a SAXNotRecognizedException to occur when we resolve configurations using this algorithm

https://docs.gradle.org/current/userguide/dependency_management.html#ex-resolving-all-configurations

(I'm not 100% sure but we don't get this error in projects that do no use the pact plugin and the only dependency in the build logic we can find that uses Xerces is the pact plugin)

**Comment by rholshausen** [comment]
4.6.4 released with xerces removed
