### ISSUE TITLE
Arrays with plain integers

### ISSUE THREAD

**Issue by Felix-Dyck** [pact-foundation/pact-jvm#1765]
(android, kotlin and library: au.com.dius.pact" version "4.3.10")

Hello,
I have certain type of json format I want to verify:

```
[...]
"months": [
        4,
        5,
        6,
        7,
        8
    ],
[...]
```

The array can be of any size and I want to verify that any value inside is of type Integer.
So I started with something like:

```
this.newArray("months") {
    this.integerType(4)
    this.integerType(5)
    this.integerType(6)
    this.integerType(7)
    this.integerType(8)
  }
```

  
While the generated array looks correct, the matching rules look like this:
```
"[...].months[0]": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "integer"
                }
              ]
            },
            "[...].months[1]": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "integer"
                }
              ]
            },
            "[...].months[2]": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "integer"
                }
              ]
            },
            "[...].months[3]": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "integer"
                }
              ]
            },
            "[...].months[4]": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "integer"
                }
              ]
            },
```

So every entry that I have given is expected and is matched by their value. When I have a longer actual array than, my verification will fail. When my values change, my verification will fail.

I have also seen eachLike and minArrayLike which solve some of the issues. But then there are other issues:

```
this.minArrayLike("months", 1) { arr ->
                                    arr.integerType(4)
                                    arr.integerType(5)
                                    arr.integerType(6)
                                    arr.integerType(7)
                                    arr.integerType(8)
                                }
```
-> then integerType needs a field "names". But I don't want these integers to have key.
Anyways, there is also `arr.integerType()` which doesn't take a parameter. But still, when the array will be generated, it will look like this:
```
"months": [
    {

    }
  ],
```
-> an object is expected. That why the verification will fail when actually receiving integers.

Same goes for eachLike. Here are also objects expected.

Thanks for reading.

**Comment by rholshausen** [comment]
Use `minArrayLike("months", 1, PactDslJsonRootValue.integerType(10))` - replace 10 with whatever example value you want in your tests.

**Comment by Felix-Dyck** [comment]
> minArrayLike("months", 1, PactDslJsonRootValue.integerType(10))

Thanks for the reply!

Unfortunately, this doesn't seem to work:
"`Type mismatch: inferred type is PactDslJsonRootValue but Consumer<LambdaDslObject!>! was expected`"
is what I get.

**Comment by rholshausen** [comment]
You need to use it on the outer object, not the inner one.

**Comment by rholshausen** [comment]
Oh, sorry, for minArrayLike it is `minArrayLike(String name, Integer size, PactDslJsonRootValue value, int numberExamples)` so
`minArrayLike("months", 1, PactDslJsonRootValue.integerType(10), 1)`
