### ISSUE TITLE
pact-jvm junit5 documentation is outdated

### ISSUE THREAD

**Issue by chenbojian** [pact-foundation/pact-jvm#1786]
The online documentation https://docs.pact.io/implementation_guides/jvm/consumer/junit5 is an old version.

The [createPact method](https://docs.pact.io/implementation_guides/jvm/consumer/junit5#2-create-a-method-annotated-with-pact-that-returns-the-interactions-for-the-test) is not compatible with V4Pact. 

But the content in github https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit5/README.md have a note for different syntax.
https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit5/README.md#2-create-a-method-annotated-with-pact-that-returns-the-interactions-for-the-test

**Comment by rholshausen** [comment]
Thanks for reporting this, the docs have now been synced

**Comment by YOU54F** [comment]
Thanks @chenbojian - our credentials for our docs sync job had expired, Ron pushed the changes manually yesterday and I've sorted the creds by switching to using our org level secret, which means it will updated in the future

sync job run in the docs repo, triggered by this repo

https://github.com/pact-foundation/docs.pact.io/actions/runs/8802450634/job/24158192257
