### ISSUE TITLE
`eachKeyLike` does not allow type matchers, only value matches and works unexpectedly with regexes.

### ISSUE THREAD

**Issue by nlandjev** [pact-foundation/pact-jvm#1813]
We are using Pact to verify a JSON response payload that satisfies the following properties:

1. The payload is an object that has a property called "a".
2. The value corresponding to the property "a" is also an object.
3. Each key inside the nested object matches a specific regular expression
4. The value corresponding to each nested object is also an object that has a key called "value" and a value of type string.

For example this object is valid (provided prop1 and prop2 match the regular expression):
```
{
  "a": {
    "prop1": {
       "value": "x"
    },
    "prop2": {
      "value": "y"
    }
 }
```

We use the following code to generate the Pact JSON file (snippet just for the object):

```
final var expectedBody = newJsonBody(body ->
    body.object("a", aObj -> {
        aObj.eachKeyLike("prop1", PactDslJsonRootValue.stingMatcher(REGEX, "prop1"));
        aObj.eachKeyLike("prop1", propObj -> proObj.stringType("value", "x"));
    }));
```

This generates the following Pact file (snippet just for the object):
```
"matchingRules": {
  "body": {
    "$.a": {
      "combine": "AND",
      "matchers": [
        {
          "match": "values"
        },
        {
          "match": "values"
        }
      ]
    },
    "$.a.*": {
      "combine": "AND",
      "matchers": [
        {
          "match": "regex",
          "regex": "<REGEX>"
        }
      ]
    },
    "$.a.*.value": {
      "combine": "AND",
      "matchers": [
        {
          "match": "type"
        }
      ]
    }
  }
}
```

This leads to a problem on the producer side that the body in the example above get accepted even if prop1 and prop2 don't match the regular expression. If we change the matchers in line 7 and 10 in the Pact JSON above to "match": "type", then the body gets rejected as expected. Is there a way to specify this with eachKeyLike? Or is there another way to specify a regex for the keys to match?

Regards, Nikolay

Relevant versions from the pom file:
au.com.dius.pact.consumer:junit5 -> 4.6.6
au.com.dius.pact.provider:junit5spring -> 4.6.6

**Comment by rholshausen** [comment]
The problem is that `eachKeyLike` doesn't do what you think. It applies the matching rules to the values, not the keys.

I'm going to deprecate those methods, and add ones that actually act on the keys.

**Comment by rholshausen** [comment]
I've added two new methods, so you can do something like
```java
newJsonBody(body ->
        body.object("a", aObj -> {
          aObj.eachKeyMatching(Matchers.regexp("prop\\d+", "prop1"));
          aObj.eachValueMatching("prop1", propObj -> propObj.stringType("value", "x"));
        }))
```

I think this is what you want.

**Comment by YOU54F** [comment]
Hey @nlandjev, are you able to test with the current version and confirm?

**Comment by rholshausen** [comment]
I'll release it soon (some time this week). I have one more change I want to get into the release first.

**Comment by rholshausen** [comment]
4.6.12 is released

**Comment by nlandjev** [comment]
Thank you, I will check it out next week and close the issue.

**Comment by nlandjev** [comment]
We've tested this and it works as expected. I'm closing the issue. Thanks for implementing :)
