### ISSUE TITLE
Add the ability to publish pact files to a broker to sbt plugin.

### ISSUE THREAD

**Issue by allenxiang** [pact-foundation/pact-jvm#226]
pact gradle plugin has the ability to publish pact files to a broker and we need something similar from sbt plugin.

**Comment by uglyog** [comment]
The folks at ITV has released a scala pact implementation, which includes pact broker support: https://github.com/ITV/scala-pact

**Comment by uglyog** [comment]
Closing this, as Scala and SBT support is provided by https://github.com/jbwheatley/pact4s or https://github.com/ITV/scala-pact.
