### ISSUE TITLE
Multiple interactions failing

### ISSUE THREAD

**Issue by oloo** [pact-foundation/pact-jvm#282]
I am trying to setup multiple interactions for the same path, HTTP method and header details and I keep getting the first response I define, contrary to the details in the README

This is the setup of service on the consumer side tests

  def uomService = new PactBuilder()

```
uomService {
    serviceConsumer CONSUMER
    hasPactWith PROVIDER
    port PORT
    uponReceiving('a POST in application/vnd.sysco.uom.purchases.list.v1+json with NO Purchases')
    withAttributes(
            headers: [
                    'Content-Type': 'application/vnd.sysco.uom.purchases.list.v1+json',
                    'Authorization': 'Bearer ' + apiKey
            ],
            method: 'post',
            path: PATH
    )
    willRespondWith(
            status: 200,
            headers: ['Content-Type': 'application/json'],
            body: []
    )

    uponReceiving('a POST in application/vnd.sysco.uom.purchases.list.v1+json with Purchases')
    withAttributes(
            headers: [
                    'Content-Type': 'application/vnd.sysco.uom.purchases.list.v1+json',
                    'Authorization': 'Bearer ' + apiKey
            ],
            method: 'post',
            path: PATH
    )
    willRespondWith(
            status: 200,
            headers: ['Content-Type': 'application/json'],
            body: [ids: [40, 30], errors: []]
    )
}
```

Multiple calls to said service with to that "PATH" with a POST result in and empty body

**Comment by uglyog** [comment]
Could you point me to the place in the readme you were referring to?

If there is more than one request that matches the incoming request, there is no way to determine which one to use to generate the response, so it uses the first one. If you want a particular response returned, you either need to make the match unique, or put them in seperate tests.

**Comment by alonpeer** [comment]
I just came across the same issue. I want to have multiple interactions with the same request, but for each one I have a different state and a different response (e.g. if user doesn't exist, then the response for a GET request will be 404, but if it does, it'll be 200).

@uglyog you suggest I put those in separate tests, which seems to solve this issue. But this makes the code a bit cumbersome and awkward. My real case actually has 4 different states for the same request, so I'll have to manage 4 different spec files. 

Perhaps the interaction to be consumed can somehow be tagged and hinted? I can't really think of a solution right now, but would like this issue to be kept open until we can figure out something.

**Comment by uglyog** [comment]
#349 and #159 are kind of related to this.

It would probably be useful to define global values for requests and responses, and then have them be overridden with specific values in individual tests. This will not help with the four different states.

As you suggested, this would require some flag to be set during the test to indicate to the mock server which response to return. Both these options can work together, but it will require a redesign of the mock server to be able to implement it.
