### ISSUE TITLE
pact-jvm not matching empty objects using Postel's law

### ISSUE THREAD

**Issue by BenSayers** [pact-foundation/pact-jvm#298]
If I have a consumer Pact file containing this response body:

``` json
"body": {
    "name": {
        "first": "Donald"
    }
}
```

And the provider returns this response:

``` json
{
    "name": {
        "first": "Donald",
        "last": "Duck"
    }
}
```

Then all is well, the provider verify passes. However if I change the consumer Pact file to this:

``` json
"body": {
    "name": {
    }
}
```

pact-jvm will return this error when the provider verifies the pact file:

```
$.body.name -> Expected an empty Map but received Map(first -> Donald, last -> Duck)
```

This seems like a bug to me. If its not a bug can you please let me know how I can write a consumer Pact file that asserts that the `name` property is defined within the response but does not care about what values are within the object.

**Comment by uglyog** [comment]
Not so much of a bug as a special case. I guess we did not think someone would want to specify an empty map that indicated they accept everything.

I'll have a look if using a like matcher will help in your case.

**Comment by uglyog** [comment]
Looks like it won't accept a matcher in that case, I'll need to fix that.

**Comment by uglyog** [comment]
Tested this with 4.2.9 and it works as expected: https://github.com/pact-foundation/pact-jvm/blob/master/provider/junit5/src/test/groovy/au/com/dius/pact/provider/junit5/VerifyEmptyObjectTest.groovy
