### ISSUE TITLE
injecting custom httpclient for pact-jvm-provider-lein

### ISSUE THREAD

**Issue by gregmcaree** [pact-foundation/pact-jvm#323]
we already have a wrapper around HTTP client that fetches the token for every request. is there anyway we can override provided http client with our custom one?

**Comment by uglyog** [comment]
Setting :create-client should be able to do this (https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-lein#modifying-the-http-client-used). Going back through the gitter history, I can't see if you had any issues with this?
