### ISSUE TITLE
Array containing at least one object with a field value not null

### ISSUE THREAD

**Issue by flaviuratiu** [pact-foundation/pact-jvm#378]
Hi.
I need to create a pact fragment verifying that the object array in the response contains at least one object with let's say a String field named "label" which is not null.
I know there will be objects in the array with label null, but I need to verify there's at least one with field not null.
Can this be done currently?
Thanks.

**Comment by uglyog** [comment]
If you want to ensure a field with a particular name is not null, you can do that. But if you need to check that there is any field that is not null, there is no current way to do that.

**Comment by flaviuratiu** [comment]
What I meant is I want to check that a specific field is not null in at least one object of the array.

For example, an array like this would be acceptable in my case:
`[
   { label: 'Test'; },
   { label: null; }
]`

But an array with the label field null in all objects of the array would not be acceptable:

`[
   { label: null; },
   { label: null; }
]`

Is there something like `minArrayLike` which could be used to verify there's at least one object in the array with the label field not null?

The following body example would fail because of the second object with label null:
`.body(new PactDslJsonBody().minArrayLike(1).stringType("label", "Test").closeObject().closeArray())`

**Comment by uglyog** [comment]
There is no way to do that at the moment. The matchers get applied to all objects in the collection.

**Comment by flaviuratiu** [comment]
I understand. Thanks for the quick response.

I think this would be a useful feature. Is it something you've considered adding in up-coming versions?

**Comment by uglyog** [comment]
That would change the way matchers are applied, and effects all the Pact implementations. It would need to be designed appropriately and done through the pact specification project.

**Comment by a-ster** [comment]
This will really be helpful in my scenario where I'm expecting a response with a summary of changes returned in an array but only the changed field will be available, i.e.
[
{
date: 20170101,
name: updatedName
},
{
date: 20170101,
address: updatedAddress
}
]

I was able to write a basic validation that date object is in the response but not the name and address objects. Is it possible to have a body matcher to check if the response body contains the expected objects? Thanks!

**Comment by QMG-kazala** [comment]
"If you want to ensure a field with a particular name is not null, you can do that" - how can it be done?

**Comment by uglyog** [comment]
Array contains matcher has been implemented. It will allow you to specify what has to be in the array, and ignores anything else.

See https://github.com/pact-foundation/pact-jvm/tree/master/consumer/junit#array-contains-matcher-v4-specification and https://github.com/pact-foundation/pact-jvm/tree/master/consumer/groovy#array-contains-matcher-v4-specification
