### ISSUE TITLE
Document usage of state in `@PactVerification`

### ISSUE THREAD

**Issue by fitzoh** [pact-foundation/pact-jvm#384]
In the [example message consumer test](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit%2Fsrc%2Ftest%2Fjava%2Fau%2Fcom%2Fdius%2Fpact%2Fconsumer%2Fv3%2FExampleMessageConsumerTest.java)

The following block is present:
```
    @Test
    @PactVerification({"test_provider", "SomeProviderState"})
    public void test() throws Exception {
        Assert.assertNotNull(new String(currentMessage));
    }
```

The javadoc for `@PactVerification` makes no mention of passing in the state.
```
    /**
     * the tested provider name.
     */
    String[] value() default "";
```

The documentation on the annotation should be updated to explain that the state can be passed in as a value, or the example should be updated.

**Comment by uglyog** [comment]
There are two problems, the example test is wrong and that the annotation can take multiple provider names as only the first one will be used.

**Comment by uglyog** [comment]
I've corrected the examples. `@PactVerification` does support multiple values, but they are the provider names.
