### ISSUE TITLE
[PACT-jvm-provider-junit] Being able to run provider tests not only against tags but against specific versions

### ISSUE THREAD

**Issue by Thadir** [pact-foundation/pact-jvm#398]
Goodday,

As a improvement we would like to see the possibility in the provider test to be able to use specific tags (like 2.0.3 / 2.1.0 / 2.1.1 / 2.2.0 / 2.2.1 / 2.2.2 / 2.2.3) so we can keep an eye out on how long our backwards compatibility list is and when we need to start talking with a team about upgrading there implementation version/client version.

At the moment this seems not to be posible in the current version.

**Comment by uglyog** [comment]
Not sure I understanding the issue, could you not include those tags as in https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/README.md#version-324246---using-tags-with-the-pact-broker

Or are you wanting to use specific versions of the pacts?

**Comment by uglyog** [comment]
Selecting the pacts to verify is now done with consumer version selectors: https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/
