### ISSUE TITLE
matcher doesn't support the parameter in the path url

### ISSUE THREAD

**Issue by MichaelSu1983** [pact-foundation/pact-jvm#399]
We have a api to get id "rest/content/{id}", and the provider cannot provider a fixed id to match it. This is a very basic requirement to support it. Do we have plan to support it 

or how to get around it? do we have a way to tell pact runner to modify the id after downloading the pact file from pact broker?

http://stackoverflow.com/questions/42364412/pact-how-to-have-dynamic-path-with-valid-data-that-is-present-in-provider-data

**Comment by uglyog** [comment]
There is not an way to have values used between different requests with Pact. The only way to do this at the moment (as is mentioned in the link you provided) is to choose one ID and use that in the Pact tests, then use a provider state to setup the data so the provider will work with that ID.

**Comment by MichaelSu1983** [comment]
Hey, thanks for your reply.

There is a problem to set id in the provider side, since provider does not allow altering id in the db.

So do we have a way to use state and modify the id in the pact file when running provider tests? Is it possible to intercept the interaction in the path?

Thanks a lot.


-------- Original message --------

**Comment by gaurav517** [comment]
I have exact same problem. I think it would be nice to be able to intercept and change the interaction in provider state functions.

As a work around, I am using Id as 1 and 2..etc in consumer tests.. and on provider side I have empty database to start with so it works.. but there might be cases where it would be difficult to work like this.

**Comment by uglyog** [comment]
You can modify the requests using a request filter when running the verification. But I would be very careful using this, just in case you modify the request in a way that invalidates the contract.

**Comment by uglyog** [comment]
This is handled with provider state injection: https://github.com/pact-foundation/pact-jvm/tree/master/consumer#having-values-injected-from-provider-state-callbacks
