### ISSUE TITLE
au.com.dius.pact.consumer.PactGenerator does not clean up between pact file writes.

### ISSUE THREAD

**Issue by nosynose** [pact-foundation/pact-jvm#409]
I am using pact-jvm-consumer-junit to generate pact. au.com.dius.pact.consumer.PactGenerator is writing pact files behind the scene.  

My project has 5 pact gen junit class. PactGenerator needs to write 5 pact files. Everything works out fine if I run each junit individually in STS/Eclipse. 

When I run these 5 junit classes with "maven test", things becomes interesting. Since there is only one JVM, there is only one PactGenerator instance. This instance is reused to write these 5 pact files.

The PactGenerator does not clean out the pact file storage between pact file writes. When running the second Junit. It has 2 pact files in its memory: the current one, and the the one from running the last junit test! So it will write the current pact file and it will also write the last pact file a second time, in the same directory of the current pact file. 

At the 3rd junit test, it writes 3 pact files. so on and so forth.

If all Junit test write the pact files to the same directory. This bug is harmless except being a little wasteful.

My 5 Junit tests happens to write pact files to different directories. So this bug causes all pact files to show up in the directory of the last pact file. 

Here is a little show of what goes on:

Running 1st Junit:
18:13:02.296 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceCreate -> Checkout to file target\pacts-do-not-publish\SelfServiceCreate-Checkout.json

Running 2nd Junit:
18:13:02.530 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceCreate -> Checkout to file target\pacts-do-not-publish\SelfServiceCreate-Checkout.json
18:13:02.530 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceGet -> Checkout to file target\pacts-do-not-publish\SelfServiceGet-Checkout.json

Running 3rd Junit:
18:13:02.983 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceCreate -> Checkout to file target\pacts-do-not-publish\SelfServiceCreate-Checkout.json
18:13:02.983 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceGet -> Checkout to file target\pacts-do-not-publish\SelfServiceGet-Checkout.json
18:13:02.983 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServicePatch -> Checkout to file target\pacts-do-not-publish\SelfServicePatch-Checkout.json

Running 4th Junit:
18:13:03.201 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceCreate -> Checkout to file target\pacts\SelfServiceCreate-Checkout.json
18:13:03.201 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceGet -> Checkout to file target\pacts\SelfServiceGet-Checkout.json
18:13:03.217 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServicePatch -> Checkout to file target\pacts\SelfServicePatch-Checkout.json
18:13:03.217 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfService -> Checkout to file target\pacts\SelfService-Checkout.json

Running 5th Junit:
18:13:03.513 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfService -> Checkout to file target\pacts\SelfService-Checkout.json
18:13:03.529 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServicePatch -> Checkout to file target\pacts\SelfServicePatch-Checkout.json
18:13:03.529 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceGet -> Checkout to file target\pacts\SelfServiceGet-Checkout.json
18:13:03.529 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfService -> ShoppingCart to file target\pacts\SelfService-ShoppingCart.json
18:13:03.544 [main] DEBUG au.com.dius.pact.consumer.PactGenerator - Writing pact SelfServiceCreate -> Checkout to file target\pacts\SelfServiceCreate-Checkout.json

**Comment by rholshausen** [comment]
Closing this as the PactGenerator class has been removed
