### ISSUE TITLE
Unable to pactVerify in docker against Spring Boot

### ISSUE THREAD

**Issue by abubics** [pact-foundation/pact-jvm#414]
See `docker_*.sh` in [project on github](https://github.com/DiUS/dius-mentor_boris_coffee-api).

I have a Spring Boot project in Kotlin, and (in the same repo) a test consumer to verify pacts against (in Groovy, but in a separate project).

In docker: I can `build test` the provider, and `build check pactPublish` the consumer, uploading the Pactfile to the SaaS broker.

But when I try to run `pactVerify` I get a JVM `SIGSEGV`. This happens in every JDK flavour I've tried so far, including: `openjdk:8`, `cogniteev/oracle-java:java8`, and `frolvlad/alpine-oraclejdk8`.

These are the last few console lines before the fault:

```
:compileTestKotlin UP-TO-DATE
:compileTestJava NO-SOURCE
:copyTestKotlinClasses UP-TO-DATE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:pactVerify_Coffee Ordering Provider
```

And attached are a couple of dumps, maybe they'll help :)

[hs_err_pid5.txt](https://github.com/DiUS/pact-jvm/files/960414/hs_err_pid5.txt)
[hs_err_pid8.txt](https://github.com/DiUS/pact-jvm/files/960415/hs_err_pid8.txt)

This is using gradle 3.4.1, from `app/gradle/wrapper/gradle-wrapper.properties`.

**Comment by uglyog** [comment]
The stack traces in the dumps are showing the failure is in the JAnsi library. It might be this bug https://github.com/fusesource/jansi/issues/66 or this https://github.com/fusesource/jansi/issues/55

**Comment by abubics** [comment]
Mmm thanks. I'll dig through the other solutions and workarounds :)

**Comment by uglyog** [comment]
I'm just running the project locally to verify the issue.

**Comment by uglyog** [comment]
And :boom:

**Comment by abubics** [comment]
Well, adding `-Dkotlin.colors.enabled=false` as per [this Kotlin bug](https://youtrack.jetbrains.com/issue/KT-17031) didn't help ;)

**Comment by uglyog** [comment]
Yeah, you need a `-Dpact.colors.enabled=false` that does just that

**Comment by uglyog** [comment]
You could disable console output as a work around: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-gradle/README.md#verification-reports-versions-327249

**Comment by uglyog** [comment]
Add `-t` to your docker run:

```
docker run \
  -v `pwd`:$mnt_dir -w $mnt_dir \
  -e pactBrokerAccount=$pactBrokerAccount \
  -e pactBrokerUsername=$pactBrokerUsername \
  -e pactBrokerPassword=$pactBrokerPassword \
  -t \ # <-----
  openjdk:8 \
  ./api_verify.sh
```

**Comment by abubics** [comment]
Great workaround \o/
My build is green now :D

**Comment by rholshausen** [comment]
Closing this as JAnsi was replaced with the Mordant library
