### ISSUE TITLE
Verification by tags from PACT Broker does not work

### ISSUE THREAD

**Issue by dosomecoding** [pact-foundation/pact-jvm#419]
I have tagged PACTS for a provider version 1.0.102 as dev and  version 1.0.101 as sit in Pact Broker. I am trying to verify PACTS from Pact broker using mvn pact:verify but I am getting following error message, so not sure if verification by tagging is fully supported or not using pact-jvm-provider-maven plugin
Failed to execute goal au.com.dius:pact-jvm-provider-maven_2.11:3.3.6:verify (default-cli) on project ProjectName: Execution default-cli of goal au.com.dius:pact-jvm-provider-maven_2.11:3.3.6:verify failed: Link 'pb:latest-provider-pacts-with-tag' was not found in the response, only the following links where found: [curies, pb:latest-pact-versions, pb:latest-provider-pacts, pb:pacticipants, pb:webhooks, self]. URL: 'http://serverhost:5000/pacts/provider/Provider1/latest', LINK: 'pb:latest-provider-pacts-with-tag' 

![image](https://cloud.githubusercontent.com/assets/28390034/25702298/ab81901a-3113-11e7-8b41-2ca2adb7aafd.png)

**Comment by uglyog** [comment]
Looks like your pact broker does not support the `pb:latest-provider-pacts-with-tag` link. What version of the pact broker are you running?

**Comment by rholshausen** [comment]
Closing as stale issue
