### ISSUE TITLE
pact verify matching problem in the body of eachKeyLike

### ISSUE THREAD

**Issue by ghost** [pact-foundation/pact-jvm#429]
I am trying to create a contract by using `eachKeyLike`.
```
new PactDslJsonBody()
     .object("documents")
        .eachKeyLike("/example/c5682f1f34ec673d54e7a5ba5ee39")
            .stringValue("name", "test-endpoint")
    .closeObject())
```
The contract looks like
```
"response": {
    "body": {
        "documents": {
            "/example/c5682f1f34ec673d54e7a5ba5ee39": {
                    "name": "test-endpoint"
            }
        }
    },
    "matchingRules": {
        "$.body.documents.*": {
            "match": "type"
            }
    }
}
```
The actual response from my example server is
```
{
  "documents": {
    "/example/c5682f1f34ec673d54f5bbc58164a": {
      "name": "test-endpoint0"
    }
}
```
The provider test passes. But the value of actual response("test-endpoint0") is not the same as the response in contract("test-endpoint"). I am using `stringValue`. So I expected they should be the same.  Is it an expected behavior? All the matching rule under the body of `eachKeyLike` will only do a type matching? If so, is there a way to do a value matching?

**Comment by uglyog** [comment]
`.eachKeyLike` sets up a cascading type matcher for all values of the map, which is why it is doing a type match and accepting `"name": "test-endpoint0"`.

There is a way specified in the V3 specification to reset the matching to equality, but this has not been implemented in the Java DSL yet.

**Comment by mingyangz1** [comment]
So can I write a pact file with V3 specification manually, and set the matching to equality? And it is used in provider side tests.

**Comment by uglyog** [comment]
Yes, but you need to use the 3.5.0 beta versions, and then add a `"match": "equality"` matcher definition to reset it back to equality.

something like

**Comment by rholshausen** [comment]
Correct way with latest Pact-JVM to do this:
```
new PactDslJsonBody()
     .object("documents")
        .eachKeyLike("/example/c5682f1f34ec673d54e7a5ba5ee39")
            .equalsTo(test-endpoint")
    .closeObject())
``
