### ISSUE TITLE
Does JVM @PactUrl provide basic auth options?

### ISSUE THREAD

**Issue by ghost** [pact-foundation/pact-jvm#430]
If not, is there any other way to provide it when using @PactUrl?

**Comment by uglyog** [comment]
`@PactUrl` can be extended with authentication options

**Comment by mingyangz1** [comment]
Tried to extend it and it works for me now. Thanks!

**Comment by tspoeri** [comment]
@mingyangz1 : this enhancement is still needed, can you please reopen the issue?

**Comment by uglyog** [comment]
Implemented for #1224
