### ISSUE TITLE
Add fuzzing to consumer tests

### ISSUE THREAD

**Issue by fitzoh** [pact-foundation/pact-jvm#432]
reposting from gitter:

> So I had an idea I pitched for spring cloud contracts that I pitched a little while ago, wanted to see what you guys thought about it…
> So if you’re using CDC you’re probably subscribing to postle’s law, and should be fine with a producer returning fields that aren’t required by the consumer. So my proposal is that you should be able to configure the mock server to return additional random fields and make sure that doesn’t break the consumer test. This would essentially be adding some fuzzing to consumer testing… thoughts?

**Comment by uglyog** [comment]
I like this idea, and will be exploring it further.

**Comment by rholshausen** [comment]
I think this is blurring the line between a Unit test and a Contract test. Contract test should be based on a valid contract between the consumer and provider. You can do these types of tests with normal Unit tests.
