### ISSUE TITLE
Provide option to run provider tests against ALL consumer versions.

### ISSUE THREAD

**Issue by fitzoh** [pact-foundation/pact-jvm#434]
Currently, you can provide a list of tags to run provider tests against.
It would be nice if there was a flag the user could set to run provider tests against all available versions of consumers.

**Comment by rholshausen** [comment]
This is supported with consumer version selectors. See https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors#verifying-pacts-where-the-consumer-is-a-mobile-application-1
