### ISSUE TITLE
SBT Basic Auth for hasPactsFromPactBroker

### ISSUE THREAD

**Issue by alex-voigt** [pact-foundation/pact-jvm#467]
I am trying to access a Pact Broker that uses Basic Auth via the SBT Provider Plugin. Works fine for accessing the list of pacts. But when it is trying to verify a Pact it fails because of authentification problems:

```
Verifying a pact between Alice and Bob
[from URL https://some.url/pacts/provider/Bob/consumer/Alice/version/1.0]
[trace] Stack trace suppressed: run last *:pactVerify for the full output.
[error] (*:pactVerify) groovy.json.JsonException: Unable to process url: https://some.url/pacts/provider/Bob/consumer/Alice/version/1.0
[error] Total time: 3 s, completed 21.06.2017 16:00:00
```

Issue #176 should have added the feature for adding basic authentifaction but it looks like that it was not ported to the SBT part. There is no second parameter provided for the options.

This is how I used it in the build.sbt:
```
SbtProviderPlugin.config ++ Seq(
  providers := Seq(
    ProviderConfig(name = "Bob"
    ).hasPactsFromPactBroker(new URL("https://username:password@some.url"))
  )
)
```

**Comment by danqa** [comment]
Hi there. Is there any update on this bug? We are trying to implement PACTs with sbt. We have it working but get 

```
Verifying a pact between X and Y
  [from Pact Broker https://blah.com/pacts/provider/x/consumer/y/version/6789]
[error] au.com.dius.pact.pactbroker.RequestFailedException: Request to path 'https://blah.com/pacts/provider/x/consumer/y/version/6789' failed with response 'HTTP/1.1 401 Unauthorized'
```

We are setting the basic auth values properly and see the pact being pushed up just cannot verify it. We believe issue this is is what is prevent this from working. An update would be most appreciated.

**Comment by uglyog** [comment]
No update. In the mean time, have a look at http://io.itv.com/scala-pact/

**Comment by rholshausen** [comment]
Closing this as Scala support is provided by https://github.com/jbwheatley/pact4s
