### ISSUE TITLE
what can i do to set proxy to connect the broker ?

### ISSUE THREAD

**Issue by yuqitao** [pact-foundation/pact-jvm#478]
when i run pact-work-shop , on step 13 , run ./gradlew :consumer:check , there is an error : time out .
i find the project need to connect the broker . i know i must set proxy . what can i do to set proxy to connect the broker ?

**Comment by uglyog** [comment]
Ah, yes, damn proxies. There is no current way of configuring the proxy directly.

There are system properties, but the way the HTTP client is setup needs to change to use those.

**Comment by yuqitao** [comment]
OK，thank you

**Comment by uglyog** [comment]
I'm leaving the issue open, as this needs to be fixed so you can use a proxy.

**Comment by yuqitao** [comment]
package au.com.dius.pact.provider.broker
HalClient.groovy

private newHttpClient() {
    http = new RESTClient(baseUrl)
    http.parser.'application/hal+json' = http.parser.'application/json'
    http.handler.'404' = {
      throw new NotFoundHalResponse("404 Not Found response from the pact broker (URL: '${baseUrl}'," +
        " LINK: '${lastUrl}')")
    }
    http
  }

can i set proxy here , use like : http.setProxy()

**Comment by uglyog** [comment]
Yes, that is one way to do it. I was hoping to use the proxy system properties (http.proxyHost, http.proxyPort) as defined here: https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/SystemDefaultHttpClient.html

**Comment by jaecktec** [comment]
any update on this?

**Comment by jaecktec** [comment]
I think this is solved, isn't it?:
https://github.com/pact-foundation/pact-jvm/blob/ed6e82c930baf6ca86ef6f5acae6b8ea91cd20e4/core/support/src/main/kotlin/au/com/dius/pact/core/support/HttpClient.kt#L68

**Comment by jaecktec** [comment]
Ah I think we should also use 'useSystemProperties()' here: 
https://github.com/pact-foundation/pact-jvm/blob/ed6e82c930baf6ca86ef6f5acae6b8ea91cd20e4/core/pactbroker/src/main/kotlin/au/com/dius/pact/core/pactbroker/HalClient.kt#L207

**Comment by jaecktec** [comment]
ok does not work with authentication and basic-auth:

https://github.com/pact-foundation/pact-jvm/blob/ed6e82c930baf6ca86ef6f5acae6b8ea91cd20e4/core/support/src/main/kotlin/au/com/dius/pact/core/support/HttpClient.kt#L123

should be switched to:

`val credsProvider = SystemDefaultCredentialsProvider()`
?

**Comment by YOU54F** [comment]
Can this be closed now due to https://github.com/pact-foundation/pact-jvm/pull/1491 being merged
