### ISSUE TITLE
DSL object attribute is array, but attribute name is a string of a number => key name is weird

### ISSUE THREAD

**Issue by maxant** [pact-foundation/pact-jvm#513]
Hi

If I create an object like this, its fine:

    new PactDslJsonBody().stringType("asdf").array("anArray").closeArray()

Result:

    {"asdf": "a random value", "anArray": []}

The same thing, just using "0" as the attribute name, rather than "anArray" causes the key to be an array. 

    new PactDslJsonBody().stringType("asdf").array("0").closeArray()

Result:

    {"asdf": "a random value", "['0']": []}

Why is the attribute name an array?

I want:

    {"asdf": "a random value", "0": []}

I.e. the attributes name should be the string of a number.

Same problem when the attribute name includes a space. 

Method "eachLike" has the same problem as method "array".

**Comment by uglyog** [comment]
Hmm, that should not do that. Looks like a defect.

**Comment by uglyog** [comment]
This has now been corrected.

**Comment by maxant** [comment]
Thanks a lot. Which version?

**Comment by uglyog** [comment]
It will be in the next version to be released, which will be 3.5.4
