### ISSUE TITLE
[pact-jvm-provider-junit] @Consumer annotation can't be set via environment variable

### ISSUE THREAD

**Issue by jefdo** [pact-foundation/pact-jvm#528]
Currently, the @Consumer annotation does not accept a ${env.variable} as an acceptable input as it doesn't have variable interpolation. The pact broker annotation has variable interpolation, and adding that functionality to the @Consumer annotation will allow pacts to be validated in a more targeted way.

**Comment by rholshausen** [comment]
Fix released with version 4.3.16
