### ISSUE TITLE
Change to broker default ordering will cause verification publishing from dev to override CI results

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-jvm#540]
In the next major release to the broker, I'm changing the default ordering of the pacts from "semantic version umber" to "date published". This means that when the verifications are automatically published with number '0', they will override the ones from the CI.

Can we either make a separate explicit 'publish verifications' task, or have a configurable switch that allows the developer to detect when the verification is running from the CI, and is turned off by default?

**Comment by uglyog** [comment]
I've added a property to disable publishing of results. I'm still undecided if results should only be published if the property turns the behaviour on instead (currently defaults to publish).

**Comment by bethesque** [comment]
Perhaps if no value is specified, you could publish, but also print out a warning about publishing from a dev box, and a note on how to configure it?
