### ISSUE TITLE
matching with dynamic values in the response body

### ISSUE THREAD

**Issue by RaghuJ** [pact-foundation/pact-jvm#592]
Hi, 

I'm having this pact: 

```
{
	"orderId": "123",

	"list": [{
		"item": 56,
		"quantity": 20,
		"orderId": "123"
	}, {
		"item": 23,
		"quantity": 20,
		"orderId": "123"
	}]
}
```

Is there a way I can write a DSL where I verify that orderId in the parent object matches the orderId in the child list?

**Comment by uglyog** [comment]
There is no mechanism to verify that different values in the body are equal to each other.
