### ISSUE TITLE
URL query is not beeing seperated from path

### ISSUE THREAD

**Issue by HerrDerb** [pact-foundation/pact-jvm#857]
I have a pact test in the same conifguration as:

```
     .path("/myservice/rest/myresource")
                        .query("geschaeftsNummer=12345678")
                        .method("POST")
                        .headers(requestHeaders)
                        .body(load("dokumente_post.json"))
                        .willRespondWith()
                        .headers(responseHeadersJson)
                        .status(404)
                        .toPact();
```

When executing my test, it fails with the reason of an "Unexpected Request" and the following output:

```
    Unexpected Request:
    	method: POST
    	path: /myservice/rest/myresource?geschaeftsNummer=12345678
    	query: [:]
```

It looks like the pact server does not seperate the query from the url and therefor fails to match the request, which actually would be correct.

**Comment by LoraV** [comment]
Have you tried putting a slash in front of "myservice" in your call to path()? I suspect that's your issue.

**Comment by HerrDerb** [comment]
Sorry, that was a typo as I had to replace the original url with the dummy url. The first slash for the path is present in the code.

**Comment by LoraV** [comment]
I see. So you’re sending both a JSON body and query parameters on a post?

**Comment by HerrDerb** [comment]
I see what you are pointing to, that does seem like an inconsistency... I'll have to check that, but I might not able to change the situation.

**Comment by uglyog** [comment]
@HerrDerb what version of Pact-JVM are you using?
