### ISSUE TITLE
PACT documentation is not available

### ISSUE THREAD

**Issue by vasile21** [pact-foundation/pact-jvm#886]
Multipe github pact documentation links seems to be broken (404 Page Not Found):
-https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-spring/README.md
- https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven
- https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-gradle

Steps to reproduce:
1. Search PACT jvm on google
2.  Click on a link that contains github.com/DiUS/pact-jvm/ 
3. Check displayed page

Results:
 -  404 page not found

**Comment by vasile21** [comment]
It seems that the links somehow changed and Google is still indexing the old links.
Fix:
add /provider after /master
e.g: https://github.com/DiUS/pact-jvm/tree/master/provider/pact-jvm-provider-maven => this is how it works

**Comment by uglyog** [comment]
Looks like the last time Google indexed the site was 29 May 2019 19:20:20 GMT.
